// Generated by scripts/generate-frame-layouts.mjs. Do not edit.
#pragma once
#include "Types.h"

namespace GeneratedLayouts {
static const GridCell FULL[] = {
  {0, 0, 4, 4, 0, CELL_XL},
};
static const int FULL_COUNT = sizeof(FULL) / sizeof(FULL[0]);
static const GridCell DEFAULT[] = {
  {0, 0, 4, 1, 0, CELL_SMALL},
  {0, 1, 4, 1, 1, CELL_SMALL},
  {0, 2, 4, 2, 2, CELL_LARGE},
};
static const int DEFAULT_COUNT = sizeof(DEFAULT) / sizeof(DEFAULT[0]);
static const GridCell PYRAMID[] = {
  {0, 0, 4, 1, 0, CELL_SMALL},
  {0, 1, 4, 1, 1, CELL_SMALL},
  {0, 2, 2, 2, 2, CELL_MEDIUM},
  {2, 2, 2, 2, 3, CELL_MEDIUM},
};
static const int PYRAMID_COUNT = sizeof(PYRAMID) / sizeof(PYRAMID[0]);
static const GridCell SQUARE[] = {
  {0, 0, 2, 2, 0, CELL_MEDIUM},
  {2, 0, 2, 2, 1, CELL_MEDIUM},
  {0, 2, 2, 2, 2, CELL_MEDIUM},
  {2, 2, 2, 2, 3, CELL_MEDIUM},
};
static const int SQUARE_COUNT = sizeof(SQUARE) / sizeof(SQUARE[0]);
}
