from pathlib import Path
p = Path('app/api/ski/summary/route.ts')
s = p.read_text()
old = """    const source = candidate._source\n    const id = fnuggCount(source?.id)\n    const name = String(source?.name || '').trim() || null\n    if (id == null || !name) return unavailableFnuggResort()\n\n    const liftsOpen = fnuggCount(source?.lifts?.open)\n"""
new = """    const source = candidate._source\n    const id = fnuggCount(source?.id)\n    const name = String(source?.name || '').trim() || null\n    if (id == null || !name) return unavailableFnuggResort()\n\n    let detailSource: any = source\n    try {\n      const detailUrl = new URL(`${FNUGG_API_BASE}/get/resort/${id}`)\n      detailUrl.searchParams.set('sourceFields', 'location,weather_zones,default_weather_zones')\n      const detailResponse = await fetch(detailUrl, {\n        headers: { Accept: 'application/json' },\n        next: { revalidate: 3600 },\n        signal: AbortSignal.timeout(5000),\n      })\n      if (detailResponse.ok) {\n        const detailPayload = await detailResponse.json().catch(() => null)\n        if (detailPayload?._source) detailSource = { ...source, ...detailPayload._source }\n      }\n    } catch {\n      // Resort status still works without altitude; powder estimation falls back to selected coordinates.\n    }\n\n    const liftsOpen = fnuggCount(source?.lifts?.open)\n"""
assert old in s
s = s.replace(old, new, 1)
s = s.replace("const resortLat = finiteNumber(source?.location?.lat)\n    const resortLon = finiteNumber(source?.location?.lon)\n    const weatherZones = Array.isArray(source?.weather_zones) ? source.weather_zones : []\n    const preferredTopId = String(source?.default_weather_zones?.top || '').trim()", "const resortLat = finiteNumber(detailSource?.location?.lat)\n    const resortLon = finiteNumber(detailSource?.location?.lon)\n    const weatherZones = Array.isArray(detailSource?.weather_zones) ? detailSource.weather_zones : []\n    const preferredTopId = String(detailSource?.default_weather_zones?.top || '').trim()", 1)
p.write_text(s)
print('patched Fnugg detail altitude lookup')
