from pathlib import Path
route_path = Path('app/api/ski/summary/route.ts')
home_path = Path('app/HomePageClient.tsx')
route = route_path.read_text()
home = home_path.read_text()

# Remove the unnecessary Fnugg detail fetch; live resorts often omit weather_zones even there.
start = route.index("    let detailSource: any = source\n")
end = route.index("    const liftsOpen = fnuggCount(source?.lifts?.open)\n", start)
route = route[:start] + route[end:]
route = route.replace("const resortLat = finiteNumber(detailSource?.location?.lat)\n    const resortLon = finiteNumber(detailSource?.location?.lon)\n    const weatherZones = Array.isArray(detailSource?.weather_zones) ? detailSource.weather_zones : []\n    const preferredTopId = String(detailSource?.default_weather_zones?.top || '').trim()", "const resortLat = finiteNumber(source?.location?.lat)\n    const resortLon = finiteNumber(source?.location?.lon)\n    const weatherZones = Array.isArray(source?.weather_zones) ? source.weather_zones : []\n    const preferredTopId = String(source?.default_weather_zones?.top || '').trim()", 1)

route = route.replace("basis: 'resort_top' | 'selected_location'", "basis: 'resort_top' | 'resort_location' | 'selected_location'", 2)

old = """async function loadPowderForecastTimeseries(resort: any, fallback: any[]) {\n  const resortLat = finiteNumber(resort?.forecast_lat)\n  const resortLon = finiteNumber(resort?.forecast_lon)\n  const elevation = finiteNumber(resort?.top_elevation_m)\n  if (resortLat == null || resortLon == null || elevation == null) {\n    return { timeseries: fallback, basis: 'selected_location' as const, elevationM: null }\n  }\n\n  const url = new URL('https://api.met.no/weatherapi/locationforecast/2.0/compact')\n  url.searchParams.set('lat', String(roundCoordinate(resortLat)))\n  url.searchParams.set('lon', String(roundCoordinate(resortLon)))\n  url.searchParams.set('altitude', String(Math.round(elevation)))\n\n  try {\n    const response = await fetch(url, {\n      headers: { Accept: 'application/json', 'User-Agent': MET_USER_AGENT },\n      next: { revalidate: 600 },\n      signal: AbortSignal.timeout(6000),\n    })\n    if (!response.ok) return { timeseries: fallback, basis: 'selected_location' as const, elevationM: null }\n    const payload = await response.json().catch(() => null)\n    const timeseries = Array.isArray(payload?.properties?.timeseries) ? payload.properties.timeseries : []\n    if (!timeseries.length) return { timeseries: fallback, basis: 'selected_location' as const, elevationM: null }\n    return { timeseries, basis: 'resort_top' as const, elevationM: elevation }\n  } catch {\n    return { timeseries: fallback, basis: 'selected_location' as const, elevationM: null }\n  }\n}\n"""
new = """async function loadPowderForecastTimeseries(resort: any, fallback: any[]) {\n  const resortLat = finiteNumber(resort?.forecast_lat)\n  const resortLon = finiteNumber(resort?.forecast_lon)\n  const explicitElevation = finiteNumber(resort?.top_elevation_m)\n  if (resortLat == null || resortLon == null) {\n    return { timeseries: fallback, basis: 'selected_location' as const, elevationM: null }\n  }\n\n  const url = new URL('https://api.met.no/weatherapi/locationforecast/2.0/compact')\n  url.searchParams.set('lat', String(roundCoordinate(resortLat)))\n  url.searchParams.set('lon', String(roundCoordinate(resortLon)))\n  if (explicitElevation != null) url.searchParams.set('altitude', String(Math.round(explicitElevation)))\n\n  try {\n    const response = await fetch(url, {\n      headers: { Accept: 'application/json', 'User-Agent': MET_USER_AGENT },\n      next: { revalidate: 600 },\n      signal: AbortSignal.timeout(6000),\n    })\n    if (!response.ok) return { timeseries: fallback, basis: 'selected_location' as const, elevationM: null }\n    const payload = await response.json().catch(() => null)\n    const timeseries = Array.isArray(payload?.properties?.timeseries) ? payload.properties.timeseries : []\n    if (!timeseries.length) return { timeseries: fallback, basis: 'selected_location' as const, elevationM: null }\n    const modelElevation = finiteNumber(Array.isArray(payload?.geometry?.coordinates) ? payload.geometry.coordinates[2] : null)\n    return {\n      timeseries,\n      basis: explicitElevation != null ? 'resort_top' as const : 'resort_location' as const,\n      elevationM: explicitElevation ?? modelElevation,\n    }\n  } catch {\n    return { timeseries: fallback, basis: 'selected_location' as const, elevationM: null }\n  }\n}\n"""
assert old in route
route = route.replace(old, new, 1)
home = home.replace("basis: 'resort_top' | 'selected_location'", "basis: 'resort_top' | 'resort_location' | 'selected_location'", 1)

route_path.write_text(route)
home_path.write_text(home)
print('patched resort-coordinate powder forecast')
