import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {aiFollowComposition,aiFollowLayout,aiFollowStudioPresets,fitAiFollowTitle,selectCurrentAiFollowUpdates,wrapAiFollowSummary} from '../app/lib/aiFollowResponsive.mjs'
import {responsiveCellProfile,studioRenderStrategy} from '../app/lib/responsiveCellProfile.mjs'

const profile=(c,r)=>responsiveCellProfile(c,r,c*196,r*114)
test('AI Follow routes every geometry responsively without a legacy variant',()=>{for(let c=1;c<=4;c++)for(let r=1;r<=4;r++){const strategy=studioRenderStrategy('assistant',c,r,c*196,r*114);assert.equal(strategy.path,'ai-follow-responsive');assert.equal(strategy.legacyVariant,null)}})
test('selection chooses current per Watch before read filtering and sorts independently of input order',()=>{const rows=[{id:'a1',watchId:'a',topicTitle:'A',summary:'old',createdAt:'2026-01-01T09:00:00Z',isRead:false},{id:'b',watchId:'b',topicTitle:'B',summary:'middle',createdAt:'2026-01-01T09:30:00Z',isRead:false},{id:'a2',watchId:'a',topicTitle:'A',summary:'new',createdAt:'2026-01-01T10:00:00Z',isRead:false}];assert.deepEqual(selectCurrentAiFollowUpdates({followingCount:2,updates:[...rows].reverse()}).map(x=>x.id),['a2','b']);assert.deepEqual(selectCurrentAiFollowUpdates({followingCount:1,updates:[rows[0],{...rows[2],isRead:true}]}),[])})
test('presets and all geometries allocate bounded non-overlapping content-sized groups',()=>{const inside=(a,b)=>b.x>=a.x&&b.y>=a.y&&b.x+b.width<=a.x+a.width+.01&&b.y+b.height<=a.y+a.height+.01,overlap=(a,b)=>a.x<b.x+b.width&&b.x<a.x+a.width&&a.y<b.y+b.height&&b.y<a.y+a.height;assert.deepEqual(Object.keys(aiFollowStudioPresets),['normal','long','extreme','empty']);for(const state of Object.values(aiFollowStudioPresets))for(let c=1;c<=4;c++)for(let r=1;r<=4;r++){const p=profile(c,r),co=aiFollowComposition(p,state),l=aiFollowLayout(p,co),cell={x:0,y:0,width:p.width,height:p.height};for(const x of [l.headerRect,l.quietPrimaryRect,l.quietSecondaryRect,l.updatesRect,l.overflowRect,...l.updateGroups.flatMap(g=>[g.groupRect,g.topicRect,g.summaryRect])].filter(Boolean))assert.ok(inside(cell,x));for(const g of l.updateGroups){assert.ok(inside(g.groupRect,g.topicRect));assert.ok(inside(g.groupRect,g.summaryRect))}for(let i=1;i<l.updateGroups.length;i++)assert.equal(overlap(l.updateGroups[i-1].groupRect,l.updateGroups[i].groupRect),false);if(l.overflowRect&&l.updateGroups.length)assert.equal(overlap(l.updateGroups.at(-1).groupRect,l.overflowRect),false);assert.ok(l.updateGroups.length<=6);assert.equal(new Set(l.updateGroups.map(g=>g.update.watchId)).size,l.updateGroups.length);if(c===1&&r===1)assert.ok(l.updateGroups.length<=1)}})
test('capacity is height-derived, shallow stays singular, overflow counts changed Watches',()=>{const state=aiFollowStudioPresets.extreme,shallow=aiFollowLayout(profile(4,1),aiFollowComposition(profile(4,1),state)),large=aiFollowLayout(profile(4,4),aiFollowComposition(profile(4,4),state));assert.equal(shallow.updateGroups.length,1);assert.ok(large.updateGroups.length>shallow.updateGroups.length);assert.ok(large.updateGroups.length<=6);assert.equal(large.overflow,selectCurrentAiFollowUpdates(state).length-large.updateGroups.length);const one=aiFollowLayout(profile(4,4),aiFollowComposition(profile(4,4),aiFollowStudioPresets.normal));assert.equal(one.updateGroups.length,1);assert.ok(one.updateGroups[0].groupRect.height<profile(4,4).height/2)})
test('quiet and zero-follow states remain distinct and pluralize in renderer',async()=>{const quiet=aiFollowComposition(profile(2,2),aiFollowStudioPresets.empty),zero=aiFollowComposition(profile(2,2),{followingCount:0,updates:[]});assert.equal(quiet.mode,'no-change');assert.equal(zero.mode,'zero-follow');assert.ok(aiFollowLayout(profile(2,2),quiet).quietPrimaryRect);const source=await readFile(new URL('../app/frame-simulator/FrameSimulator.tsx',import.meta.url),'utf8');assert.match(source,/No new updates/);assert.match(source,/Nothing followed yet/);assert.match(source,/Following.*topic/);assert.doesNotMatch(source.slice(source.indexOf('function drawResponsiveAiFollow'),source.indexOf('function drawStocks')),/fetch\(|Date\.now|setTimeout|setInterval/)})
test('measured fitting is word-aware and declaration exports match runtime',async()=>{const measure=(text,size)=>text.length*size;assert.equal(fitAiFollowTitle('International e-paper manufacturing',180,measure,{fontSize:10}).truncated,true);const wrapped=wrapAiFollowSummary('New listing matches your saved filters',190,2,measure,{fontSize:10});assert.deepEqual(wrapped.lines,['New listing matches','your saved filters']);const clipped=wrapAiFollowSummary('New listing matches your saved filters',220,1,measure,{fontSize:10});assert.equal(clipped.truncated,true);assert.match(clipped.lines[0],/…$/);const runtime=await readFile(new URL('../app/lib/aiFollowResponsive.mjs',import.meta.url),'utf8'),declarations=await readFile(new URL('../app/lib/aiFollowResponsive.d.mts',import.meta.url),'utf8');for(const name of [...runtime.matchAll(/export (?:const|function) (\w+)/g)].map(x=>x[1]))assert.match(declarations,new RegExp(`export (?:const|function) ${name}\\b`))})

test('quiet state uses width in shallow cells and keeps a centered vertical group elsewhere',()=>{const wide=aiFollowLayout(profile(4,1),aiFollowComposition(profile(4,1),aiFollowStudioPresets.empty)),tall=aiFollowLayout(profile(1,4),aiFollowComposition(profile(1,4),aiFollowStudioPresets.empty));assert.ok(wide.quietSecondaryRect);assert.ok(wide.quietSecondaryRect.x>wide.quietPrimaryRect.x+wide.quietPrimaryRect.width);assert.ok(tall.quietSecondaryRect.y>tall.quietPrimaryRect.y+tall.quietPrimaryRect.height)})
