import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
import { customPhysicalPayload, duplicateLayout, duplicateLayoutClientState, nextCustomLayoutName, normalizeLayoutName, orderedLayoutItems, remapAssignmentsAfterGeometryEdit, supportsPhysicalCustomCell, supportsPhysicalCustomLayout, validateCustomGeometry } from '../app/lib/customLayouts.mjs'
import { sortCells } from '../app/lib/frameLayoutEditor.mjs'

const cell=(slot,col,row,colSpan,rowSpan)=>({slot,col,row,colSpan,rowSpan})
const rows=[0,1,2,3].map(row=>cell(row,0,row,4,1))
const large=[cell(0,0,0,4,2),cell(1,0,2,4,2)]
const medium=[cell(0,0,0,2,2),cell(1,2,0,2,2),cell(2,0,2,2,2),cell(3,2,2,2,2)]
const full=[cell(0,0,0,4,4)]
const adaptive=[cell(0,0,0,4,1),cell(1,0,1,1,3),cell(2,1,1,3,3)]
const layout=(id,name,sortOrder,createdAt='2026-01-01T00:00:00Z')=>({id,deviceId:'frame',ownerUserId:'user',name,cells:rows,sortOrder,createdAt,updatedAt:createdAt})

test('four immutable built-ins lead and Add layout is permanent last',()=>{
  assert.deepEqual(orderedLayoutItems([]).map(x=>x.key),['default','pyramid','square','full','add-layout'])
  const items=orderedLayoutItems([layout('uuid-b','B',2),layout('uuid-a','A',1)])
  assert.deepEqual(items.map(x=>x.key),['default','pyramid','square','full','uuid-a','uuid-b','add-layout'])
  assert.equal(items[4].id,'uuid-a');assert.equal(items.at(-1).type,'add')
})
test('custom names normalize uppercase whitespace and Unicode before the character limit',()=>{assert.equal(normalizeLayoutName('  Morning   room  '),'MORNING ROOM');assert.equal(normalizeLayoutName(' blåbær  kjøkken '),'BLÅBÆR KJØKKEN');assert.equal(Array.from(normalizeLayoutName('ø'.repeat(45))).length,40)})
test('blank custom names advance from the highest numbered existing custom name',()=>{assert.equal(nextCustomLayoutName([]),'CUSTOM 1');assert.equal(nextCustomLayoutName([layout('a','CUSTOM 1',0)]),'CUSTOM 2');assert.equal(nextCustomLayoutName([layout('a','Morning',0),layout('b','Kitchen',1)]),'CUSTOM 1');assert.equal(nextCustomLayoutName([layout('a','custom 1',0),layout('b','CUSTOM 3',1)]),'CUSTOM 4')})
test('name is presentation, UUID remains identity through rename/edit',()=>{const original=layout('stable-uuid','Morning',0),renamed={...original,name:'Kitchen'},edited={...renamed,cells:large};assert.equal(edited.id,original.id)})
test('duplicate gets new UUID, copied geometry, normalized name and following order',()=>{const copy=duplicateLayout(layout('a','Morning',4),'b');assert.equal(copy.id,'b');assert.equal(copy.name,'MORNING COPY');assert.equal(copy.sortOrder,5);assert.deepEqual(copy.cells,rows)})
test('duplicate becomes the visible and active custom layout with independent assignments',()=>{const source=layout('original','Morning',0),copy=layout('duplicate','Morning copy',1),sourceAssignments={0:'date',1:'weather'},state=duplicateLayoutClientState([source],{original:sourceAssignments},source.id,copy);assert.deepEqual(state.layouts.map(item=>item.id),['original','duplicate']);assert.equal(state.carouselItemId,'duplicate');assert.equal(state.activeCustomLayoutId,'duplicate');assert.deepEqual(state.assignments.duplicate,sourceAssignments);assert.notEqual(state.assignments.duplicate,sourceAssignments);state.assignments.duplicate[0]='groceries';assert.equal(sourceAssignments[0],'date')})
test('all currently supported physical compositions pass',()=>{for(const cells of [rows,large,medium,full])assert.deepEqual(validateCustomGeometry(cells),{valid:true,errors:[],unsupportedSlots:[]})})
test('structural persistence accepts an adaptive 1x3 and 3x3 partition',()=>{
  assert.deepEqual(validateCustomGeometry(adaptive),{valid:true,errors:[],unsupportedSlots:[]})
  assert.equal(supportsPhysicalCustomLayout(adaptive.map(c=>({...c,module:'date'}))).valid,true)
})
test('unsupported cells and malformed geometry are rejected centrally',()=>{
  assert.equal(validateCustomGeometry(Array.from({length:16},(_,i)=>cell(i,i%4,Math.floor(i/4),1,1))).valid,true)
  assert.equal(validateCustomGeometry([cell(0,0,0,4,2),cell(0,0,2,4,2)]).errors.includes('duplicate_slot'),true)
  assert.equal(validateCustomGeometry([cell(0,0,0,4,2),cell(1,0,1,4,2)]).errors.includes('overlap'),true)
  assert.equal(validateCustomGeometry([cell(0,0,0,4,1)]).errors.includes('holes'),true)
  assert.equal(validateCustomGeometry([cell(0,0,0,5,4)]).errors.includes('out_of_bounds'),true)
  assert.equal(validateCustomGeometry([{slot:0,col:'0',row:0,colSpan:4,rowSpan:4}]).errors.includes('non_integer'),true)
  for(const invalid of [[cell(0,0,0,4,1)],[cell(0,0,0,4,2),cell(1,0,1,4,2)],[cell(0,0,0,5,4)]])assert.equal(validateCustomGeometry(invalid).valid,false)
})
test('physical contract contains geometry and modules but never CellSize',()=>{const source=layout('layout-uuid','Four rows',0),payload=customPhysicalPayload(source,{0:'date',1:'weather',2:'reminders',3:'groceries'});assert.equal(payload.layout,'custom');assert.equal(payload.custom_layout_id,'layout-uuid');assert.deepEqual(payload.cells[0],{...rows[0],module:'date'});assert.equal(JSON.stringify(payload).includes('CellSize'),false);assert.equal(customPhysicalPayload(source,{0:'date'}),null);assert.equal(customPhysicalPayload({...source,cells:adaptive},{0:'date',1:'weather',2:'surf'}),null)})
test('create and edit persistence use structural validation while frame writes retain the physical gate',async()=>{
  const page=await readFile(new URL('../app/HomePageClient.tsx',import.meta.url),'utf8')
  const post=await readFile(new URL('../app/api/custom-layouts/route.ts',import.meta.url),'utf8')
  const patch=await readFile(new URL('../app/api/custom-layouts/[id]/route.ts',import.meta.url),'utf8')
  const settings=await readFile(new URL('../app/api/device/save-settings/route.ts',import.meta.url),'utf8')
  assert.match(page,/submitLayoutDraft\(\)[\s\S]*validateCustomGeometry\(cells\)/)
  assert.match(post,/validateCustomGeometry\(body\.cells\)/)
  assert.match(patch,/validateCustomGeometry\(body\.cells\)/)
  for(const source of [page,post,patch,settings])assert.doesNotMatch(source,/requirePhysical/)
  assert.match(settings,/supportsPhysicalCustomLayout/)
  assert.match(page,/supportsPhysicalCustomLayout\(assigned\)[\s\S]*This layout isn’t supported on the frame yet\./)
})

test('physical support is explicitly module-aware',()=>{
  assert.equal(supportsPhysicalCustomCell({...cell(0,0,0,3,3),module:'date'}),true)
  assert.equal(supportsPhysicalCustomCell({...cell(0,0,0,3,3),module:'weather:2'}),true)
  for(const module of ['weatherfoo','reminders','countdown','surf','soccer','stocks','groceries','ai-follow','unknown',''])
    assert.equal(supportsPhysicalCustomCell({...cell(0,0,0,3,3),module}),false)
  assert.equal(supportsPhysicalCustomCell({...cell(0,0,0,4,1),module:'weather'}),true)
})
test('structural validation API cannot imply physical validation',async()=>{
  const [implementation,wrapper,declaration]=await Promise.all(['../app/lib/customLayouts.mjs','../app/lib/customLayouts.ts','../app/lib/customLayouts.d.mts'].map(path=>readFile(new URL(path,import.meta.url),'utf8')))
  for(const source of [implementation,wrapper,declaration])assert.doesNotMatch(source,/requirePhysical/)
  assert.match(wrapper,/options\?:\{requireModules\?:boolean\}/);assert.match(declaration,/options\?: \{requireModules\?: boolean\}/)
})
test('editor geometry assigns deterministic slots only at serialization',()=>{const editor=rows.toReversed().map(({slot:ignored,...geometry})=>({...geometry,id:`saved:${ignored}`,moduleId:'empty'}));assert.equal(editor.some(value=>'slot' in value),false);const serialized=sortCells(editor).map((value,slot)=>({slot,col:value.col,row:value.row,colSpan:value.colSpan,rowSpan:value.rowSpan}));assert.deepEqual(serialized,rows)})
test('no-op edit keeps slot assignments while changed geometry clears ambiguous cells',()=>{const assignments={0:'date',1:'weather',2:'reminders',3:'groceries'};assert.deepEqual(remapAssignmentsAfterGeometryEdit(rows,rows,assignments),assignments);assert.deepEqual(remapAssignmentsAfterGeometryEdit(rows,large,assignments),{0:null,1:null});const reordered=rows.toReversed().map((value,index)=>({...value,slot:index}));assert.deepEqual(remapAssignmentsAfterGeometryEdit(rows,reordered,assignments),{0:'groceries',1:'reminders',2:'weather',3:'date'})})
test('custom creation and editing use the inline Frame tab state',async()=>{
  const page=await readFile(new URL('../app/HomePageClient.tsx',import.meta.url),'utf8')
  const library=await readFile(new URL('../app/components/CustomLayoutLibrary.tsx',import.meta.url),'utf8')
  assert.match(page,/carouselItemId==='add-layout' \? \{title:'CUSTOM',subtitle:'Tap \+ to create your own layout'\}/)
  assert.match(page,/onAdd=\{beginCreateLayout\}/)
  assert.match(page,/editorMode\?<InlineCustomLayoutEditor/)
  assert.match(page,/aria-label="Layout name"/)
  assert.doesNotMatch(page,/aria-label="Layout name" autoFocus/)
  assert.match(page,/SAVE LAYOUT/)
  assert.match(page,/layoutFlow\?\.mode==='edit'.*DELETE LAYOUT/)
  assert.match(page,/layoutFlow\.layout\.id.*method:'PATCH'/)
  assert.doesNotMatch(library,/CustomLayoutFlow|New layout|Continue|fixed inset-0/)
  assert.match(library,/4 by 4 custom layout editor/)
  const inlineEditor=library.slice(library.indexOf('export function InlineCustomLayoutEditor'))
  assert.doesNotMatch(inlineEditor,/rounded-\[22px\]|bg-\[color:var\(--card-bg\)\]/)
})
test('custom layouts share the open Frame canvas and render their saved geometry',async()=>{
  const page=await readFile(new URL('../app/HomePageClient.tsx',import.meta.url),'utf8')
  const library=await readFile(new URL('../app/components/CustomLayoutLibrary.tsx',import.meta.url),'utf8')
  assert.match(page,/customLayout\?<CustomLayoutPreview cells=\{customLayout\.cells\}/)
  assert.doesNotMatch(page,/Add a module to every cell before updating the frame/)
  assert.match(library,/data-layout-surface="open"/)
  assert.match(library,/data-layout-cell=/)
  assert.match(library,/internalDividerSegments\(/)
  const preview=library.slice(library.indexOf('export function CustomLayoutPreview'),library.indexOf('export function AddLayoutCard'))
  assert.doesNotMatch(preview,/rounded-\[22px\]|bg-\[color:var\(--card-bg\)\]/)
})
test('inline editor exposes its dotted grid and reactive cell dividers',async()=>{
  const library=await readFile(new URL('../app/components/CustomLayoutLibrary.tsx',import.meta.url),'utf8')
  assert.match(library,/aria-label="4 by 4 dotted guide"/)
  assert.match(library,/\[1,2,3\]\.map/)
  assert.match(library,/data-layout-divider=\{divider\.axis\}/)
  assert.match(library,/if\(result\.valid\)onChange\(result\.cells\)/)
  assert.match(library,/cells=\{withSlots\(pendingStroke\?\.valid\?pendingStroke\.cells:cells\)\}/)
  assert.match(library,/finalizeDividerStroke\(cells,state\.start,end/)
  assert.doesNotMatch(library,/overwriteWithSelection|dragSelectionFromPointers|resolveShortTap/)
  assert.doesNotMatch(library,/mergeCellsInSelection/)
  assert.match(library,/data-layout-guide="vertical"[^>]+border-l border-dotted/)
  assert.match(library,/data-layout-divider=\{divider\.axis\}[\s\S]+editorGuide\?'bg-\[color:var\(--fg-60\)\]'/)
  assert.match(library,/editorGuide\?'w-0\.5 -translate-x-1\/2':'w-px'/)
  assert.match(library,/editorGuide\?'h-0\.5 -translate-y-1\/2':'h-px'/)
  assert.match(library,/\{editorGuide&&<div aria-label="4 by 4 dotted guide"/)
})
test('inline editor previews snapped drags without mutating geometry and safely cancels',async()=>{
  const library=await readFile(new URL('../app/components/CustomLayoutLibrary.tsx',import.meta.url),'utf8')
  const editor=library.slice(library.indexOf('export function InlineCustomLayoutEditor'))
  assert.match(editor,/latestRaw:Point;latestClamped:Point;lock\?:DividerStrokeLock;meaningful:boolean/)
  assert.match(editor,/current=clampPointToViewport\(raw,viewport\(e\.currentTarget\)\)/)
  assert.match(editor,/Math\.hypot\(current\.x-start\.x,current\.y-start\.y\)<MIN_STROKE_PX\)\{setPendingStroke\(null\)/)
  assert.match(editor,/previewDividerStroke\(cells,\{start,end:current,lock:drag\.current\.lock\}/)
  assert.match(editor,/data-layout-pending-stroke=/)
  assert.match(editor,/rounded-full bg-\[#2aa3ff\]/)
  assert.match(editor,/pendingStroke\.normalized\.boundary\*25[\s\S]*pendingStroke\.normalized\.rangeEnd-pendingStroke\.normalized\.rangeStart/)
  assert.match(editor,/aria-label="Inferred divider completion"/)
  assert.match(editor,/bg-\[#2aa3ff\]\/70/)
  assert.match(editor,/onPointerMove=\{move\}/);assert.match(editor,/onPointerCancel=\{cancel\}/);assert.match(editor,/onLostPointerCapture=\{lostCapture\}/)
  assert.match(editor,/lost\?state\.latestClamped:clampPointToViewport/)
  assert.match(editor,/if\(lost&&!state\.meaningful\)\{clearDrag\(e\.pointerId\);return\}/)
  assert.match(editor,/const result=finalizeDividerStroke\(cells,state\.start,end/)
  assert.match(editor,/const cancel=.*clearDrag\(e\.pointerId\)/)
  assert.doesNotMatch(editor,/onPointerLeave|onPointerOut/)
  assert.doesNotMatch(editor,/pendingSelection|resolveShortTap|splitCellAtBoundary/)
  const page=await readFile(new URL('../app/HomePageClient.tsx',import.meta.url),'utf8')
  assert.match(page,/Draw to split · trace to erase/)
})
test('only saved custom headers offer the quiet inline edit control',async()=>{
  const page=await readFile(new URL('../app/HomePageClient.tsx',import.meta.url),'utf8')
  assert.match(page,/customLayout&&<button type="button" aria-label="Edit custom layout"/)
  assert.match(page,/onClick=\{\(\)=>onEdit\(customLayout\)\}/)
  assert.match(page,/function beginEditLayout\(layout:CustomLayout\)\{setLayoutDraftName\(layout\.name\);setLayoutDraftCells\(editorCells\(layout\.cells\)\)/)
  assert.match(page,/layoutFlow\.layout\.id.*method:'PATCH'/)
  assert.match(page,/layoutFlow\?\.mode==='edit'&&<button type="button" onClick=/)
  assert.equal((page.match(/>DELETE LAYOUT<\/button>/g)||[]).length,1)
  assert.doesNotMatch(page,/Manage custom layout|customMenuOpen|onToggleMenu|>•••<|Rename.*Duplicate/)
})
test('Add Layout is centered directly on the open canvas without card treatment',async()=>{
  const library=await readFile(new URL('../app/components/CustomLayoutLibrary.tsx',import.meta.url),'utf8')
  const add=library.slice(library.indexOf('export function AddLayoutCard'),library.indexOf('export function InlineCustomLayoutEditor'))
  assert.match(add,/className="h-full w-full text-\[color:var\(--fg-60\)\]"/)
  assert.match(add,/>\+<\/span><span[^>]+>Add layout<\/span>/)
  assert.doesNotMatch(add,/rounded|border|bg-\[/)
})
test('saved custom modules use geometry-aware fitting without changing built-in labels',async()=>{
  const page=await readFile(new URL('../app/HomePageClient.tsx',import.meta.url),'utf8')
  const library=await readFile(new URL('../app/components/CustomLayoutLibrary.tsx',import.meta.url),'utf8')
  assert.match(page,/renderCellLabel=\{\(assignment,cell\)=><AdaptiveCustomCellLabel[^>]+colSpan=\{cell\.colSpan\} rowSpan=\{cell\.rowSpan\}/)
  assert.match(page,/function AdaptiveCustomCellLabel\([\s\S]*module\?moduleLabel\(language,module\):'\+'/)
  assert.match(page,/rowSpan>colSpan&&rotated>horizontal\*1\.15/)
  assert.match(page,/Math\.min\(1,availableWidth\/labelWidth,availableHeight\/labelHeight\)/)
  assert.match(page,/data-orientation=\{fit\.rotated\?'rotated':'horizontal'\}/)
  assert.match(page,/function FrameCellLabel\([\s\S]*module\?moduleLabel\(language,module\):'\+'/)
  assert.match(page,/module\?'text-\[color:var\(--fg\)\] font-semibold text-lg':'text-\[color:var\(--fg-50\)\] text-2xl'/)
  assert.match(page,/const body = content \?\? <FrameCellLabel language=\{language\} module=\{module\}\/>/)
  assert.match(library,/absolute z-10 flex items-center justify-center overflow-hidden/)
})
test('legacy custom headers display uppercase and blank creates do not show a name error',async()=>{
  const page=await readFile(new URL('../app/HomePageClient.tsx',import.meta.url),'utf8')
  assert.match(page,/title:normalizeLayoutName\(customLayouts\.find/)
  assert.match(page,/text-2xl font-semibold uppercase tracking-widest/)
  assert.match(page,/nextCustomLayoutName\(customLayouts\)/)
  assert.doesNotMatch(page,/Enter a name for your layout\./)
})
test('schema and routes enforce owner plus frame membership',async()=>{const sql=await readFile(new URL('../supabase/migrations/20260821120000_add_custom_layout_library.sql',import.meta.url),'utf8');assert.match(sql,/owner_user_id = auth\.uid\(\)/);assert.match(sql,/device_members/);assert.match(sql,/enable row level security/);const builder=await readFile(new URL('../app/api/device/frame-config/builder.ts',import.meta.url),'utf8');assert.match(builder,/supportsPhysicalCustomLayout/);assert.match(builder,/layout: 'default'/)})
