import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
const root = new URL('../', import.meta.url)
const modules=['date','reminders','weather','countdown','surf','soccer','stocks','groceries']
const sizes=['small','medium','large','xl']
test('all modules expose four shared visual contracts and Studio dispatchers',async()=>{const profiles=JSON.parse(await readFile(new URL('shared/module-layout-profiles.json',root)));const ui=await readFile(new URL('app/frame-simulator/FrameSimulator.tsx',root),'utf8');for(const module of modules){assert.ok(profiles[module]);for(const size of sizes)assert.ok(profiles[module][size],`${module}.${size}`);assert.match(ui,new RegExp(`draw${module[0].toUpperCase()+module.slice(1)}`))}})
test('supported geometry contract is unchanged and unsupported cells remain explicit',async()=>{const lib=await readFile(new URL('app/lib/frameSimulator.ts',root),'utf8');const ui=await readFile(new URL('app/frame-simulator/FrameSimulator.tsx',root),'utf8');for(const geometry of ["'4x1'","'2x2'","'4x2'","'4x4'"])assert.match(lib,new RegExp(geometry));assert.match(lib,/\.includes\(`\$\{colSpan\}x\$\{rowSpan\}`\)/);assert.match(ui,/UNSUPPORTED — NEEDS NEW VARIANT/)})
test('key physical parity invariants are declared and rendered',async()=>{const p=JSON.parse(await readFile(new URL('shared/module-layout-profiles.json',root)));const ui=await readFile(new URL('app/frame-simulator/FrameSimulator.tsx',root),'utf8');assert.equal(p.weather.xl.topColumns,3);assert.equal(p.weather.large.columns,4);assert.equal(p.surf.xl.topRegions,3);assert.equal(p.surf.xl.forecastColumns,4);assert.deepEqual(p.surf.large.labels,['Morning','Noon','Afternoon','Evening']);assert.equal(p.soccer.small.bottomStatRegions,3);assert.ok(p.soccer.large.standingsColumns.includes('Gap'));assert.equal(p.stocks.xl.detailGroups,3);assert.deepEqual(p.groceries.xl.topPanels,['Grocery List','Weekly Menu']);assert.deepEqual(p.countdown.xl.calendarMarkers,['crossedDay','targetCircle']);assert.match(ui,/weatherIcon/);assert.match(ui,/arrowIcon/);assert.match(ui,/ratingBlocks/);assert.match(ui,/globalCompositeOperation|fillStyle=ctx\.strokeStyle/);assert.match(ui,/mode==='countdown'/);assert.match(ui,/Weekly Menu/);assert.doesNotMatch(ui,/Morning','Noon','Evening','Night/);assert.doesNotMatch(ui,/generic bullet/)})
test('audit contains all 32 combinations',async()=>{const audit=await readFile(new URL('docs/frame-studio-module-parity.md',root),'utf8');assert.equal((audit.match(/\| PARITY \(/g)||[]).length,32)})
