import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {chooseNearestEdge,createHistory,detectOrientation,finalizeStroke,hasOverlap,initialLayout,internalDividerSegments,previewStroke,pushHistory,redoHistory,snapBoundary,undoHistory,validateLayout} from '../app/lib/frameLayoutEditor.mjs'
const viewport={width:400,height:400}
const stroke=(x1,y1,x2,y2)=>({start:{x:x1,y:y1},end:{x:x2,y:y2}})
const split=(cells,s)=>previewStroke(cells,s,viewport)
const geometry=cells=>cells.map(({col,row,colSpan,rowSpan,moduleId})=>({col,row,colSpan,rowSpan,moduleId}))
const assertPartition=cells=>{assert.equal(validateLayout(cells),true);assert.equal(cells.reduce((n,c)=>n+c.colSpan*c.rowSpan,0),16);for(let i=0;i<cells.length;i++)for(let j=i+1;j<cells.length;j++)assert.equal(hasOverlap(cells[i],cells[j]),false);for(let row=0;row<4;row++)for(let col=0;col<4;col++)assert.equal(cells.filter(c=>col>=c.col&&col<c.col+c.colSpan&&row>=c.row&&row<c.row+c.rowSpan).length,1)}
test('detects vertical and horizontal intent',()=>{assert.equal(detectOrientation(stroke(30,10,35,300)),'vertical');assert.equal(detectOrientation(stroke(10,30,300,35)),'horizontal')})
test('snaps representative pixels to every 4x4 boundary',()=>{assert.deepEqual([0,49,51,99,101,149,151,199,201,249,251,299,301,349,351,399,400].map(v=>snapBoundary(v,400)),[0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4]);assert.deepEqual([0,100,200,300,400].map(v=>snapBoundary(v,400)),[0,1,2,3,4])})
test('nearest edge selection and ties are deterministic',()=>{const c=initialLayout()[0];assert.equal(chooseNearestEdge(c,'vertical',1),'left');assert.equal(chooseNearestEdge(c,'vertical',3),'right');assert.equal(chooseNearestEdge(c,'vertical',2),'left');assert.equal(chooseNearestEdge(c,'horizontal',1),'top');assert.equal(chooseNearestEdge(c,'horizontal',3),'bottom');assert.equal(chooseNearestEdge(c,'horizontal',2),'top')})
test('top-left single line creates the specified three rectangles',()=>{const p=split(initialLayout(),stroke(100,0,104,200));assert.equal(p.valid,true);assert.deepEqual(geometry(p.cells),[{col:0,row:0,colSpan:1,rowSpan:2,moduleId:'empty'},{col:1,row:0,colSpan:3,rowSpan:4,moduleId:'empty'},{col:0,row:2,colSpan:1,rowSpan:2,moduleId:'empty'}]);assertPartition(p.cells)})
test('mirrored corner gestures produce rectangular normalized partitions',()=>{for(const s of [stroke(300,0,296,200),stroke(100,200,104,400),stroke(300,200,296,400),stroke(0,100,200,104),stroke(200,300,400,296)]){const p=split(initialLayout(),s);assert.equal(p.valid,true);assert.equal(p.cells.length,3);assertPartition(p.cells)}})
test('repeated splits remain in bounds, gapless and non-overlapping',()=>{let cells=split(initialLayout(),stroke(100,0,102,200)).cells;const target=cells.find(c=>c.col===1);const p=split(cells,stroke(210,100,390,104));assert.equal(p.valid,true);cells=p.cells;assert.ok(target);assertPartition(cells);assert.ok(cells.every(c=>c.col+c.colSpan<=4&&c.row+c.rowSpan<=4))})

test('internal dividers exclude the viewport edge, merge adjacency, and preserve a T junction',()=>{const cells=[{id:'a',col:0,row:0,colSpan:1,rowSpan:2,moduleId:'empty'},{id:'b',col:0,row:2,colSpan:1,rowSpan:2,moduleId:'empty'},{id:'c',col:1,row:0,colSpan:3,rowSpan:4,moduleId:'empty'}];const segments=internalDividerSegments(cells);assert.deepEqual(segments,[{axis:'vertical',boundary:1,from:0,to:4},{axis:'horizontal',boundary:2,from:0,to:1}]);assert.equal(new Set(segments.map(x=>JSON.stringify(x))).size,segments.length);assert.ok(segments.every(x=>x.boundary>0&&x.boundary<4))})
test('contiguous unit dividers merge into one unique segment',()=>{const cells=[{id:'left',col:0,row:0,colSpan:2,rowSpan:4,moduleId:'empty'},{id:'r1',col:2,row:0,colSpan:2,rowSpan:1,moduleId:'empty'},{id:'r2',col:2,row:1,colSpan:2,rowSpan:3,moduleId:'empty'}];assert.deepEqual(internalDividerSegments(cells),[{axis:'vertical',boundary:2,from:0,to:4},{axis:'horizontal',boundary:1,from:2,to:4}])})
test('pointer-up finalization uses the release endpoint rather than stale move preview',()=>{const cells=initialLayout(),move=previewStroke(cells,stroke(100,0,100,100),viewport),release=finalizeStroke(cells,{x:100,y:0},{x:100,y:200},viewport);assert.notDeepEqual(geometry(move.cells),geometry(release.cells));assert.deepEqual(geometry(release.cells),geometry(split(cells,stroke(100,0,100,200)).cells))})
test('invalid and no-op gestures retain the same layout reference',()=>{const cells=initialLayout();for(const s of [stroke(10,10,12,12),stroke(-1,20,200,20),stroke(0,0,0,300),stroke(100,10,100,20)]){const p=split(cells,s);assert.equal(p.valid,false);assert.equal(p.cells,cells)}})
test('undo and redo restore exact immutable states',()=>{const before=initialLayout(),after=split(before,stroke(100,0,100,200)).cells;const pushed=pushHistory(createHistory(before),after),undone=undoHistory(pushed),redone=redoHistory(undone);assert.deepEqual(undone.present,before);assert.deepEqual(redone.present,after);assert.deepEqual(before,initialLayout())})
test('assignment follows largest result and top-left wins an area tie',()=>{const assigned=[{...initialLayout()[0],moduleId:'weather'}];let p=split(assigned,stroke(100,0,100,200));assert.equal(p.cells.find(c=>c.moduleId==='weather').col,1);const half=[{id:'half',col:0,row:0,colSpan:2,rowSpan:4,moduleId:'date'},{id:'right',col:2,row:0,colSpan:2,rowSpan:4,moduleId:'empty'}];p=split(half,stroke(0,200,200,200));const keeper=p.cells.find(c=>c.moduleId==='date');assert.deepEqual({col:keeper.col,row:keeper.row},{col:0,row:0})})
test('registry mirrors every firmware dispatch and drives the picker',async()=>{const registry=JSON.parse(await readFile(new URL('../shared/frame-modules.json',import.meta.url),'utf8')),renderer=await readFile(new URL('../frame/src/modules/ModuleRenderer.cpp',import.meta.url),'utf8'),simulator=await readFile(new URL('../app/frame-simulator/FrameSimulator.tsx',import.meta.url),'utf8');const expected=['date','weather','surf','reminders','countdown','soccer','stocks','groceries'];assert.deepEqual(registry.map(x=>x.id),expected);for(const id of expected)assert.match(renderer,new RegExp(`(?:equalsIgnoreCase|startsWith)\\(\"${id}`));assert.match(simulator,/frameModuleRegistry\.map/);assert.doesNotMatch(simulator,/const modules\s*=/);assert.doesNotMatch(simulator,/committed\.forEach\(c=>ctx\.strokeRect/);assert.match(simulator,/ox\.strokeRect/);for(const id of expected)assert.match(simulator,new RegExp(`${id}`))})
