import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
const root=new URL('../',import.meta.url)
const spec=JSON.parse(await readFile(new URL('shared/frame-layouts.json',root),'utf8'))
const gx=n=>spec.viewport.x+Math.trunc(spec.viewport.width*n/spec.gridSize)
const gy=n=>spec.viewport.y+Math.trunc(spec.viewport.height*n/spec.gridSize)
const resolve=c=>({x:gx(c.col),y:gy(c.row),w:gx(c.col+c.colSpan)-gx(c.col),h:gy(c.row+c.rowSpan)-gy(c.row),slot:c.slot,size:c.size})
test('physical panel and locked viewport do not drift',()=>{assert.deepEqual(spec.panel,{width:800,height:480});assert.deepEqual(spec.viewport,{x:9,y:22,width:785,height:458})})
test('boundary multiplication before division reaches every exact edge without drift',()=>{assert.deepEqual([0,1,2,3,4].map(gx),[9,205,401,597,794]);assert.deepEqual([0,1,2,3,4].map(gy),[22,136,251,365,480]);assert.equal(gx(4),794);assert.equal(gy(4),480)})
test('legacy cells are pixel-identical',()=>{const expected={full:[[9,22,785,458,0,'XL']],default:[[9,22,785,114,0,'SMALL'],[9,136,785,115,1,'SMALL'],[9,251,785,229,2,'LARGE']],pyramid:[[9,22,785,114,0,'SMALL'],[9,136,785,115,1,'SMALL'],[9,251,392,229,2,'MEDIUM'],[401,251,393,229,3,'MEDIUM']],square:[[9,22,392,229,0,'MEDIUM'],[401,22,393,229,1,'MEDIUM'],[9,251,392,229,2,'MEDIUM'],[401,251,393,229,3,'MEDIUM']]};for(const [name,cells] of Object.entries(spec.layouts))assert.deepEqual(cells.map(c=>{const p=resolve(c);return[p.x,p.y,p.w,p.h,p.slot,p.size]}),expected[name])})
test('all declared cells are valid and remain inside viewport',()=>{for(const cells of Object.values(spec.layouts))for(const c of cells){assert.ok(c.col>=0&&c.row>=0&&c.colSpan>=1&&c.rowSpan>=1&&c.col+c.colSpan<=4&&c.row+c.rowSpan<=4);const p=resolve(c);assert.ok(p.x>=9&&p.y>=22&&p.x+p.w<=794&&p.y+p.h<=480)}})
test('divider boundaries preserve legacy coordinates',()=>{assert.equal(gy(1),136);assert.equal(gy(2),251);assert.equal(gx(2),401);assert.equal(Math.trunc(785*.025),19);assert.equal(Math.trunc(458*.025),11)})
test('invalid spans are rejected by the shared conversion contract',()=>{const valid=c=>c.col>=0&&c.row>=0&&c.col<4&&c.row<4&&c.colSpan>=1&&c.rowSpan>=1&&c.col+c.colSpan<=4&&c.row+c.rowSpan<=4;for(const c of [{col:0,row:0,colSpan:0,rowSpan:1},{col:3,row:0,colSpan:2,rowSpan:1},{col:0,row:3,colSpan:1,rowSpan:2}])assert.equal(valid(c),false)})
test('simulator consumes shared definitions and a real 800x480 canvas without network calls',async()=>{const [lib,ui]=await Promise.all([readFile(new URL('app/lib/frameSimulator.ts',root),'utf8'),readFile(new URL('app/frame-simulator/FrameSimulator.tsx',root),'utf8')]);assert.match(lib,/frame-layouts\.json/);assert.match(lib,/resolveGridCell/);assert.match(ui,/width="800" height="480"/);assert.doesNotMatch(ui,/fetch\(|axios|XMLHttpRequest/)})
test('unsupported test geometries are explicit and module profiles cover core modules',async()=>{const profiles=JSON.parse(await readFile(new URL('shared/module-layout-profiles.json',root),'utf8'));assert.deepEqual(Object.keys(profiles),['date','reminders','weather','countdown']);const lib=await readFile(new URL('app/lib/frameSimulator.ts',root),'utf8');const ui=await readFile(new URL('app/frame-simulator/FrameSimulator.tsx',root),'utf8');assert.match(lib,/isSupported/);assert.match(ui,/UNSUPPORTED — NEEDS NEW VARIANT/)})
