import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {responsiveCellProfile,studioRenderStrategy} from '../app/lib/responsiveCellProfile.mjs'
import {fitGroceriesText,fitGroceryText,fitMealIdeaText,fitRunningLowText,formatGroceryItem,groceriesComposition,groceriesFutureDinners,groceriesLayout,groceriesStudioPresets,groceriesTodayDinner,selectGroceryItems} from '../app/lib/groceriesResponsive.mjs'

test('Groceries keeps four handmade anchors and routes twelve adaptive geometries',()=>{const anchors=new Map([['4x1','SMALL'],['2x2','MEDIUM'],['4x2','LARGE'],['4x4','XL']]);let adaptive=0;for(let c=1;c<=4;c++)for(let r=1;r<=4;r++){const strategy=studioRenderStrategy('groceries',c,r,c*196,r*114),anchor=anchors.get(`${c}x${r}`);if(anchor){assert.equal(strategy.path,'legacy');assert.equal(strategy.legacyVariant,anchor)}else{assert.equal(strategy.path,'groceries-responsive');adaptive++}}assert.equal(adaptive,12)})

test('presets have structured deterministic facts and exact quantities',()=>{assert.deepEqual(Object.keys(groceriesStudioPresets),['normal','long','extreme','empty']);for(const state of Object.values(groceriesStudioPresets)){assert.equal(state.todayDate,'2026-08-21');assert.ok(state.items.every(value=>typeof value.name==='string'&&Number.isFinite(value.quantity)));assert.ok(state.dinners.every(value=>/^2026-08-\d\d$/.test(value.date)&&value.dayLabel&&value.title))}assert.equal(formatGroceryItem({name:'Milk',quantity:1}),'Milk');assert.equal(formatGroceryItem({name:'Milk',quantity:2}),'2x Milk');assert.equal(formatGroceryItem({name:'Oil',quantity:12}),'12x Oil')})

test('measured ellipsis preserves the complete quantity prefix',()=>{const fit=fitGroceryText({name:'Extra virgin olive oil',quantity:12},90,(text,size)=>text.length*size*.5,{fontSize:12});assert.equal(fit.quantity,'12x');assert.match(fit.text,/^12x /);assert.match(fit.name,/…$/);assert.equal(fitGroceryText({name:'Milk',quantity:12},10,(text,size)=>text.length*size*.5,{fontSize:12}),null)})

test('long headings expose the exact shortened string used for their measured underline',()=>{const measure=text=>text.length*10,source='Slow-cooked chicken tikka masala',rendered=fitGroceriesText(source,150,measure);assert.equal(rendered.truncated,true);assert.notEqual(rendered.text,source);assert.ok(measure(rendered.text)<=150);assert.ok(measure(source)>150)})

test('Running Low preserves item identity before its optional explanatory label',()=>{const measure=text=>text.length*10,item={name:'Coffee beans',label:'Likely to run out before next shop'},full=fitRunningLowText(item,600,measure),withoutLabel=fitRunningLowText(item,130,measure),short=fitRunningLowText(item,70,measure);assert.equal(full.labelShown,true);assert.equal(full.text,'Coffee beans — Likely to run out before next shop');assert.deepEqual(withoutLabel,{text:'Coffee beans',labelShown:false,nameTruncated:false});assert.equal(short.labelShown,false);assert.match(short.text,/^Coffee…$/)})

test('Meal Ideas progressively discloses only whole missing ingredient tokens',()=>{const measure=text=>text.length*10,idea={name:'Curry',missing:['salsa','coconut milk']},two=fitMealIdeaText(idea,400,measure),one=fitMealIdeaText(idea,250,measure),none=fitMealIdeaText(idea,100,measure),title=fitMealIdeaText({name:'Exceptionally long curry recipe',missing:['coconut milk']},80,measure);assert.equal(two.text,'Curry · missing: salsa, coconut milk');assert.equal(two.missingShown,2);assert.equal(one.text,'Curry · missing: salsa');assert.equal(one.missingShown,1);assert.deepEqual(none,{text:'Curry',missingShown:0,titleTruncated:false});assert.equal(title.missingShown,0);assert.equal(title.titleTruncated,true);assert.match(title.text,/…$/);for(const result of [two,one,none,title])assert.doesNotMatch(result.text,/coconut m…/)})

test('today and future meals use todayDate, exclude past/today, and sort ascending',()=>{const state={...groceriesStudioPresets.normal,dinners:[{date:'2026-08-24',dayLabel:'Mon',title:'Soup'},{date:'2026-08-20',dayLabel:'Thu',title:'Past'},{date:'2026-08-21',dayLabel:'Fri',title:'Today'},{date:'2026-08-22',dayLabel:'Sat',title:'Pasta'}]};assert.equal(groceriesTodayDinner(state).title,'Today');assert.deepEqual(groceriesFutureDinners(state).map(value=>value.title),['Pasta','Soup']);assert.ok(groceriesFutureDinners(state).every(value=>value.date>state.todayDate))})

test('rotation is deterministic and selection never duplicates or manufactures items',()=>{const state={...groceriesStudioPresets.normal,rotationOffset:4};assert.deepEqual(selectGroceryItems(state,4).map(value=>value.name),['Rice','Soap','Milk','Bread']);const selected=selectGroceryItems(state,99);assert.equal(selected.length,state.items.length);assert.equal(new Set(selected).size,selected.length)})

test('all presets and geometries allocate bounded content-sized groups',()=>{const contains=(a,b)=>b.x>=a.x-.01&&b.y>=a.y-.01&&b.x+b.width<=a.x+a.width+.01&&b.y+b.height<=a.y+a.height+.01,overlaps=(a,b)=>a.x<b.x+b.width&&b.x<a.x+a.width&&a.y<b.y+b.height&&b.y<a.y+a.height;for(const state of Object.values(groceriesStudioPresets))for(let c=1;c<=4;c++)for(let r=1;r<=4;r++){const p=responsiveCellProfile(c,r,c*196,r*114),co=groceriesComposition(p,state),l=groceriesLayout(p,co,state),cell={x:0,y:0,width:p.width,height:p.height};for(const value of [l.emptyRect,l.headerRect,l.todayLabelRect,l.titleRect,l.groceryRect,l.overflowRect,l.menuRect,l.menuHeaderRect,l.runningLowRect,l.mealIdeasRect,...l.groceryRows.map(v=>v.itemRect),...l.groceryRows.map(v=>v.quantityRect),...l.groceryRows.map(v=>v.nameRect),...l.menuRows.map(v=>v.rect),...l.runningLowRows.map(v=>v.rect),...l.mealIdeaGroups.map(v=>v.rect)].filter(Boolean))assert.ok(contains(cell,value),`${c}x${r} ${co.family} escaped cell`);for(const row of l.groceryRows)assert.ok(contains(l.groceryRect,row.itemRect));for(const row of l.menuRows)assert.ok(contains(l.menuRect,row.rect));for(const row of l.runningLowRows)assert.ok(contains(l.runningLowRect,row.rect));for(const row of l.mealIdeaGroups)assert.ok(contains(l.mealIdeasRect,row.rect));const panels=[l.groceryRect,l.menuRect,l.runningLowRect,l.mealIdeasRect].filter(Boolean);for(let i=0;i<panels.length;i++)for(let j=i+1;j<panels.length;j++)assert.equal(overlaps(panels[i],panels[j]),false)}})

test('space drives visible rows, honest overflow, and menu usability',()=>{const state=groceriesStudioPresets.extreme,tinyP=responsiveCellProfile(1,1,196,114),tinyC=groceriesComposition(tinyP,state),tiny=groceriesLayout(tinyP,tinyC,state),tallP=responsiveCellProfile(1,4,196,456),tall=groceriesLayout(tallP,groceriesComposition(tallP,state),state);assert.ok(tiny.groceryRows.length<=2);assert.ok(tall.groceryRows.length>tiny.groceryRows.length);assert.equal(Number(tiny.overflowRect!==null),Number(state.items.length>tiny.groceryRows.length));assert.equal(tinyC.showMenu,false);for(const dims of [[196,456],[392,342]])assert.equal(groceriesComposition(responsiveCellProfile(1,3,...dims),state).showMenu,false);const wide=groceriesComposition(responsiveCellProfile(3,2,588,228),state);assert.equal(wide.showMenu,true);const layout=groceriesLayout(responsiveCellProfile(3,2,588,228),wide,state);assert.ok(layout.menuRows.length>=2);assert.ok(layout.groceryRect.width>layout.menuRect.width)})

test('insights disclose progressively with firmware caps and priority',()=>{const medium=groceriesComposition(responsiveCellProfile(3,2,588,228),groceriesStudioPresets.normal);assert.equal(medium.showRunningLow,false);assert.equal(medium.showMealIdeas,false);const pressured=groceriesComposition(responsiveCellProfile(4,3,784,342),groceriesStudioPresets.extreme);assert.equal(pressured.showRunningLow,true);assert.equal(pressured.showMealIdeas,false);const expandedP=responsiveCellProfile(3,4,588,456),expanded=groceriesComposition(expandedP,groceriesStudioPresets.extreme),layout=groceriesLayout(expandedP,expanded,groceriesStudioPresets.extreme);assert.equal(expanded.showMealIdeas,true);assert.ok(layout.runningLowRows.length<=3);assert.ok(layout.mealIdeaGroups.length<=2);assert.deepEqual(layout.mealIdeaGroups[0].idea.missing,['fresh coriander','smoked paprika','avocado']);const mealOnly={...groceriesStudioPresets.empty,items:[{name:'Milk',quantity:1}],mealIdeas:[{name:'Tacos',missing:['salsa']}]},mealComposition=groceriesComposition(expandedP,mealOnly);assert.equal(mealComposition.showRunningLow,false);assert.equal(mealComposition.showMealIdeas,true);assert.ok(groceriesLayout(expandedP,mealComposition,mealOnly).mealIdeasRect)})

test('semantic states distinguish valid empty, failed, and partial content',()=>{const base=groceriesStudioPresets.empty,states=[{...base,items:[{name:'Milk',quantity:1}]},{...base,items:[{name:'Milk',quantity:1}],dinners:[{date:base.todayDate,dayLabel:'Fri',title:'Tacos'}]},{...base,dinners:[{date:'2026-08-22',dayLabel:'Sat',title:'Pasta'},{date:'2026-08-23',dayLabel:'Sun',title:'Curry'}]},{...base,dinners:[{date:base.todayDate,dayLabel:'Fri',title:'Tacos'},{date:'2026-08-22',dayLabel:'Sat',title:'Pasta'},{date:'2026-08-23',dayLabel:'Sun',title:'Curry'}]},{...base,runningLow:[{name:'Coffee',label:'Low soon'}]},{...base,mealIdeas:[{name:'Tacos',missing:['salsa']}]},base,{...base,status:'failed'}];const p=responsiveCellProfile(3,4,588,456);states.forEach(state=>assert.doesNotThrow(()=>groceriesLayout(p,groceriesComposition(p,state),state)));assert.equal(groceriesComposition(p,base).family,'empty');assert.equal(groceriesComposition(p,{...base,status:'failed'}).failed,true);assert.equal(groceriesComposition(p,states[2]).family,'expanded')})

test('runtime/declaration parity and renderer use measurement without AI, network, or wall clock',async()=>{const runtime=await readFile(new URL('../app/lib/groceriesResponsive.mjs',import.meta.url),'utf8'),declarations=await readFile(new URL('../app/lib/groceriesResponsive.d.mts',import.meta.url),'utf8'),studio=await readFile(new URL('../app/frame-simulator/FrameSimulator.tsx',import.meta.url),'utf8'),renderer=studio.slice(studio.indexOf('function drawResponsiveGroceries'),studio.indexOf('function groceryHeader'));for(const name of [...runtime.matchAll(/export (?:const|function) (\w+)/g)].map(value=>value[1]))assert.match(declarations,new RegExp(`export (?:const|function) ${name}\\b`));assert.doesNotMatch(runtime+renderer,/fetch\(|Date\(|Date\.now|setInterval|setTimeout|\bAI\b|axios/);assert.match(renderer,/measureText/);assert.match(renderer,/fitGroceryText/);assert.match(renderer,/fitRunningLowText/);assert.match(renderer,/fitMealIdeaText/);assert.match(renderer,/rendered=fitGroceriesText\(text,rect\.width[^]*drawText\(rendered\.text[^]*ctx\.measureText\(rendered\.text\)\.width/)})
