import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync, mkdtempSync, writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {execFileSync} from 'node:child_process'
import registry from '../shared/frame-modules.json' with {type:'json'}
import {aiFollowComposition} from '../app/lib/aiFollowResponsive.mjs'
import {responsiveCellProfile,studioRenderStrategy} from '../app/lib/responsiveCellProfile.mjs'
import {supportsPhysicalCustomCell,supportsPhysicalCustomLayout} from '../app/lib/customLayouts.mjs'

const read=p=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8')
const renderer=read('frame/src/modules/ModuleRenderer.cpp'), capability=read('frame/src/modules/AdaptiveModuleCapability.h')
const assistant=read('frame/src/modules/ModuleAssistant.cpp'), endpoint=read('app/api/device/assistant/route.ts'), data=read('app/lib/device/aiAssistantDeviceData.ts')

test('assistant is the sole physical AI Follow identity and Studio identity',()=>{assert.deepEqual(registry.filter(x=>x.label==='AI Follow'),[{id:'assistant',label:'AI Follow'}]);assert.equal(registry.some(x=>x.id==='ai-follow'),false);for(let c=1;c<=4;c++)for(let r=1;r<=4;r++)assert.equal(studioRenderStrategy('assistant',c,r,c*196,r*114).path,'ai-follow-responsive');assert.throws(()=>studioRenderStrategy('ai-follow',1,1,196,114))})
test('exact physical capability accepts assistant in every valid rectangle only',()=>{for(let c=1;c<=4;c++)for(let r=1;r<=4;r++)assert.equal(supportsPhysicalCustomCell({colSpan:c,rowSpan:r,module:'assistant'}),true);for(const module of ['assistant:1','assistantfoo','assistant:','ai-follow','assist ant'])assert.equal(supportsPhysicalCustomCell({colSpan:1,rowSpan:1,module}),false);assert.match(capability,/exactOnly\(module, "assistant"\)/)})
test('custom layout preflight remains atomic',()=>{const cells=[];for(let row=0;row<4;row++)for(let col=0;col<4;col++)cells.push({slot:row*4+col,col,row,colSpan:1,rowSpan:1,module:'assistant'});assert.equal(supportsPhysicalCustomLayout(cells).valid,true);cells[7].module='assistant:1';const result=supportsPhysicalCustomLayout(cells);assert.equal(result.valid,false);assert.deepEqual(result.unsupportedSlots,[7])})
test('all cell sizes dispatch to one exact-pixel renderer without legacy variants',()=>{assert.match(renderer,/exactOnly\(mod\.c_str\(\), "assistant"\)[\s\S]*ModuleAssistant::render\(c\)/);assert.doesNotMatch(assistant,/render(?:Small|Medium|Large|XL)/);assert.match(assistant,/compose\(\{c\.w,c\.h/);for(const size of ['CELL_SMALL','CELL_MEDIUM','CELL_LARGE','CELL_XL','CELL_ADAPTIVE'])assert.doesNotMatch(assistant,new RegExp(`case ${size}`))})
test('composition modes, families, capacities, and boundary pixels remain Studio-defined',()=>{const state=n=>({followingCount:2,updates:Array.from({length:n},(_,i)=>({id:String(i),watchId:String(i),topicTitle:'T',summary:'S',createdAt:new Date(2e12-i*1000).toISOString()}))});assert.equal(aiFollowComposition({width:200,height:120},state(0)).mode,'no-change');assert.equal(aiFollowComposition({width:200,height:120},{followingCount:0,updates:[]}).mode,'zero-follow');for(const [w,h,family] of [[239,134,'micro'],[240,134,'shallow'],[200,135,'shallow'],[300,164,'shallow'],[300,165,'single'],[300,244,'single'],[359,390,'list'],[360,389,'list'],[360,390,'expanded']])assert.equal(aiFollowComposition({width:w,height:h},state(6)).family,family);assert.match(assistant,/visibleCapacity/);assert.match(assistant,/policy\.summaryLines/)})
test('firmware mirrors Studio header, quiet, update, and overflow geometry',()=>{assert.match(assistant,/const Rect header=\{c\.x\+pad,c\.y\+pad,c\.w-pad\*2,30\}/);assert.match(assistant,/"AI FOLLOW"[\s\S]*ALIGN_CENTER/);assert.match(assistant,/if\(c\.h>=135\)[\s\S]*header\.y\+21/);assert.match(assistant,/horizontal=secondary&&c\.h<155/);assert.match(assistant,/blockH=24\+\(secondary&&!horizontal\?32:0\)/);assert.match(assistant,/start\+36[\s\S]*ALIGN_CENTER/);assert.match(assistant,/const int top=header\.y\+header\.h\+8,rowH=18\+policy\.summaryLines\*16\+3,gap=8/);assert.match(assistant,/const Rect overflow=\{c\.x\+pad,top\+rowsHeight\+5,c\.w-pad\*2,18\}/);assert.match(assistant,/overflow\.w<75\?"\+%u":"\+%u more"/);assert.match(assistant,/drawInRect\(overflow,more[^;]+ALIGN_RIGHT\)/)})
test('display language comes from frame settings and never from Watch content language',()=>{assert.match(endpoint,/from\('device_settings'\)\.select\('settings_json'\)/);assert.match(endpoint,/settings\.language === 'no' \? 'no' : 'en'/);assert.doesNotMatch(endpoint,/activeWatches\.some[\s\S]*preferred_language/);assert.match(data,/preferred_language/)})
test('production selector remains current-per-watch, unread, dismissed, fresh, deterministic and member-filtered',()=>{for(const token of ['newestByWatch','memberUserIds','is_read !== true','dismissed_from_frame !== true','24 * 60 * 60 * 1000','sort((a, b) => candidateTimestamp(b)'])assert.match(read('app/lib/device/aiAssistantFrame.ts'),new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(data,/selectAiAssistantFrameItems/);assert.match(data,/monitoring_watches!inner\(owner_user_id/)})
test('authenticated compact endpoint reuses persisted data and server sanitization only',()=>{assert.match(endpoint,/device\.device_token !== token/);assert.match(endpoint,/loadAiAssistantDeviceData/);assert.doesNotMatch(endpoint,/openai|optimizeFrameContent|fetch\(|generate/i);assert.match(data,/sanitizeAiAssistantMirrorSummary/);for(const key of ['active_watch_count','update_count','updates','overflow_count'])assert.match(endpoint,new RegExp(key));assert.doesNotMatch(endpoint,/source_urls|raw_result|watch_prompt|original_request/)})
test('firmware fetch and render are bounded, filtered and fail-soft',()=>{assert.match(assistant,/MAX_UPDATES = 6/);assert.match(assistant,/sizeof\(AssistantCache\) == 1542/);assert.match(assistant,/MAX_RESPONSE_BYTES = 6144/);assert.match(assistant,/DynamicJsonDocument doc\(4096\)/);assert.match(assistant,/DeserializationOption::Filter/);assert.match(assistant,/httpGetAuth/);assert.doesNotMatch(assistant,/Serial\.(?:print|println)\(body/);assert.doesNotMatch(assistant,/static AssistantCache g_cache\s*=/);assert.equal((assistant.match(/static AssistantCache\* g_cache/g)||[]).length,1);assert.equal((assistant.match(/new \(std::nothrow\) AssistantCache\{\}/g)||[]).length,1);assert.match(assistant,/if \(g_cacheAllocationAttempted\) return false/);assert.match(assistant,/if\(!cacheAvailable\|\|!g_cache->ok\)/);assert.doesNotMatch(assistant.slice(assistant.indexOf('void render(')),/\bString\b|malloc|calloc/)})
test('Arduino-independent policy compiles as strict GNU C++11',()=>{const dir=mkdtempSync(join(tmpdir(),'e9-policy-'));const source=join(dir,'main.cpp');writeFileSync(source,'#include "AiFollowAdaptivePolicy.h"\nint main(){AiFollowAdaptivePolicy::Input i={360,390,2,8};return AiFollowAdaptivePolicy::compose(i).visibleCapacity==0;}\n');execFileSync('g++',['-std=gnu++11','-Wall','-Wextra','-Werror','-I',join(process.cwd(),'frame/src/modules'),source,'-o',join(dir,'policy')])})
