import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {responsiveCellProfile,studioRenderStrategy} from '../app/lib/responsiveCellProfile.mjs'
import {fitSoccerFact,soccerComposition,soccerFixtureTeamLabels,soccerLayout,soccerStudioPresets,soccerTableWindow,soccerTeamAbbreviation} from '../app/lib/soccerResponsive.mjs'

test('Soccer locks four anchors and routes exactly 12 adaptive geometries',()=>{const locked=new Map([['4x1','SMALL'],['2x2','MEDIUM'],['4x2','LARGE'],['4x4','XL']]);let adaptive=0;for(let c=1;c<=4;c++)for(let r=1;r<=4;r++){const strategy=studioRenderStrategy('soccer',c,r,c*196,r*114),anchor=locked.get(`${c}x${r}`);if(anchor){assert.equal(strategy.path,'legacy');assert.equal(strategy.legacyVariant,anchor)}else{assert.equal(strategy.path,'soccer-responsive');adaptive++}}assert.equal(adaptive,12)})

test('firmware abbreviations and alpha fallback are deterministic',()=>{assert.deepEqual(['Arsenal','Liverpool','Manchester United','Manchester City','Wolves'].map(soccerTeamAbbreviation),['ARS','LIV','MUN','MCI','WOL']);assert.equal(soccerTeamAbbreviation('Borussia Mönchengladbach'),'BOR');assert.equal(soccerTeamAbbreviation('Paris Saint-Germain'),'PAR')})

test('structured presets compose with every internal rect contained by its parent and physical cell',()=>{const epsilon=.01,contains=(parent,child)=>child.x>=parent.x-epsilon&&child.y>=parent.y-epsilon&&child.x+child.width<=parent.x+parent.width+epsilon&&child.y+child.height<=parent.y+parent.height+epsilon,cell=p=>({x:0,y:0,width:p.width,height:p.height}),overlap=(a,b)=>a.x<b.x+b.width&&b.x<a.x+a.width&&a.y<b.y+b.height&&b.y<a.y+a.height;assert.deepEqual(Object.keys(soccerStudioPresets),['normal','long','extreme','empty']);for(const [name,state] of Object.entries(soccerStudioPresets))for(let c=1;c<=4;c++)for(let r=1;r<=4;r++){const p=responsiveCellProfile(c,r,c*196,r*114),co=soccerComposition(p,state),layout=soccerLayout(p,co),physical=cell(p);assert.equal(co.available,name!=='empty');const regions=[layout.emptyRect,layout.primaryRect,layout.primaryGroupRect,layout.kickoffRect,layout.teamsRect,layout.standingRect,layout.previousRect,layout.previousGroupRect,layout.standingsRect,layout.detailsRect,layout.detailsGroupRect,...layout.detailRowRects,...layout.rowRects].filter(Boolean);for(const x of regions)assert.ok(contains(physical,x),`${name} ${c}x${r} rect escaped the cell`);for(const x of [layout.primaryGroupRect,layout.kickoffRect,layout.teamsRect,layout.standingRect].filter(Boolean))assert.ok(contains(layout.primaryRect,x),`${name} ${c}x${r} primary child escaped`);if(layout.previousGroupRect)assert.ok(contains(layout.previousRect,layout.previousGroupRect));if(layout.detailsGroupRect)assert.ok(contains(layout.detailsRect,layout.detailsGroupRect));for(const row of layout.detailRowRects)assert.ok(contains(layout.detailsGroupRect,row));for(const row of layout.rowRects)assert.ok(contains(layout.standingsRect,row),`${name} ${c}x${r} standings row escaped`);const siblingPrevious=layout.previousRect&&!contains(layout.primaryRect,layout.previousRect)?layout.previousRect:null,topRegions=[layout.primaryRect,siblingPrevious,layout.standingsRect,layout.detailsRect].filter(Boolean);for(let i=0;i<topRegions.length;i++)for(let j=i+1;j<topRegions.length;j++)assert.equal(overlap(topRegions[i],topRegions[j]),false)}})

test('2x4 expanded aligns a compact details group with the primary group above unchanged standings',()=>{const p=responsiveCellProfile(2,4,392,456),co=soccerComposition(p,soccerStudioPresets.normal),layout=soccerLayout(p,co),center=r=>r.y+r.height/2;assert.equal(co.family,'expanded');assert.equal(layout.detailRowRects.length,4);assert.ok(layout.detailsGroupRect.height<layout.detailsRect.height);for(const row of layout.detailRowRects)assert.ok(row.y>=layout.detailsGroupRect.y&&row.y+row.height<=layout.detailsGroupRect.y+layout.detailsGroupRect.height);assert.ok(Math.abs(center(layout.detailsGroupRect)-center(layout.primaryGroupRect))<=1);assert.deepEqual(layout.standingsRect,{x:13.72,y:269,width:364.56,height:173.28});assert.ok(layout.dividerX>layout.primaryRect.x+layout.primaryRect.width)} )

test('3x2 wide history uses dominant primary and compact previous siblings',()=>{for(const state of [soccerStudioPresets.normal,soccerStudioPresets.long]){const p=responsiveCellProfile(3,2,588,228),co=soccerComposition(p,state),layout=soccerLayout(p,co);assert.equal(co.family,'fixture-history');assert.equal(co.showPrevious,true);assert.ok(layout.primaryRect.width>layout.previousRect.width);assert.ok(layout.primaryRect.x+layout.primaryRect.width<layout.previousRect.x);assert.ok(layout.previousGroupRect.height<layout.previousRect.height);assert.ok(layout.previousGroupRect.height>=67);assert.ok(layout.dividerX>layout.primaryRect.x+layout.primaryRect.width);const labels=soccerFixtureTeamLabels(state.previousFixture,layout.previousGroupRect.width-8,(text,size)=>text.length*size,13);assert.equal(labels.abbreviated,true);assert.match(`${state.previousFixture.homeScore} - ${state.previousFixture.awayScore}`,/^\d+ - \d+$/)}})

test('wide-history disclosure does not leak into narrow families or alter other family decisions',()=>{const expected=new Map([['1x1','micro'],['2x1','fixture-strip'],['3x1','fixture-strip'],['1x2','fixture-stack'],['1x3','fixture-stack'],['1x4','fixture-stack'],['2x3','fixture-history'],['3x3','fixture-standings'],['3x4','fixture-standings'],['4x3','fixture-standings']]);for(const [key,family] of expected){const [c,r]=key.split('x').map(Number),co=soccerComposition(responsiveCellProfile(c,r,c*196,r*114),soccerStudioPresets.normal);assert.equal(co.family,family,key);if(['1x1','2x1','3x1','1x2'].includes(key))assert.equal(co.showPrevious,false,key)}})

test('1x1 normal micro gives fixture identity the full bounded group',()=>{const p=responsiveCellProfile(1,1,196,114),composition=soccerComposition(p,soccerStudioPresets.normal),layout=soccerLayout(p,composition),inside=(parent,child)=>child.x>=parent.x&&child.y>=parent.y&&child.x+child.width<=parent.x+parent.width&&child.y+child.height<=parent.y+parent.height;assert.equal(composition.family,'micro');assert.equal(layout.kickoffRect,null);assert.ok(layout.teamsRect);assert.ok(inside(layout.primaryRect,layout.teamsRect));assert.ok(inside({x:0,y:0,width:p.width,height:p.height},layout.teamsRect))})

test('state-specific compositions degrade without fake regions',()=>{const p=responsiveCellProfile(4,3,785,343),f={homeTeam:'Arsenal',awayTeam:'Liverpool',kickoffDay:'Sunday',kickoffTime:'16:30'},previous={homeTeam:'Arsenal',awayTeam:'Chelsea',homeScore:12,awayScore:10},rows=soccerStudioPresets.normal.table;const states=[{teamName:'Arsenal',nextFixture:f,previousFixture:previous,position:1,points:68,table:rows},{teamName:'Arsenal',nextFixture:f},{teamName:'Arsenal',previousFixture:previous},{teamName:'Arsenal',position:1,points:68,table:rows},{teamName:'Arsenal',nextFixture:f,table:rows},{teamName:'Arsenal',nextFixture:f,position:1,points:68},{teamName:null}];const c=states.map(s=>soccerComposition(p,s));assert.equal(c[0].primaryState,'next');assert.equal(c[1].showStanding,false);assert.equal(c[2].primaryState,'previous');assert.equal(c[3].primaryState,'standing');assert.equal(c[4].showStanding,false);assert.equal(c[5].showTable,false);assert.equal(c[6].available,false)})

test('measured fixture selection never produces partial names and facts are atomic',()=>{const f=soccerStudioPresets.long.nextFixture,measure=(v,s)=>v.length*s;assert.deepEqual(soccerFixtureTeamLabels(f,200,measure,10),{home:'MUN',away:'WOL',abbreviated:true});assert.equal(soccerFixtureTeamLabels(f,1000,measure,10).abbreviated,false);assert.deepEqual(fitSoccerFact('12 - 10',70,22,measure,{maxFont:16,minFont:8}),{text:'12 - 10',fontSize:10});assert.equal(fitSoccerFact('Saturday 23:59',20,22,measure,{maxFont:16,minFont:8}),null)})

test('standings disclose by physical usability and center selected row',()=>{const state=soccerStudioPresets.extreme;const narrow=soccerComposition(responsiveCellProfile(3,3,560,300),state),wide=soccerComposition(responsiveCellProfile(4,3,785,343),state);assert.equal(narrow.showTable,true);assert.deepEqual(narrow.tableColumns,['P','Team','Pts','GD']);assert.deepEqual(wide.tableColumns,['P','Team','Pts','Gap','GD']);const window=soccerTableWindow(state.table,5),selected=window.findIndex(r=>r.selected);assert.equal(window.length,5);assert.equal(selected,2);assert.ok(wide.tableRows>=3);assert.ok(wide.tableRows!==soccerComposition(responsiveCellProfile(4,3,785,500),state).tableRows)})

test('runtime declarations match and renderer has no network or ellipsis path',async()=>{const runtime=await readFile(new URL('../app/lib/soccerResponsive.mjs',import.meta.url),'utf8'),declarations=await readFile(new URL('../app/lib/soccerResponsive.d.mts',import.meta.url),'utf8');for(const name of [...runtime.matchAll(/export (?:const|function) (\w+)/g)].map(x=>x[1]))assert.match(declarations,new RegExp(`export (?:const|function) ${name}\\b`));const source=await readFile(new URL('../app/frame-simulator/FrameSimulator.tsx',import.meta.url),'utf8'),renderer=source.slice(source.indexOf('function drawResponsiveSoccer'),source.indexOf('function soccerFixture'));assert.doesNotMatch(renderer,/fetch\(|…/);assert.match(renderer,/soccerFixtureTeamLabels/);assert.match(renderer,/fitSoccerFact/)})
