import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {responsiveCellProfile,studioRenderStrategy} from '../app/lib/responsiveCellProfile.mjs'
import {fitStockFact,formatStockPrice,formatStockSigned,STOCK_CHART_MIN_HEIGHT,STOCK_CHART_MIN_WIDTH,STOCK_RANGES,stockReferenceLine,stocksComposition,stocksLayout,stocksStudioPresets} from '../app/lib/stocksResponsive.mjs'

test('Stocks keeps four anchors and routes the other twelve geometries',()=>{const anchors=new Map([['4x1','SMALL'],['2x2','MEDIUM'],['4x2','LARGE'],['4x4','XL']]);let adaptive=0;for(let c=1;c<=4;c++)for(let r=1;r<=4;r++){const strategy=studioRenderStrategy('stocks',c,r,c*196,r*114),anchor=anchors.get(`${c}x${r}`);if(anchor){assert.equal(strategy.path,'legacy');assert.equal(strategy.legacyVariant,anchor)}else{assert.equal(strategy.path,'stocks-responsive');adaptive++}}assert.equal(adaptive,12)})

test('presets are structured, deterministic, range-valid, and do not rely on purchases',()=>{assert.deepEqual(Object.keys(stocksStudioPresets),['normal','long','extreme','empty']);assert.deepEqual(STOCK_RANGES,['day','week','month','year']);for(const [name,state] of Object.entries(stocksStudioPresets)){assert.ok(STOCK_RANGES.includes(state.selectedRange));assert.equal(state.purchasePrice,null);assert.equal(state.personalChangePercent,null);assert.ok(state.series.every(Number.isFinite));if(name==='empty'){assert.equal(state.price,null);assert.deepEqual(state.series,[])}else assert.ok(state.series.length>=2)}assert.equal(stocksStudioPresets.extreme.selectedRange,'year')})

test('firmware price and signed formatting is exact and atomic fitting never ellipsizes',()=>{assert.equal(formatStockPrice(124.5),'124.50');assert.equal(formatStockPrice(512.18),'512.18');assert.equal(formatStockPrice(999999),'999999');assert.equal(formatStockPrice(null),null);assert.equal(formatStockSigned(2.9),'+2.90');assert.equal(formatStockSigned(-.42,{percent:true}),'-0.42%');assert.equal(formatStockSigned(2.4,{percent:true}),'+2.40%');const measure=(text,size)=>text.length*size;assert.deepEqual(fitStockFact('+999.99%',100,25,measure,{maxFont:18,minFont:8}),{text:'+999.99%',fontSize:12});assert.equal(fitStockFact('999999',10,20,measure,{maxFont:18,minFont:8}),null)})

test('all presets and geometries produce bounded non-overlapping allocated regions',()=>{const contains=(a,b)=>b.x>=a.x-.01&&b.y>=a.y-.01&&b.x+b.width<=a.x+a.width+.01&&b.y+b.height<=a.y+a.height+.01,overlaps=(a,b)=>a.x<b.x+b.width&&b.x<a.x+a.width&&a.y<b.y+b.height&&b.y<a.y+a.height;for(const state of Object.values(stocksStudioPresets))for(let c=1;c<=4;c++)for(let r=1;r<=4;r++){const p=responsiveCellProfile(c,r,c*196,r*114),co=stocksComposition(p,state),layout=stocksLayout(p,co),cell={x:0,y:0,width:p.width,height:p.height},regions=[layout.emptyRect,layout.titleRect,layout.summaryGroupRect,layout.priceRect,layout.dayChangeRect,layout.rangeChangeRect,layout.detailsRect,...layout.detailRowRects,layout.rangeSelectorRect,layout.chartRect].filter(Boolean);for(const region of regions)assert.ok(contains(cell,region),`${c}x${r} ${co.family} escaped`);for(const region of [layout.titleRect,layout.priceRect,layout.dayChangeRect,layout.rangeChangeRect].filter(Boolean))assert.ok(contains(layout.summaryGroupRect,region));for(const row of layout.detailRowRects)assert.ok(contains(layout.detailsRect,row));const groups=[layout.summaryGroupRect,layout.chartRect,layout.rangeSelectorRect].filter(Boolean);for(let i=0;i<groups.length;i++)for(let j=i+1;j<groups.length;j++)assert.equal(overlaps(groups[i],groups[j]),false,`${c}x${r} top groups overlap`)}})

test('chart and selector disclosure obey physical usability thresholds',()=>{for(const [c,r] of [[1,1],[2,1],[3,1],[1,2]]){const p=responsiveCellProfile(c,r,c*196,r*114),co=stocksComposition(p,stocksStudioPresets.normal),layout=stocksLayout(p,co);assert.equal(co.showChart,false);assert.equal(layout.chartRect,null);assert.equal(layout.rangeSelectorRect,null)}const p=responsiveCellProfile(3,2,588,228),co=stocksComposition(p,stocksStudioPresets.normal),layout=stocksLayout(p,co);assert.equal(co.family,'chart-summary');assert.equal(co.showChart,true);assert.ok(layout.chartRect.width>=STOCK_CHART_MIN_WIDTH);assert.ok(layout.chartRect.height>=STOCK_CHART_MIN_HEIGHT);assert.ok(['detail-chart','expanded'].includes(stocksComposition(responsiveCellProfile(4,3,785,343),stocksStudioPresets.normal).family))})

test('details progressively disclose, missing values omit, and reference line is valid-only',()=>{const large=stocksComposition(responsiveCellProfile(4,3,785,343),stocksStudioPresets.normal);assert.equal(large.showDetails,true);assert.deepEqual(large.detailKeys,['open','high','low','previousClose','change']);const partial={...stocksStudioPresets.normal,high:null,change:null};assert.deepEqual(stocksComposition(responsiveCellProfile(4,3,785,343),partial).detailKeys,['open','low','previousClose']);assert.equal(stockReferenceLine(stocksStudioPresets.normal),123.1);assert.equal(stockReferenceLine({...stocksStudioPresets.normal,baselinePrice:null}),null);assert.equal(stockReferenceLine({...stocksStudioPresets.normal,baselinePrice:999}),null)})

test('runtime/declaration parity and renderer remain deterministic without network or Max',async()=>{const runtime=await readFile(new URL('../app/lib/stocksResponsive.mjs',import.meta.url),'utf8'),declarations=await readFile(new URL('../app/lib/stocksResponsive.d.mts',import.meta.url),'utf8'),studio=await readFile(new URL('../app/frame-simulator/FrameSimulator.tsx',import.meta.url),'utf8');for(const name of [...runtime.matchAll(/export (?:const|function) (\w+)/g)].map(match=>match[1]))assert.match(declarations,new RegExp(`export (?:const|function) ${name}\\b`));const renderer=studio.slice(studio.indexOf('function drawResponsiveStocks'),studio.indexOf('function drawStocks'));assert.doesNotMatch(runtime+renderer,/fetch\(|\bMax\b/);assert.doesNotMatch(renderer,/purchasePrice|personalChangePercent/);assert.match(renderer,/fitStockFact/);assert.match(renderer,/stockReferenceLine/)})

test('each range selector item restores Canvas ink state after selected styling',async()=>{const studio=await readFile(new URL('../app/frame-simulator/FrameSimulator.tsx',import.meta.url),'utf8'),renderer=studio.slice(studio.indexOf('function drawResponsiveStocks'),studio.indexOf('function drawStocks')),selector=renderer.slice(renderer.indexOf('if(layout.rangeSelectorRect)'),renderer.indexOf('if(layout.chartRect)'));assert.match(selector,/STOCK_RANGES\.forEach\([^]*ctx\.save\(\)[^]*ctx\.fillStyle='#fff'[^]*ctx\.fillStyle='#000'[^]*centered\([^]*ctx\.restore\(\)[^]*\}\)/);assert.ok(selector.indexOf('ctx.restore()')>selector.indexOf('centered(ctx,label'),'selected and unselected labels must be drawn before the item state is restored')})
