'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import styles from './FrameSimulator.module.css'
import {
  PANEL, VIEWPORT, calendarGeometry, cellsForLayout, dividersForLayout, gridX, gridY, isoWeekNumber,
  moduleProfiles, quantizeOneBit, resolveGridCell, responsiveShowcaseRegistry, studioModuleRegistry,
  type CalendarRowMode, type GridCell, type LayoutName, type LegacyModuleName, type ModuleName, type PixelCell, type StudioModuleName,
} from '../lib/frameSimulator'
import { createHistory, finalizeDividerStroke, internalDividerSegments, previewDividerStroke, pushHistory, redoHistory, resolveDividerStrokeLock, undoHistory, type DividerHit, type DividerStrokeLock, type EditorCell, type EditorHistory, type GridSelection, type Point, type SplitGuide } from '../lib/frameLayoutEditor.mjs'
import { legacyStudioVariant, responsiveCellProfile, studioRenderStrategy, type ResponsiveCellProfile } from '../lib/responsiveCellProfile.mjs'
import { chooseReminderTextVariant, REMINDER_STUDIO_PRESET_VALUES, reminderComposition, reminderLayout, reminderStudioPresets, type ReminderItem, type ReminderItemLayout, type ReminderRect, type ReminderState } from '../lib/remindersResponsive.mjs'
import { weatherComposition, weatherLayout, weatherStudioPresets, type WeatherState } from '../lib/weatherResponsive.mjs'
import { countdownComposition, countdownLayout, countdownStudioPresets, fitCountdownStructuredText, type CountdownRect, type CountdownState } from '../lib/countdownResponsive.mjs'
import { dateComposition, dateLayout, dateStudioPresets, fitDateFact, type DateRect, type DateState } from '../lib/dateResponsive.mjs'
import { fitSurfFact, surfComposition, surfLayout, surfRatingWord, surfStudioPresets, type SurfForecast, type SurfRect, type SurfState } from '../lib/surfResponsive.mjs'
import { fitSoccerFact, soccerComposition, soccerFixtureTeamLabels, soccerLayout, soccerStudioPresets, soccerTableWindow, soccerTeamAbbreviation, type SoccerRect, type SoccerState } from '../lib/soccerResponsive.mjs'
import { fitStockFact, formatStockPrice, formatStockSigned, STOCK_RANGE_LABELS, STOCK_RANGES, stockReferenceLine, stocksComposition, stocksLayout, stocksStudioPresets, type StockRect, type StocksState } from '../lib/stocksResponsive.mjs'
import { fitGroceriesText, fitGroceryText, fitMealIdeaText, fitRunningLowText, groceriesComposition, groceriesLayout, groceriesStudioPresets, type GroceriesState, type GroceryRect } from '../lib/groceriesResponsive.mjs'
import { aiFollowComposition, aiFollowLayout, aiFollowStudioPresets, fitAiFollowTitle, wrapAiFollowSummary, type AiFollowRect, type AiFollowState } from '../lib/aiFollowResponsive.mjs'

type Preset = typeof REMINDER_STUDIO_PRESET_VALUES[number]
const fake = {
  date: { normal:['Wednesday','August','19','2026'], long:['torsdag','desember','31','2026'], extreme:['Wednesday','September','30','2099'], empty:['Date unavailable','','',''] },
  reminders: { normal:['Today','Dentist · 14:30','Buy coffee','Call Mum'], long:['Tomorrow','Renew the family travel insurance','Call the electrical contractor','Pick up prescriptions'], extreme:['Upcoming','An exceptionally long reminder that exceeds its clipping region','Another overflowing reminder row','Third oversized item','Fourth overflow item','Fifth overflow item'], empty:['No reminders','Nothing upcoming'] },
  weather: { normal:['Oslo','18°','Partly cloudy','12°','21°'], long:['Longyearbyen','-18°','Snow showers and strong wind','-24°','-12°'], extreme:['A very long location name','-123°','Exceptionally prolonged weather condition','-140°','123°'], empty:['Weather unavailable','','','',''] },
  countdown: { normal:['Summer holiday','42','days','30 June'], long:['Anniversary celebration','365','days','19 August 2027'], extreme:['An extremely long countdown event label','99999','days','31 December 2099'], empty:['No Countdown','No events yet','',''] },
  surf: { normal:["Hoddevik",surfRatingWord(4)!.toUpperCase(),'1.2–1.8 m','12 s'], long:["Today’s Best: Unstad",surfRatingWord(5)!.toUpperCase(),'2.0–3.5 m','15 s'], extreme:['An exceptionally long surf spot',surfRatingWord(6)!.toUpperCase(),'8.0–12.0 m','22 s'], empty:['No surf forecast','--','--','--'] },
  soccer: { normal:['Arsenal vs Liverpool','Sun 16:30','Position: 1','Points: 68'], long:['Manchester United vs Wolverhampton','Wednesday 20:45','Position: 12','Points: 42'], extreme:['Borussia Mönchengladbach vs Paris Saint-Germain','Saturday 23:59','Position: 99','Points: 999'], empty:['No fixtures','--','Position: --','Points: --'] },
  stocks: { normal:['FRAME','124.50','+2.4%','Month'], long:['Berkshire Hathaway Class B','512.18','-0.42%','Year'], extreme:['AN-EXCEPTIONALLY-LONG-SYMBOL','999999','+999.99%','Year'], empty:['No stock','--','--','Day'] },
  groceries: { normal:['Tacos tonight','Milk','Bread','Apples','todayDinner'], long:['Family curry night','Extra virgin olive oil','Wholegrain sourdough bread','Laundry detergent','todayDinner'], extreme:['An exceptionally long grocery heading','A grocery item whose label must clip','Another extremely verbose item','One more oversized item','list'], empty:['All set','Nothing to buy','','','list'] },
} satisfies Record<LegacyModuleName,Record<Preset,string[]>>
const calendarPreset: Record<Preset,{year:number;month0:number}> = {
  normal:{year:2026,month0:7}, long:{year:2026,month0:11},
  extreme:{year:2099,month0:8}, empty:{year:2026,month0:7},
}
const monthNames=['January','February','March','April','May','June','July','August','September','October','November','December']
type CalendarDisplay = { showMonthTitle:boolean; showWeekNums:boolean; showDowHeader:boolean }

function line(ctx:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number) { ctx.beginPath();ctx.moveTo(x1+.5,y1+.5);ctx.lineTo(x2+.5,y2+.5);ctx.stroke() }
function centered(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,w:number,font:string) { ctx.font=font;ctx.textAlign='center';ctx.fillText(text,x+w/2,y) }
function clippedCentered(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,w:number,h=28) { ctx.save();ctx.beginPath();ctx.rect(x,y-h,w,h+4);ctx.clip();ctx.textAlign='center';ctx.fillText(text,x+w/2,y);ctx.restore() }
function metricHeight(font:string) { const match=font.match(/(\d+)px/); return match ? Number(match[1]) : 16 }

function adaptiveHeader(ctx:CanvasRenderingContext2D,c:PixelCell,text:string,p:ResponsiveCellProfile) {
  clippedCentered(ctx,text.toUpperCase(),c.x+8,c.y+Math.min(22,c.h*.18),c.w-16,Math.min(20,c.h*.16))
  if(p.area>=4) ctx.fillRect(c.x+c.w*.3,c.y+Math.min(27,c.h*.22),c.w*.4,2)
}
function adaptiveList(ctx:CanvasRenderingContext2D,c:PixelCell,items:string[],p:ResponsiveCellProfile,start:number) {
  const count=Math.min(items.length,p.density==='expanded'?6:p.density==='normal'?4:p.density==='compact'?2:1)
  if(p.orientation==='landscape'&&count>1){const w=c.w/count;items.slice(0,count).forEach((v,i)=>clippedCentered(ctx,v,c.x+i*w+5,start,c.w/count-10));return}
  const room=c.y+c.h-start-8,rowH=Math.min(28,room/Math.max(1,count));items.slice(0,count).forEach((v,i)=>clippedCentered(ctx,`• ${v}`,c.x+8,start+i*rowH,c.w-16,rowH))
}
function adaptiveMetrics(ctx:CanvasRenderingContext2D,c:PixelCell,values:string[],p:ResponsiveCellProfile,start:number) {
  const shown=values.slice(0,p.density==='micro'?1:p.density==='compact'?2:p.density==='normal'?3:4)
  if(p.orientation==='landscape'){const w=c.w/shown.length;shown.forEach((v,i)=>clippedCentered(ctx,v,c.x+i*w+4,start,w-8));return}
  const gap=Math.min(34,(c.y+c.h-start)/shown.length);shown.forEach((v,i)=>clippedCentered(ctx,v,c.x+6,start+i*gap,c.w-12,gap))
}
function drawResponsiveDate(ctx:CanvasRenderingContext2D,c:PixelCell,p:ResponsiveCellProfile,state:DateState) {
  const composition=dateComposition(p,state),layout=dateLayout(p,composition)
  const absolute=(r:DateRect):DateRect=>({...r,x:c.x+r.x,y:c.y+r.y})
  if(!composition.available&&layout.emptyRect){const r=absolute(layout.emptyRect);centered(ctx,'Date unavailable',r.x,r.y+r.height/2+5,r.width,'14px sans-serif');return}
  const fact=(value:string|number|null,rect:DateRect|null,maxFont:number,weight='bold',uppercase=false)=>{
    if(value==null||!rect)return
    const r=absolute(rect),text=uppercase?String(value).toUpperCase():String(value)
    const fitted=fitDateFact(text,r.width-8,r.height-4,(candidate,size)=>{ctx.font=`${weight} ${size}px sans-serif`;return ctx.measureText(candidate).width},{maxFont,minFont:9})
    if(!fitted)return
    ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.width,r.height);ctx.clip();centered(ctx,fitted.text,r.x,r.y+r.height/2+fitted.fontSize*.36,r.width,`${weight} ${fitted.fontSize}px sans-serif`);ctx.restore()
  }
  if(composition.family==='micro'){
    fact(state.day,layout.dayRect,Math.min(58,(layout.dayRect?.height??58)*.82),'bold')
    fact(state.weekday,layout.weekdayRect,14,'bold',true)
  }else{
    fact(state.year,layout.yearRect,14,'normal')
    fact(state.monthName,layout.monthRect,composition.family==='horizontal'?18:20,'bold',composition.family!=='horizontal')
    fact(state.day,layout.dayRect,composition.family==='horizontal'?34:64,'bold')
    if(layout.weekdayRect){
      const r=absolute(layout.weekdayRect),label=fitDateFact(String(state.weekday).toUpperCase(),r.width-18,r.height-8,(candidate,size)=>{ctx.font=`bold ${size}px sans-serif`;return ctx.measureText(candidate).width},{maxFont:17,minFont:9})
      if(label){const badgeW=Math.min(r.width-4,Math.max(62,ctx.measureText(label.text).width+18)),badgeH=Math.min(r.height-4,label.fontSize+10),bx=r.x+(r.width-badgeW)/2,by=r.y+(r.height-badgeH)/2;ctx.save();ctx.fillStyle='#fff';ctx.fillRect(bx,by,badgeW,badgeH);ctx.fillStyle='#000';centered(ctx,label.text,bx,by+badgeH/2+label.fontSize*.35,badgeW,`bold ${label.fontSize}px sans-serif`);ctx.restore()}
    }
  }
  const today={year:state.year!,month0:state.month0!,day:state.day!}
  if(layout.calendarRect&&composition.currentCalendar){const r=absolute(layout.calendarRect);drawCalendar(ctx,r.x,r.y,r.width,r.height,state.year!,state.month0!,'date',composition.currentCalendar,today)}
  if(layout.nextCalendarRect&&composition.nextCalendar&&Number.isInteger(state.nextMonth0)&&Number.isInteger(state.nextMonthYear)){const r=absolute(layout.nextCalendarRect);drawCalendar(ctx,r.x,r.y,r.width,r.height,state.nextMonthYear!,state.nextMonth0!,'date',composition.nextCalendar,today)}
  if(layout.holidayRect&&composition.holidayRows){const r=absolute(layout.holidayRect);centered(ctx,'UPCOMING HOLIDAYS',r.x,r.y+17,r.width,'bold 13px sans-serif');state.holidays?.slice(0,composition.holidayRows).forEach((holiday,index)=>fact(`${holiday.dateLabel}  ${holiday.title}`,{x:layout.holidayRect!.x,y:layout.holidayRect!.y+25+index*22,width:layout.holidayRect!.width,height:20},14,'normal'))}
}
function drawResponsiveReminders(ctx:CanvasRenderingContext2D,c:PixelCell,p:ResponsiveCellProfile,state:ReminderState) {
  const composition=reminderComposition(p,state),layout=reminderLayout(p,composition)
  if(!composition.available&&layout.emptyRect){const r=layout.emptyRect;centered(ctx,'No reminders',c.x+r.x,c.y+r.y+r.height/2+5,r.width,'14px sans-serif');return}
  const visible=[...state.today.slice(0,composition.todayItems),...state.tomorrow.slice(0,composition.tomorrowItems)]
  const absolute=(r:ReminderRect):ReminderRect=>({...r,x:c.x+r.x,y:c.y+r.y})
  const heading=(label:string,rect:ReminderRect|null)=>{if(!composition.showHeading||!rect)return;const r=absolute(rect);ctx.font='bold 14px sans-serif';ctx.textAlign='left';ctx.fillText(label,r.x,r.y+14);ctx.fillRect(r.x,r.y+19,Math.min(ctx.measureText(label).width,r.width),2)}
  heading('TODAY',layout.todayRect)
  heading('TOMORROW',layout.tomorrowRect)
  const drawItem=(item:ReminderItem,itemLayout:ReminderItemLayout)=>{
    const itemRect=absolute(itemLayout.itemRect),timeRect=absolute(itemLayout.timeRect)
    let titleRect=absolute(itemLayout.titleRect)
    if(!item.time)titleRect={...itemRect,x:itemRect.x+2,width:Math.max(1,itemRect.width-4)}
    const font=`bold ${itemLayout.density.fontSize}px sans-serif`;ctx.font=font;ctx.textAlign='left'
    const baseline=Math.min(itemLayout.density.fontSize+2,timeRect.height)
    if(composition.showTime&&item.time){ctx.save();ctx.beginPath();ctx.rect(timeRect.x,timeRect.y,timeRect.width,timeRect.height);ctx.clip();ctx.fillText(item.time,timeRect.x,timeRect.y+baseline);ctx.restore()}
    const selected=chooseReminderTextVariant(item,titleRect.width,value=>ctx.measureText(value).width)
    ctx.save();ctx.beginPath();ctx.rect(titleRect.x,titleRect.y,titleRect.width,titleRect.height);ctx.clip();ctx.fillText(selected.text,titleRect.x,titleRect.y+Math.min(itemLayout.density.fontSize+2,titleRect.height));ctx.restore()
  }
  visible.forEach((item,index)=>drawItem(item,layout.items[index]))
  if(composition.direction==='horizontal')layout.items.slice(1).forEach(item=>{const r=absolute(item.itemRect);line(ctx,r.x-6,r.y+5,r.x-6,r.y+r.height-5)})
  if(layout.footerRect){const r=absolute(layout.footerRect),label=r.width<48?`+${composition.overflow}`:`+${composition.overflow} more`;ctx.font='bold 12px sans-serif';ctx.textAlign=composition.direction==='horizontal'?'center':'right';ctx.fillText(label,composition.direction==='horizontal'?r.x+r.width/2:r.x+r.width,r.y+r.height/2+4)}
  for(const [rect,count] of [[layout.todayFooterRect,composition.todayOverflow],[layout.tomorrowFooterRect,composition.tomorrowOverflow]] as const){if(rect){const r=absolute(rect);ctx.font='bold 12px sans-serif';ctx.textAlign='right';ctx.fillText(`+${count} more`,r.x+r.width,r.y+r.height/2+4)}}
}
function drawResponsive(ctx:CanvasRenderingContext2D,c:PixelCell,m:LegacyModuleName,d:string[],p:ResponsiveCellProfile) {
  const centerY=c.y+c.h*(p.orientation==='portrait'?.38:.53)
  if(m==='date') {
    if(p.orientation==='landscape'){centered(ctx,`${d[0]} ${d[2]}. ${d[1]}`,c.x,centerY,c.w,'bold 17px sans-serif');return}
    centered(ctx,d[0].toUpperCase(),c.x,c.y+Math.min(24,c.h*.2),c.w,'bold 13px sans-serif');centered(ctx,d[2],c.x,centerY+12,c.w,`bold ${Math.min(54,c.h*.36)}px sans-serif`);if(p.area>1)centered(ctx,d[1].toUpperCase(),c.x,c.y+c.h-15,c.w,'bold 13px sans-serif');if(p.area>=8)centered(ctx,d[3],c.x,c.y+c.h-35,c.w,'12px sans-serif');return
  }
  const titles:Record<Exclude<LegacyModuleName,'date'>,string>={reminders:'Today',weather:d[0],countdown:d[0],surf:d[0],soccer:'Next fixture',stocks:d[0],groceries:'Groceries'}
  adaptiveHeader(ctx,c,titles[m as Exclude<LegacyModuleName,'date'>],p)
  if(m==='reminders'){adaptiveList(ctx,c,d.slice(1).length?d.slice(1):['No reminders'],p,c.y+Math.min(58,c.h*.4));return}
  if(m==='weather'){weatherIcon(ctx,c.x+c.w*(p.orientation==='portrait'?.25:.06),c.y+c.h*.27,Math.min(c.w*.5,90),Math.min(c.h*.4,80));adaptiveMetrics(ctx,c,[d[1],`Wind 4 m/s`,'Dry',`${d[3]} / ${d[4]}`],p,p.orientation==='landscape'?centerY:c.y+c.h*.7);return}
  if(m==='countdown'){centered(ctx,d[1],c.x,centerY+10,c.w,`bold ${Math.min(52,c.h*.32)}px sans-serif`);centered(ctx,'DAYS',c.x,Math.min(c.y+c.h-13,centerY+34),c.w,'bold 13px sans-serif');if(p.area>=6)centered(ctx,d[3],c.x,c.y+c.h-13,c.w,'12px sans-serif');return}
  if(m==='surf'){adaptiveMetrics(ctx,c,['POOR',d[2],d[3],'Wind 5 m/s'],p,c.y+Math.min(58,c.h*.42));if(p.area>=6)ratingBlocks(ctx,c.x+c.w/2-Math.min(65,c.w*.35),c.y+c.h-35,Math.min(130,c.w*.7),2);return}
  if(m==='soccer'){adaptiveMetrics(ctx,c,['ARS vs LIV',d[1],d[2],d[3]],p,c.y+Math.min(58,c.h*.42));return}
  if(m==='stocks'){adaptiveMetrics(ctx,c,[d[1],d[2],d[3]],p,c.y+Math.min(58,c.h*.42));if(p.area>=6)drawSparkline(ctx,c.x+15,c.y+c.h*.64,c.w-30,c.h*.25);return}
  adaptiveList(ctx,c,d.slice(1,4),p,c.y+Math.min(58,c.h*.42))
}

function drawCalendar(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,year:number,month0:number,mode:CalendarRowMode,display:CalendarDisplay,today?:{year:number;month0:number;day:number}) {
  const p=moduleProfiles.date.calendar,padX=p.padding[0],padY=p.padding[1],weekW=display.showWeekNums?p.weekWidth:0,titleH=display.showMonthTitle?p.titleHeight:0,titleGap=display.showMonthTitle?p.titleGap:0,dowH=display.showDowHeader?p.dowHeight:0
  ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();let top=y+padY
  if(display.showMonthTitle){ctx.font='bold 16px sans-serif';centered(ctx,monthNames[month0],x,top+18,w,'bold 16px sans-serif');top+=titleH+titleGap}
  const {firstWeekday,dayCount,rows}=calendarGeometry(year,month0,mode)
  const gridX0=x+padX+weekW,gridW=Math.max(7,w-padX*2-weekW),cellW=Math.trunc(gridW/7),cellH=Math.max(10,Math.trunc((h-padY*2-titleH-titleGap-dowH)/rows))
  if(display.showDowHeader){ctx.font='11px sans-serif';['Mo','Tu','We','Th','Fr','Sa','Su'].forEach((d,i)=>centered(ctx,d,gridX0+i*cellW,top+12,cellW,'11px sans-serif'));top+=dowH}
  if(display.showWeekNums){line(ctx,gridX0-1,top+2,gridX0-1,top+rows*cellH-2);for(let row=0;row<rows;row++){const firstDay=row*7-firstWeekday+1,lastDay=firstDay+6;if(lastDay<1||firstDay>dayCount)continue;const sampleDay=Math.max(1,Math.min(dayCount,firstDay));centered(ctx,String(isoWeekNumber(year,month0,sampleDay)),x+padX,top+row*cellH+Math.trunc(cellH/2)+4,weekW,'11px sans-serif')}}
  for(let day=1;day<=dayCount;day++){const index=firstWeekday+day-1,row=Math.trunc(index/7),col=index%7;if(row>=rows)continue;const cellX=gridX0+col*cellW,cellY=top+row*cellH,cx=cellX+cellW/2,cy=cellY+cellH/2,isCurrentMonth=today?month0===today.month0&&year===today.year:month0===calendarPreset.normal.month0&&year===calendarPreset.normal.year,isToday=isCurrentMonth&&day===(today?.day??19),isDate=mode==='date'||mode==='dateLarge',isReminder=mode==='remindersLarge'||mode==='remindersXL';if((isDate||isReminder)&&isToday){ctx.save();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(cx,cy,Math.max(5,Math.min(16,Math.min(cellW,cellH)/2-2)),0,Math.PI*2);ctx.fill();ctx.fillStyle='#000';centered(ctx,String(day),cellX,cy+4,cellW,'11px sans-serif');ctx.restore()}else centered(ctx,String(day),cellX,cy+4,cellW,'11px sans-serif');if(isDate&&[24,31].includes(day)){ctx.beginPath();ctx.arc(cx,cellY+cellH-3,2,0,Math.PI*2);ctx.fill()}if(isReminder&&!isToday&&[7,12,24].includes(day)){for(let dot=0;dot<(day===12?2:1);dot++){ctx.beginPath();ctx.arc(cx+(dot?4:-2),cellY+cellH-2,2,0,Math.PI*2);ctx.fill()}}}
  if(mode==='countdown'){for(const day of [2,3,4]){const index=firstWeekday+day-1,row=Math.trunc(index/7),col=index%7,cx=gridX0+col*cellW+cellW/2,cy=top+row*cellH+cellH/2;line(ctx,cx-5,cy-5,cx+5,cy+5);line(ctx,cx+5,cy-5,cx-5,cy+5)}const day=Math.min(19,dayCount),index=firstWeekday+day-1,row=Math.trunc(index/7),col=index%7;ctx.beginPath();ctx.arc(gridX0+col*cellW+cellW/2,top+row*cellH+cellH/2,Math.min(cellW,cellH)*.42,0,Math.PI*2);ctx.stroke()}
  ctx.restore()
}
function drawMediumStack(ctx:CanvasRenderingContext2D,c:PixelCell,parts:string[],kind:'date'|'countdown') {
  const profile=kind==='date'?moduleProfiles.date.medium:moduleProfiles.countdown.medium
  const fonts=kind==='date'?['14px sans-serif','bold 18px sans-serif','bold 42px sans-serif','bold 17px sans-serif']:['bold 17px sans-serif','bold 28px sans-serif','14px sans-serif','bold 16px sans-serif']
  const heights=fonts.map(metricHeight),gaps=profile.gaps,badgeH=heights[3]+profile.badgePadding[1]*2
  const total=heights[0]+gaps[0]+heights[1]+gaps[1]+heights[2]+gaps[2]+badgeH;let y=c.y+Math.trunc((c.h-total)/2)
  parts.forEach((part,i)=>{if(i===3){const badgeW=Math.min(c.w-profile.maxBadgeInset,Math.max(100,part.length*10+profile.badgePadding[0]*2)),bx=c.x+(c.w-badgeW)/2;ctx.save();ctx.fillStyle='#fff';ctx.fillRect(bx,y,badgeW,badgeH);ctx.fillStyle='#000';centered(ctx,part,bx,y+profile.badgePadding[1]+heights[3],badgeW,fonts[3]);ctx.restore()}else{centered(ctx,part,c.x,y+heights[i],c.w,fonts[i]);y+=heights[i]+gaps[i]}})
}
function drawDate(ctx:CanvasRenderingContext2D,c:PixelCell,d:string[],preset:Preset) {
  const {year,month0}=calendarPreset[preset],nextMonth0=(month0+1)%12,nextYear=month0===11?year+1:year
  if(c.size==='SMALL'){clippedCentered(ctx,`${d[0]} ${d[2]}. ${d[1]}`,c.x+8,c.y+c.h/2+9,c.w-16);return}
  if(c.size==='MEDIUM'){drawMediumStack(ctx,c,[d[3],d[1],d[2],d[0]],'date');return}
  const gap=moduleProfiles.date.large.columnGap,leftW=Math.trunc((c.w-gap)/2),rightX=c.x+leftW+gap
  if(c.size==='LARGE'){drawMediumStack(ctx,{...c,w:leftW},[d[3],d[1],d[2],d[0]],'date');const p=moduleProfiles.date.large.calendarPadding;drawCalendar(ctx,rightX+p,c.y+p,c.w-leftW-gap-p*2,c.h-p*2,year,month0,'dateLarge',{showMonthTitle:false,showWeekNums:true,showDowHeader:true});return}
  const rowGap=moduleProfiles.date.xl.rowGap,topH=Math.trunc((c.h-rowGap)/2),bottomY=c.y+topH+rowGap,rightW=c.w-leftW-gap
  drawMediumStack(ctx,{...c,w:leftW,h:topH},[d[3],d[1],d[2],d[0]],'date');centered(ctx,'UPCOMING HOLIDAYS',c.x,bottomY+30,leftW,'bold 14px sans-serif');centered(ctx,'24.12  Christmas Eve',c.x,bottomY+65,leftW,'14px sans-serif')
  const mp=moduleProfiles.date.xl.monthPadding,rp=moduleProfiles.date.xl.rightPadding;drawCalendar(ctx,rightX,c.y+mp-9,rightW-rp,topH-mp+8,year,month0,'date',{showMonthTitle:true,showWeekNums:true,showDowHeader:true});drawCalendar(ctx,rightX,bottomY,rightW-rp,c.y+c.h-bottomY-mp,nextYear,nextMonth0,'date',{showMonthTitle:true,showWeekNums:true,showDowHeader:false})
}
function drawReminderMedium(ctx:CanvasRenderingContext2D,c:PixelCell,d:string[],small:boolean) {
  const p=small?moduleProfiles.reminders.small:moduleProfiles.reminders.medium,titleY=c.y+p.topPadding,isFuture=!small&&!['Today','Tomorrow'].includes(d[0]),maxItems=small?moduleProfiles.reminders.small.maxItems:isFuture?moduleProfiles.reminders.medium.maxFutureItems:moduleProfiles.reminders.medium.maxTodayItems,visible=Math.min(d.length-1,maxItems)
  ctx.font='bold 17px sans-serif';const titleW=Math.min(c.w-20,d[0].length*10);centered(ctx,d[0],c.x,titleY+17,c.w,'bold 17px sans-serif');ctx.fillRect(c.x+(c.w-titleW)/2,titleY+20,titleW,p.underlineHeight)
  if(d.length-1>visible){ctx.font='11px sans-serif';ctx.textAlign='right';ctx.fillText(`+${d.length-1-visible} more`,c.x+c.w-10,c.y+14)}
  const tomorrowNote=d[0]==='Today'?'Tomorrow: 2':'',badge=isFuture?'IN 16 DAYS':'',badgeH=badge?30:0,contentTop=titleY+20+p.underlineHeight+p.contentGap,contentBottom=c.y+c.h-(badge?49:tomorrowNote?34:12),contentH=contentBottom-contentTop
  if(small){for(let i=1;i<visible;i++)line(ctx,c.x+Math.trunc(c.w*i/visible),contentTop+8,c.x+Math.trunc(c.w*i/visible),contentBottom-8);for(let i=0;i<visible;i++){const x0=c.x+Math.trunc(c.w*i/visible),x1=c.x+Math.trunc(c.w*(i+1)/visible);clippedCentered(ctx,d[i+1],x0+8,contentTop+contentH/2+7,x1-x0-16)}}
  else {const rowH=Math.min(36,contentH/Math.max(1,visible)),blockH=rowH*visible,startY=contentTop+(contentH-blockH)/2;for(let i=0;i<visible;i++){const cy=startY+i*rowH+rowH/2;ctx.beginPath();ctx.arc(c.x+35,cy,3,0,Math.PI*2);ctx.fill();clippedCentered(ctx,d[i+1],c.x+48,cy+6,c.w-83,rowH)}}
  if(tomorrowNote)centered(ctx,tomorrowNote,c.x,c.y+c.h-26,c.w,'11px sans-serif')
  if(badge){const bw=Math.min(c.w-18,116),bx=c.x+(c.w-bw)/2,by=c.y+c.h-35-badgeH;ctx.save();ctx.fillStyle='#fff';ctx.fillRect(bx,by,bw,badgeH);ctx.fillStyle='#000';centered(ctx,badge,bx,by+20,bw,'bold 11px sans-serif');ctx.restore()}
}
function drawReminders(ctx:CanvasRenderingContext2D,c:PixelCell,d:string[],preset:Preset) {
  const {year,month0}=calendarPreset[preset],nextMonth0=(month0+1)%12,nextYear=month0===11?year+1:year
  if(c.size==='SMALL'){drawReminderMedium(ctx,c,d,true);return}if(c.size==='MEDIUM'){drawReminderMedium(ctx,c,d,false);return}
  const gap=moduleProfiles.reminders.large.columnGap,leftW=Math.trunc((c.w-gap)/2),rightX=c.x+leftW+gap
  if(c.size==='LARGE'){const p=moduleProfiles.reminders.large;drawReminderMedium(ctx,{...c,w:leftW},d,false);drawCalendar(ctx,rightX+p.calendarPadding,c.y+p.calendarPadding,c.w-leftW-gap-p.calendarPadding*2,c.h-p.calendarPadding*2,year,month0,'remindersLarge',{showMonthTitle:false,showWeekNums:true,showDowHeader:true});return}
  const p=moduleProfiles.reminders.xl
  const topH=Math.trunc((c.h-p.rowGap)/2),bottomY=c.y+topH+p.rowGap,rightW=c.w-leftW-gap;drawReminderMedium(ctx,{...c,w:leftW,h:topH},d,false);const nextRows=moduleProfiles.reminders.xl.nextReminderRows,rowH=32,startY=bottomY+topH-nextRows*rowH-24;for(let i=0;i<nextRows;i++){const ry=startY+i*rowH;ctx.font='12px sans-serif';ctx.textAlign='right';ctx.fillText(`${String(20+i).padStart(2,'0')}.08`,c.x+82,ry+18);ctx.textAlign='left';ctx.fillText(d[1+i%(Math.max(1,d.length-1))]||'Upcoming reminder',c.x+98,ry+18)};drawCalendar(ctx,rightX,c.y+p.monthPadding-9,rightW-p.rightPadding,topH-p.monthPadding+8,year,month0,'remindersXL',{showMonthTitle:true,showWeekNums:true,showDowHeader:true});drawCalendar(ctx,rightX,bottomY,rightW-p.rightPadding,c.y+c.h-bottomY-p.monthPadding,nextYear,nextMonth0,'remindersXL',{showMonthTitle:true,showWeekNums:true,showDowHeader:false})
}
function weatherIcon(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number){const r=Math.min(w,h)*.22;ctx.beginPath();ctx.arc(x+w*.42,y+h*.42,r,Math.PI,Math.PI*2);ctx.arc(x+w*.58,y+h*.48,r*.8,Math.PI,Math.PI*2);ctx.lineTo(x+w*.76,y+h*.68);ctx.lineTo(x+w*.25,y+h*.68);ctx.closePath();ctx.stroke();line(ctx,x+w*.35,y+h*.82,x+w*.31,y+h*.94);line(ctx,x+w*.55,y+h*.82,x+w*.51,y+h*.94);line(ctx,x+w*.72,y+h*.82,x+w*.68,y+h*.94)}
type WeatherRect={x:number;y:number;width:number;height:number}
function fitWeatherText(ctx:CanvasRenderingContext2D,value:string|null|undefined,rect:WeatherRect,options:{maxFont:number;minFont:number;bold?:boolean;maxLines?:number}){
  if(!value||rect.width<8||rect.height<options.minFont)return
  const maxLines=options.maxLines??1,prefix=options.bold?'bold ':''
  const ellipsize=(text:string,width:number)=>{if(ctx.measureText(text).width<=width)return text;let lo=0,hi=text.length;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(ctx.measureText(`${text.slice(0,mid).trimEnd()}…`).width<=width)lo=mid;else hi=mid-1}return lo?`${text.slice(0,lo).trimEnd()}…`:''}
  for(let size=options.maxFont;size>=options.minFont;size--){
    ctx.font=`${prefix}${size}px sans-serif`;const words=value.split(/\s+/),lines:string[]=[];let current=''
    for(const word of words){const candidate=current?`${current} ${word}`:word;if(ctx.measureText(candidate).width<=rect.width)current=candidate;else{if(current)lines.push(current);current=word}}
    if(current)lines.push(current)
    if(lines.length<=maxLines&&lines.length*size*1.2<=rect.height){ctx.textAlign='center';lines.forEach((text,index)=>ctx.fillText(text,rect.x+rect.width/2,rect.y+size+(index*size*1.2)));return}
    if(size===options.minFont){const shown=lines.slice(0,maxLines);shown[maxLines-1]=ellipsize(lines.slice(maxLines-1).join(' '),rect.width);ctx.textAlign='center';shown.filter(Boolean).forEach((text,index)=>ctx.fillText(text,rect.x+rect.width/2,rect.y+size+(index*size*1.2)))}
  }
}
function drawResponsiveWeather(ctx:CanvasRenderingContext2D,c:PixelCell,p:ResponsiveCellProfile,state:WeatherState){
  const composition=weatherComposition(p,state),layout=weatherLayout(p,composition),offset=(rect:WeatherRect|null)=>rect&&({x:c.x+rect.x,y:c.y+rect.y,width:rect.width,height:rect.height})
  if(!composition.available){centered(ctx,'Weather unavailable',c.x,c.y+c.h/2+5,c.w,'14px sans-serif');return}
  const header=offset(layout.headerRect),primary=offset(layout.primaryRect)!,detailsRect=offset(layout.detailsRect),forecast=offset(layout.forecastRect)
  const range=[state.low&&`Low ${state.low}`,state.high&&`High ${state.high}`].filter(Boolean).join('  '),wind=[state.windDirection,state.windSpeed].filter(Boolean).join(' ')
  const detailLines=[composition.showRange&&range,composition.showWind&&wind&&`Wind ${wind}`,composition.showPrecipitation&&`Rain ${state.precipitationProbability}%`].filter(Boolean) as string[]
  if(header&&state.location){fitWeatherText(ctx,state.location,header,{maxFont:13,minFont:10,bold:true});ctx.font='bold 13px sans-serif';const underline=Math.min(header.width*.68,ctx.measureText(state.location).width);ctx.fillRect(header.x+(header.width-underline)/2,header.y+Math.min(header.height-5,18),underline,2)}
  ctx.save();ctx.beginPath();ctx.rect(primary.x,primary.y,primary.width,primary.height);ctx.clip()
  if(composition.layout==='vertical'){
    const tempH=Math.min(58,primary.height*.3),iconH=Math.min(88,primary.height*.4),conditionH=composition.showCondition?Math.max(0,primary.height-tempH-iconH):0
    fitWeatherText(ctx,state.temperature,{x:primary.x,y:primary.y,width:primary.width,height:tempH},{maxFont:Math.min(42,tempH*.72),minFont:22,bold:true})
    const iconW=Math.min(primary.width*.62,90);weatherIcon(ctx,primary.x+(primary.width-iconW)/2,primary.y+tempH,iconW,iconH)
    if(conditionH>=16)fitWeatherText(ctx,state.condition,{x:primary.x,y:primary.y+tempH+iconH,width:primary.width,height:conditionH},{maxFont:13,minFont:10,bold:true,maxLines:conditionH>=28?2:1})
  }else{
    const iconW=Math.min(primary.width*.34,94),gap=Math.min(12,primary.width*.04),textRect={x:primary.x+iconW+gap,y:primary.y,width:Math.max(1,primary.width-iconW-gap),height:primary.height}
    weatherIcon(ctx,primary.x,primary.y+primary.height*.12,iconW,primary.height*.72)
    const tempH=composition.showCondition?primary.height*.58:primary.height
    fitWeatherText(ctx,state.temperature,{...textRect,height:tempH},{maxFont:Math.min(42,tempH*.62),minFont:22,bold:true})
    if(composition.showCondition)fitWeatherText(ctx,state.condition,{x:textRect.x,y:textRect.y+tempH,width:textRect.width,height:textRect.height-tempH},{maxFont:13,minFont:10,bold:true,maxLines:textRect.height-tempH>=28?2:1})
  }
  ctx.restore()
  if(detailsRect){const rowH=detailsRect.height/Math.max(1,detailLines.length);detailLines.forEach((value,index)=>fitWeatherText(ctx,value,{x:detailsRect.x,y:detailsRect.y+index*rowH,width:detailsRect.width,height:rowH},{maxFont:12,minFont:10,maxLines:rowH>=28?2:1}))}
  if(forecast&&layout.dividerY!=null){line(ctx,forecast.x,c.y+layout.dividerY,forecast.x+forecast.width,c.y+layout.dividerY);const columnW=forecast.width/composition.forecastRows;state.forecast?.slice(0,composition.forecastRows).forEach((item,index)=>{const column={x:forecast.x+index*columnW,y:forecast.y,width:columnW,height:forecast.height};if(index)line(ctx,column.x,column.y+7,column.x,column.y+column.height-5);ctx.save();ctx.beginPath();ctx.rect(column.x+4,column.y,column.width-8,column.height);ctx.clip();fitWeatherText(ctx,item.day,{x:column.x+5,y:column.y+4,width:column.width-10,height:22},{maxFont:12,minFont:10,bold:true});fitWeatherText(ctx,item.temperature,{x:column.x+5,y:column.y+30,width:column.width-10,height:25},{maxFont:15,minFont:12,bold:true});fitWeatherText(ctx,item.condition,{x:column.x+5,y:column.y+59,width:column.width-10,height:column.height-61},{maxFont:11,minFont:9,maxLines:2});ctx.restore()})}
  else if(composition.showInsight&&detailsRect)fitWeatherText(ctx,state.insight,detailsRect,{maxFont:11,minFont:9,maxLines:2})
}
function weatherColumn(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,label:string,d:string[]){centered(ctx,label,x,y+20,w,'bold 15px sans-serif');weatherIcon(ctx,x+w*.25,y+h*.2,w*.5,h*.38);centered(ctx,`${d[3]} | ${d[4]}`,x,y+h-42,w,'bold 14px sans-serif');centered(ctx,'Wind 5 m/s · Rain 20%',x,y+h-20,w,'12px sans-serif')}
function drawWeather(ctx:CanvasRenderingContext2D,c:PixelCell,d:string[]){
  if(c.size==='SMALL'){const p=moduleProfiles.weather.small,top=c.y+(c.h-58)/2;centered(ctx,d[0],c.x,top+16,c.w,'bold 17px sans-serif');ctx.fillRect(c.x+c.w/2-d[0].length*4,top+20,d[0].length*8,p.underlineHeight);centered(ctx,`${d[3]} to ${d[4]}  |  Wind 5 m/s  |  Rain 20%`,c.x,top+58,c.w,'bold 15px sans-serif');return}
  if(c.size==='MEDIUM'){centered(ctx,`Low ${d[3]}       High ${d[4]}`,c.x,c.y+30,c.w,'bold 18px sans-serif');line(ctx,c.x+c.w*.2,c.y+42,c.x+c.w*.8,c.y+42);centered(ctx,'INSIGHT · Clearing this afternoon',c.x,c.y+65,c.w,'11px sans-serif');weatherIcon(ctx,c.x+c.w*.32,c.y+72,c.w*.36,c.h*.42);centered(ctx,'Wind 5 m/s',c.x,c.y+c.h-42,c.w,'13px sans-serif');centered(ctx,'Precipitation 20%',c.x,c.y+c.h-20,c.w,'13px sans-serif');return}
  if(c.size==='LARGE'){const p=moduleProfiles.weather.large;centered(ctx,d[0],c.x,c.y+p.topPadding,c.w,'bold 17px sans-serif');line(ctx,c.x+c.w*.35,c.y+p.topPadding+6,c.x+c.w*.65,c.y+p.topPadding+6);const top=c.y+p.topPadding+30,w=c.w/p.columns;for(let i=0;i<p.columns;i++){if(i)line(ctx,c.x+i*w,top+12,c.x+i*w,c.y+c.h-18);weatherColumn(ctx,c.x+i*w,top,w,c.y+c.h-top,['Today','Thu','Fri','Sat'][i],d)}return}
  const p=moduleProfiles.weather.xl,topH=c.h/p.topRows,third=c.w/p.topColumns,dividerY=c.y+topH;line(ctx,c.x+c.w*.025,dividerY,c.x+c.w*.975,dividerY);for(let i=1;i<3;i++)line(ctx,c.x+i*third,c.y+25,c.x+i*third,dividerY-20);centered(ctx,d[0],c.x,c.y+32,third,'bold 15px sans-serif');['Low '+d[3],'High '+d[4],'Wind 5 m/s','Rain 20%','Sun 06:01 / 20:32','Humidity 68%'].forEach((v,i)=>centered(ctx,v,c.x,c.y+62+i*24,third,'12px sans-serif'));centered(ctx,'TODAY',c.x+third,c.y+32,third,'bold 15px sans-serif');weatherIcon(ctx,c.x+third+third*.25,c.y+48,third*.5,topH*.5);centered(ctx,d[1],c.x+third,c.y+topH-22,third,'bold 28px sans-serif');centered(ctx,'WEATHER INSIGHT',c.x+third*2,c.y+32,third,'bold 14px sans-serif');['Clouds clearing after lunch','with a light western wind.','Dry through the evening.'].forEach((v,i)=>centered(ctx,v,c.x+third*2,c.y+72+i*25,third,'12px sans-serif'));const colW=c.w/4;for(let i=0;i<4;i++){if(i)line(ctx,c.x+i*colW,dividerY+20,c.x+i*colW,c.y+c.h-18);weatherColumn(ctx,c.x+i*colW,dividerY+8,colW,c.h-topH-8,['Thu','Fri','Sat','Sun'][i],d)}
}
function drawResponsiveCountdown(ctx:CanvasRenderingContext2D,c:PixelCell,p:ResponsiveCellProfile,state:CountdownState){
  const composition=countdownComposition(p,state),layout=countdownLayout(p,composition)
  const effectiveDate=state.displayDate||state.targetDate
  const absolute=(rect:CountdownRect|null)=>rect&&({x:c.x+rect.x,y:c.y+rect.y,width:rect.width,height:rect.height})
  if(!composition.available){centered(ctx,'No countdown',c.x,c.y+c.h/2+5,c.w,'14px sans-serif');return}
  const title=absolute(layout.titleRect),count=absolute(layout.countRect)!,unit=absolute(layout.unitRect)!,date=absolute(layout.targetDateRect),upcomingGroup=absolute(layout.upcomingGroupRect)
  const ellipsize=(value:string,width:number)=>{if(ctx.measureText(value).width<=width)return value;let lo=0,hi=value.length;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(ctx.measureText(`${value.slice(0,mid).trimEnd()}…`).width<=width)lo=mid;else hi=mid-1}return lo?`${value.slice(0,lo).trimEnd()}…`:''}
  const fitted=(value:string,rect:CountdownRect,{max=17,min=11,lines=1,bold=true}:{max?:number;min?:number;lines?:number;bold?:boolean}={})=>{
    const prefix=bold?'bold ':''
    for(let size=max;size>=min;size--){ctx.font=`${prefix}${size}px sans-serif`;const words=value.split(/\s+/),wrapped:string[]=[];let current='';for(const word of words){const candidate=current?`${current} ${word}`:word;if(ctx.measureText(candidate).width<=rect.width)current=candidate;else{if(current)wrapped.push(current);current=word}}if(current)wrapped.push(current);if(wrapped.length<=lines&&wrapped.length*size*1.2<=rect.height){ctx.textAlign='center';wrapped.forEach((text,index)=>ctx.fillText(text,rect.x+rect.width/2,rect.y+size+(index*size*1.2)));return}if(size===min){const shown=wrapped.slice(0,lines);shown[lines-1]=ellipsize(wrapped.slice(lines-1).join(' '),rect.width);ctx.textAlign='center';shown.filter(Boolean).forEach((text,index)=>ctx.fillText(text,rect.x+rect.width/2,rect.y+size+(index*size*1.2)))}}
  }
  const structured=(value:string,rect:CountdownRect,{max=16,min=9}:{max?:number;min?:number}={})=>{
    const result=fitCountdownStructuredText(value,rect.width,rect.height,(text,size)=>{ctx.font=`bold ${size}px sans-serif`;return ctx.measureText(text).width},{maxFont:max,minFont:min})
    if(!result)return false
    ctx.font=`bold ${result.fontSize}px sans-serif`;ctx.textAlign='center';ctx.fillText(result.text,rect.x+rect.width/2,rect.y+(rect.height+result.fontSize*.72)/2);return true
  }
  if(title&&state.title)fitted(state.title,title,{max:17,min:11,lines:title.height>=38?2:1})
  // Count is always drawn verbatim. Only its font size changes to fit the allocated hero region.
  const countValue=state.count!,maxCount=Math.max(18,Math.min(76,Math.floor(count.height*.82))),minCount=10
  let countSize=maxCount;for(;countSize>minCount;countSize--){ctx.font=`bold ${countSize}px sans-serif`;if(ctx.measureText(countValue).width<=count.width-2&&countSize<=count.height*.88)break}
  ctx.font=`bold ${countSize}px sans-serif`;ctx.textAlign='center';ctx.fillText(countValue,count.x+count.width/2,count.y+(count.height+countSize*.72)/2)
  structured(state.unit!,unit,{max:composition.family==='horizontal'?15:16,min:9})
  if(date&&effectiveDate){ctx.font='bold 12px sans-serif';if(ctx.measureText(effectiveDate).width<=date.width-12){const badgeW=Math.min(date.width,ctx.measureText(effectiveDate).width+18),badgeH=Math.min(25,date.height),bx=date.x+(date.width-badgeW)/2,by=date.y+(date.height-badgeH)/2;ctx.save();ctx.fillStyle='#fff';ctx.fillRect(bx,by,badgeW,badgeH);ctx.fillStyle='#000';centered(ctx,effectiveDate,bx,by+17,badgeW,'bold 12px sans-serif');ctx.restore()}}
  if(upcomingGroup){centered(ctx,'COMING UP',upcomingGroup.x,upcomingGroup.y+15,upcomingGroup.width,'bold 12px sans-serif');layout.upcomingRows.forEach((local,index)=>{const item=state.upcoming?.[index];if(!item)return;const titleRect=absolute(local.titleRect)!,metricRect=absolute(local.metricRect)!,metric=`${item.count} ${item.unit}`;ctx.font='12px sans-serif';ctx.textAlign='left';ctx.fillText(ellipsize(item.title,titleRect.width),titleRect.x,titleRect.y+(titleRect.height+12*.72)/2);structured(metric,metricRect,{max:12,min:9})})}
}
function drawCountdown(ctx:CanvasRenderingContext2D,c:PixelCell,d:string[],preset:Preset){
  const {year,month0}=calendarPreset[preset],nextMonth0=(month0+1)%12,nextYear=month0===11?year+1:year
  if(c.size==='SMALL'){clippedCentered(ctx,`${d[0]} in ${d[1]} ${d[2]}`,c.x+moduleProfiles.countdown.small.horizontalInset,c.y+c.h/2+7,c.w-moduleProfiles.countdown.small.horizontalInset*2);return}
  if(c.size==='MEDIUM'){drawMediumStack(ctx,c,d,'countdown');return}
  const p=c.size==='LARGE'?moduleProfiles.countdown.large:moduleProfiles.countdown.xl,gap=p.columnGap,leftW=Math.trunc((c.w-gap)/2),rightX=c.x+leftW+gap
  if(c.size==='LARGE'){drawMediumStack(ctx,{...c,w:leftW},d,'countdown');centered(ctx,'COMING UP',rightX,c.y+55,c.w-leftW-gap,'bold 14px sans-serif');for(let i=0;i<p.listRows;i++)clippedCentered(ctx,`• Event ${i+2} in ${i*14+60} days`,rightX+12,c.y+90+i*28,c.w-leftW-gap-24);return}
  const topH=Math.trunc((c.h-p.rowGap)/2),botY=c.y+topH+p.rowGap,rightW=c.w-leftW-gap;drawMediumStack(ctx,{...c,w:leftW,h:topH},d,'countdown');centered(ctx,'COMING UP',c.x,botY+30,leftW,'bold 14px sans-serif');for(let i=0;i<p.listRows;i++)clippedCentered(ctx,`• Event ${i+2}`,c.x+12,botY+60+i*26,leftW-24);drawCalendar(ctx,rightX,c.y,rightW,topH,year,month0,'countdown',{showMonthTitle:true,showWeekNums:false,showDowHeader:true});drawCalendar(ctx,rightX,botY,rightW,c.y+c.h-botY,nextYear,nextMonth0,'countdown',{showMonthTitle:true,showWeekNums:false,showDowHeader:false})
}
function drawSparkline(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number){const points=[.72,.55,.62,.3,.45,.18,.26,.08];ctx.strokeRect(x+.5,y+.5,w-1,h-1);ctx.beginPath();points.forEach((v,i)=>{const px=x+i*w/(points.length-1),py=y+v*h;i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke()}
function underlinedHeading(ctx:CanvasRenderingContext2D,text:string,c:PixelCell,y:number){centered(ctx,text,c.x,y,c.w,'bold 17px sans-serif');const w=Math.min(c.w-24,text.length*9);ctx.fillRect(c.x+(c.w-w)/2,y+5,w,2)}
function ratingBlocks(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,rating=4){const gap=4,boxW=Math.min(24,Math.trunc((w-gap*5)/6));for(let i=0;i<6;i++){ctx.strokeRect(x+i*(boxW+gap),y,boxW,18);if(i<rating)ctx.fillRect(x+i*(boxW+gap)+3,y+3,boxW-6,12)}}
function experienceDice(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,rating=4){const gap=4,size=Math.min(18,Math.trunc((w-gap*5)/6)),pipColor=ctx.fillStyle==='#fff'?'#000':'#fff';for(let i=0;i<6;i++){const dx=x+i*(size+gap);ctx.strokeRect(dx,y,size,size);if(i>=rating)continue;ctx.fillRect(dx,y,size,size);ctx.save();ctx.fillStyle=pipColor;const pip=(px:number,py:number)=>{ctx.beginPath();ctx.arc(dx+px*size,y+py*size,Math.max(1,size/11),0,Math.PI*2);ctx.fill()};const value=i+1;if(value%2)pip(.5,.5);if(value>=2){pip(.28,.28);pip(.72,.72)}if(value>=4){pip(.72,.28);pip(.28,.72)}if(value===6){pip(.28,.5);pip(.72,.5)}ctx.restore()}}
function adaptiveSurfRatingVisual(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,rating:number,experience:boolean){if(experience)experienceDice(ctx,x,y,w,rating);else ratingBlocks(ctx,x,y,w,rating)}
function arrowIcon(ctx:CanvasRenderingContext2D,x:number,y:number,size:number,down=false){line(ctx,x,y,x+(down?0:size),y+(down?size:0));if(down){line(ctx,x,y+size,x-4,y+size-6);line(ctx,x,y+size,x+4,y+size-6)}else{line(ctx,x+size,y,x+size-6,y-4);line(ctx,x+size,y,x+size-6,y+4)}}
function metricIcon(ctx:CanvasRenderingContext2D,x:number,y:number,kind:'wave'|'wind'|'drop'|'sun'){if(kind==='drop'){ctx.beginPath();ctx.moveTo(x+7,y);ctx.quadraticCurveTo(x+16,y+12,x+7,y+18);ctx.quadraticCurveTo(x-2,y+12,x+7,y);ctx.stroke()}else if(kind==='sun'){ctx.beginPath();ctx.arc(x+8,y+9,6,0,Math.PI*2);ctx.stroke();line(ctx,x,y+18,x+16,y+18)}else{ctx.beginPath();ctx.arc(x+6,y+9,5,Math.PI,0);ctx.arc(x+16,y+9,5,Math.PI,0);ctx.stroke();if(kind==='wind')line(ctx,x,y+15,x+22,y+15)}}
function drawResponsiveSurf(ctx:CanvasRenderingContext2D,c:PixelCell,p:ResponsiveCellProfile,state:SurfState){
 const composition=surfComposition(p,state),layout=surfLayout(p,composition),absolute=(r:SurfRect):SurfRect=>({...r,x:c.x+r.x,y:c.y+r.y})
 const fact=(value:string|number|null|undefined,rect:SurfRect|null,maxFont=17,bold=false)=>{if(value==null||!rect)return null;const r=absolute(rect),fitted=fitSurfFact(value,r.width-10,r.height-3,(text,size)=>{ctx.font=`${bold?'bold ':''}${size}px sans-serif`;return ctx.measureText(text).width},{maxFont,minFont:9});if(!fitted)return null;ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.width,r.height);ctx.clip();centered(ctx,fitted.text,r.x,r.y+r.height/2+fitted.fontSize*.35,r.width,`${bold?'bold ':''}${fitted.fontSize}px sans-serif`);ctx.restore();return fitted}
 if(!composition.available&&layout.emptyRect){fact('No surf forecast',layout.emptyRect,15);return}
 if(layout.headerRect&&state.spot){const r=absolute(layout.headerRect),fitted=fitSurfFact(state.spot.toUpperCase(),r.width-8,r.height-9,(text,size)=>{ctx.font=`bold ${size}px sans-serif`;return ctx.measureText(text).width},{maxFont:17,minFont:9});if(fitted){ctx.font=`bold ${fitted.fontSize}px sans-serif`;const measured=Math.min(ctx.measureText(fitted.text).width,r.width-8),baseline=r.y+fitted.fontSize+2;centered(ctx,fitted.text,r.x,baseline,r.width,`bold ${fitted.fontSize}px sans-serif`);ctx.fillRect(r.x+(r.width-measured)/2,baseline+5,measured,2)}}
 if(layout.ratingRect&&state.rating.score!=null)fact(surfRatingWord(state.rating.score),layout.ratingRect,Math.min(34,layout.ratingRect.height*.7),true)
 if(layout.ratingBlocksRect&&state.rating.score!=null){const r=absolute(layout.ratingBlocksRect),blockWidth=Math.min(r.width-18,Math.max(68,r.width*.65)),experience=Boolean(state.ratingFromExperience||state.rating.experienceBased);adaptiveSurfRatingVisual(ctx,r.x+(r.width-blockWidth)/2,r.y+r.height/2-4,blockWidth,state.rating.score,experience)}
 fact(state.waveHeight,layout.waveRect,20,true)
 if(layout.detailsRect){const r=layout.detailsRect,values=[composition.showPeriod?state.period:null,composition.showWind?state.windSpeed:null,composition.showDirections&&state.swellDirection?`Swell ${state.swellDirection}`:null,composition.showDirections&&state.windDirection?`Wind ${state.windDirection}`:null].filter((v):v is string=>Boolean(v)),rowH=r.height/Math.max(1,values.length);values.forEach((value,index)=>{const rr={x:r.x,y:r.y+index*rowH,width:r.width,height:rowH};if(composition.showDirections&&/^(Swell|Wind) /.test(value)&&r.width>=115){const ar=absolute(rr);arrowIcon(ctx,ar.x+9,ar.y+Math.max(4,(ar.height-18)/2),18,value.startsWith('Wind'));fact(value,{...rr,x:rr.x+28,width:rr.width-28},15)}else fact(value,rr,15,index<2)})}
 if(layout.bestWindowRect&&composition.showTodaysBestLabel)fact(composition.todaysBestLabelMode==='spacious'?'Best next 4hrs':"Today's Best",layout.bestWindowRect,12,true)
 if(layout.environmentRect){const values=[state.airTemperature&&`Air ${state.airTemperature}`,state.waterTemperature&&`Water ${state.waterTemperature}`,state.sunrise&&state.sunset&&`Sun ${state.sunrise} / ${state.sunset}`].filter((v):v is string=>Boolean(v)),r=layout.environmentRect,rowH=r.height/Math.max(1,values.length);values.forEach((value,index)=>fact(value,{x:r.x,y:r.y+index*rowH,width:r.width,height:rowH},12))}
 const renderForecastColumns=(columns:typeof layout.daypartColumns,entries:readonly SurfForecast[])=>columns.forEach((column,index)=>{const entry=entries[index];if(!entry)return;const r=absolute(column.columnRect);if(index)line(ctx,r.x,r.y+5,r.x,r.y+r.height-5);fact(entry.day,column.dayRect,13,true);fact(surfRatingWord(entry.ratingScore),column.ratingRect,13,true);const blocks=absolute(column.blocksRect),bw=Math.min(90,blocks.width-18),experience=Boolean(entry.ratingFromExperience||entry.experienceDiceValue);adaptiveSurfRatingVisual(ctx,blocks.x+(blocks.width-bw)/2,blocks.y+blocks.height/2-4,bw,entry.ratingScore,experience);fact(entry.waveHeight,column.waveRect,13,true);if(column.periodRect)fact(entry.period,column.periodRect,11)})
 const dayparts=state.dayparts??[],daily=state.daily??state.forecast??[]
 renderForecastColumns(layout.daypartColumns,dayparts.slice(0,composition.daypartCount))
 renderForecastColumns(layout.dailyColumns,daily.slice(0,composition.dailyCount))
}
function drawSurf(ctx:CanvasRenderingContext2D,c:PixelCell,d:string[]){
 if(c.size==='SMALL'){const y=c.y+28;underlinedHeading(ctx,d[0],c,y);centered(ctx,d[1],c.x+8,c.y+c.h-22,c.w*.22,'bold 14px sans-serif');ratingBlocks(ctx,c.x+c.w*.25,c.y+c.h-39,134,4);centered(ctx,d[2],c.x+c.w*.62,c.y+c.h-22,c.w*.36,'bold 14px sans-serif');return}
 if(c.size==='MEDIUM'){underlinedHeading(ctx,d[0],c,c.y+31);const half=c.w/2;line(ctx,c.x+half,c.y+54,c.x+half,c.y+c.h-18);centered(ctx,d[1],c.x,c.y+82,half,'bold 17px sans-serif');ratingBlocks(ctx,c.x+half/2-67,c.y+95,134);centered(ctx,d[2],c.x,c.y+148,half,'bold 18px sans-serif');arrowIcon(ctx,c.x+half+32,c.y+82,22);centered(ctx,'Swell W',c.x+half+55,c.y+94,half-55,'13px sans-serif');arrowIcon(ctx,c.x+half+32,c.y+120,22,true);centered(ctx,'Wind N',c.x+half+55,c.y+136,half-55,'13px sans-serif');metricIcon(ctx,c.x+half+28,c.y+154,'wave');centered(ctx,d[3],c.x+half+55,c.y+169,half-55,'13px sans-serif');metricIcon(ctx,c.x+half+28,c.y+185,'wind');centered(ctx,'5 m/s',c.x+half+55,c.y+200,half-55,'13px sans-serif');return}
 if(c.size==='LARGE'){underlinedHeading(ctx,d[0],c,c.y+31);const top=c.y+58,colW=c.w/4,labels=moduleProfiles.surf.large.labels;for(let i=0;i<4;i++){const score=Math.max(1,4-i);if(i)line(ctx,c.x+i*colW,top+5,c.x+i*colW,c.y+c.h-18);centered(ctx,labels[i],c.x+i*colW,top+20,colW,'bold 13px sans-serif');centered(ctx,surfRatingWord(score)!.toUpperCase(),c.x+i*colW,top+48,colW,'bold 14px sans-serif');ratingBlocks(ctx,c.x+i*colW+colW/2-55,top+58,110,score);centered(ctx,d[2],c.x+i*colW,c.y+c.h-25,colW,'14px sans-serif')}return}
 const mid=c.y+c.h*moduleProfiles.surf.xl.splitRatio,third=c.w/moduleProfiles.surf.xl.topRegions;centered(ctx,`${d[0]} · TODAY'S BEST`,c.x,c.y+20,c.w,'bold 12px sans-serif');line(ctx,c.x+c.w*.025,mid,c.x+c.w*.975,mid);for(let i=1;i<3;i++)line(ctx,c.x+i*third,c.y+32,c.x+i*third,mid-14);arrowIcon(ctx,c.x+42,c.y+64,24);centered(ctx,'Swell W',c.x+70,c.y+77,third-70,'13px sans-serif');arrowIcon(ctx,c.x+42,c.y+104,24,true);centered(ctx,'Wind N',c.x+70,c.y+119,third-70,'13px sans-serif');metricIcon(ctx,c.x+42,c.y+138,'wave');metricIcon(ctx,c.x+42,c.y+174,'wind');centered(ctx,'12 s     5 m/s',c.x+72,c.y+188,third-72,'13px sans-serif');centered(ctx,'TODAY',c.x+third,c.y+62,third,'bold 14px sans-serif');centered(ctx,surfRatingWord(4)!.toUpperCase(),c.x+third,c.y+92,third,'bold 18px sans-serif');ratingBlocks(ctx,c.x+third+third/2-67,c.y+108,134,4);centered(ctx,d[2],c.x+third,c.y+164,third,'bold 17px sans-serif');metricIcon(ctx,c.x+third*2+38,c.y+66,'sun');metricIcon(ctx,c.x+third*2+38,c.y+108,'drop');metricIcon(ctx,c.x+third*2+38,c.y+150,'sun');['Air 12° / 19°','Water 14° / 16°','Sun 06:01 / 20:32'].forEach((v,i)=>centered(ctx,v,c.x+third*2+62,c.y+80+i*42,third-62,'12px sans-serif'));const w=c.w/moduleProfiles.surf.xl.forecastColumns;for(let i=0;i<moduleProfiles.surf.xl.forecastColumns;i++){const score=Math.max(1,4-i);if(i)line(ctx,c.x+i*w,mid+18,c.x+i*w,c.y+c.h-16);centered(ctx,['Thu','Fri','Sat','Sun'][i],c.x+i*w,mid+34,w,'bold 13px sans-serif');centered(ctx,surfRatingWord(score)!.toUpperCase(),c.x+i*w,mid+64,w,'bold 13px sans-serif');ratingBlocks(ctx,c.x+i*w+w/2-45,mid+76,90,score);centered(ctx,d[2],c.x+i*w,c.y+c.h-25,w,'13px sans-serif')}
}
function drawResponsiveSoccer(ctx:CanvasRenderingContext2D,c:PixelCell,p:ResponsiveCellProfile,state:SoccerState){
  const composition=soccerComposition(p,state),layout=soccerLayout(p,composition),absolute=(r:SoccerRect|null)=>r&&({x:c.x+r.x,y:c.y+r.y,width:r.width,height:r.height})
  if(!composition.available){centered(ctx,'No fixtures',c.x,c.y+c.h/2+5,c.w,'14px sans-serif');return}
  const fact=(value:string|number|null|undefined,r:SoccerRect|null,max=18,min=9,bold=true)=>{if(!r)return false;const a=absolute(r)!;const fitted=fitSoccerFact(value,a.width-4,a.height,(text,size)=>{ctx.font=`${bold?'bold ':''}${size}px sans-serif`;return ctx.measureText(text).width},{maxFont:max,minFont:min});if(!fitted)return false;ctx.font=`${bold?'bold ':''}${fitted.fontSize}px sans-serif`;ctx.textAlign='center';ctx.fillText(fitted.text,a.x+a.width/2,a.y+(a.height+fitted.fontSize*.72)/2);return true}
  const fixture=composition.primaryState==='next'?state.nextFixture:state.previousFixture
  if(fixture&&layout.teamsRect){const r=absolute(layout.teamsRect)!,score=fixture.homeScore!=null&&fixture.awayScore!=null?`${fixture.homeScore} - ${fixture.awayScore}`:null;const labels=soccerFixtureTeamLabels(fixture,r.width-8,(text,size)=>{ctx.font=`bold ${size}px sans-serif`;return ctx.measureText(text).width},Math.min(18,r.height*.28))!;const inline=`${labels.home} vs ${labels.away}`;if(score&&composition.primaryState==='previous'){fact('LAST',{...layout.teamsRect,height:18},11,9);fact(`${labels.home} ${fixture.homeScore} - ${fixture.awayScore} ${labels.away}`,{...layout.teamsRect,y:layout.teamsRect.y+19,height:layout.teamsRect.height-19},20,10)}else fact(inline,layout.teamsRect,composition.family==='micro'?20:18,10)}
  if(composition.primaryState==='next'&&state.nextFixture&&layout.kickoffRect){const day=state.nextFixture.kickoffDay,time=state.nextFixture.kickoffTime;fact([day&&(layout.kickoffRect.width<150?({Monday:'Mon',Tuesday:'Tue',Wednesday:'Wed',Thursday:'Thu',Friday:'Fri',Saturday:'Sat',Sunday:'Sun'} as Record<string,string>)[day]||day:day),time].filter(Boolean).join(' '),layout.kickoffRect,14,9,false)}
  if(composition.primaryState==='standing'&&state.teamName)fact(soccerTeamAbbreviation(state.teamName),layout.teamsRect,22,11)
  if(composition.showStanding&&layout.standingRect){const bits=[state.position!=null&&`${layout.standingRect.width<210?'Pos':'Position'} ${state.position}`,state.points!=null&&`${state.points} ${layout.standingRect.width<210?'pts':'points'}`].filter(Boolean);fact(bits.join('  |  '),layout.standingRect,13,9,false)}
  if(layout.dividerX){const x=c.x+layout.dividerX,top=c.y+Math.min(layout.primaryRect!.y,layout.detailsRect?.y??layout.previousRect?.y??layout.primaryRect!.y),bottom=c.y+Math.max(layout.primaryRect!.y+layout.primaryRect!.height,(layout.detailsRect??layout.previousRect)!.y+(layout.detailsRect??layout.previousRect)!.height);line(ctx,x,top+8,x,bottom-8)}
  if(composition.showPrevious&&state.previousFixture&&layout.previousGroupRect){const previous=state.previousFixture,r=layout.previousGroupRect,labels=soccerFixtureTeamLabels(previous,r.width-8,(text,size)=>{ctx.font=`bold ${size}px sans-serif`;return ctx.measureText(text).width},13)!;const score=previous.homeScore!=null&&previous.awayScore!=null?`${previous.homeScore} - ${previous.awayScore}`:null;fact('LAST',{...r,height:20},11,9);fact(`${labels.home} vs ${labels.away}`,{...r,y:r.y+21,height:25},13,9);if(score)fact(score,{...r,y:r.y+47,height:r.height-47},20,10)}
  const standingsRect=absolute(layout.standingsRect);if(composition.showTable&&standingsRect){const rows=soccerTableWindow(state.table,composition.tableRows),columns=composition.tableColumns;const widths=columns.map(col=>col==='Team'?Math.max(70,standingsRect.width-(columns.length-1)*40):40),total=widths.reduce((a,b)=>a+b,0),scale=standingsRect.width/total;let x=standingsRect.x;columns.forEach((col,i)=>{const w=widths[i]*scale;centered(ctx,col,x,standingsRect.y+16,w,'bold 10px sans-serif');x+=w});rows.forEach((row,i)=>{const rr=absolute(layout.rowRects[i])!;if(row.selected){line(ctx,rr.x+3,rr.y+1,rr.x+rr.width-3,rr.y+1);line(ctx,rr.x+3,rr.y+rr.height-2,rr.x+rr.width-3,rr.y+rr.height-2)}let rx=rr.x;columns.forEach((col,j)=>{const w=widths[j]*scale,value=col==='P'?row.position:col==='Team'?soccerTeamAbbreviation(row.team):col==='Pts'?row.points:col==='Gap'?(row.gap==null?'—':row.gap):row.goalDifference;fact(value,{x:rx-c.x,y:rr.y-c.y,width:w,height:rr.height},11,8,col==='Team'&&Boolean(row.selected));rx+=w})})}
  if(composition.showDetails&&layout.detailsGroupRect){const details=[state.competitionName,state.record&&`W${state.record.won} D${state.record.drawn} L${state.record.lost}`,state.form&&`Form ${state.form}`,state.topScorer&&`${state.topScorer.name} · ${state.topScorer.goals} goals`].filter(Boolean) as string[];details.forEach((value,i)=>fact(value,layout.detailRowRects[i]??null,12,9,false))}
}
function soccerFixture(ctx:CanvasRenderingContext2D,x:number,y:number,w:number){centered(ctx,'ARS   vs   LIV',x,y,w,'bold 18px sans-serif')}
function soccerPanel(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number){const rows=['Sun 16:30','ARS  vs  LIV','Position 1   |   Points 68','','LAST','ARS  vs  CHE','2  –  1'],rh=h/8;rows.forEach((v,i)=>{if(i===3)line(ctx,x+w*.05,y+(i+1)*rh,x+w*.95,y+(i+1)*rh);else centered(ctx,v,x,y+(i+1)*rh,w,i===4?'bold 12px sans-serif':'14px sans-serif')})}
function standings(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,rows:number){const top=y+28,rowH=Math.max(17,(h-38)/(rows+1));centered(ctx,'P   TEAM    PTS   GAP   GD',x,top,w,'bold 11px monospace');for(let i=0;i<rows;i++){const ry=top+(i+1)*rowH;if(i===0){line(ctx,x+8,ry-rowH*.7,x+w-8,ry-rowH*.7);line(ctx,x+8,ry+rowH*.3,x+w-8,ry+rowH*.3)}centered(ctx,`${i+1}   ${['ARS','LIV','MCI','CHE'][i%4]}      ${68-i*3}    ${i?i*3:'—'}   +${20-i}`,x,ry,w,'11px monospace')}}
function drawSoccer(ctx:CanvasRenderingContext2D,c:PixelCell,d:string[]){if(c.size==='SMALL'){soccerFixture(ctx,c.x,c.y+38,c.w);const y=c.y+c.h-36,w=c.w/3;['Sun 16:30','Position 1','Points 68'].forEach((v,i)=>{if(i)line(ctx,c.x+i*w,y-14,c.x+i*w,c.y+c.h-8);centered(ctx,v,c.x+i*w,y+8,w,'12px sans-serif')});return}if(c.size==='MEDIUM'){soccerPanel(ctx,c.x,c.y,c.w,c.h);return}const half=c.w*moduleProfiles.soccer.large.panelRatio;if(c.size==='LARGE'){soccerPanel(ctx,c.x,c.y,half,c.h);standings(ctx,c.x+half,c.y,c.w-half,c.h,moduleProfiles.soccer.large.standingsRows);return}centered(ctx,'ARSENAL',c.x,c.y+28,half,'bold 18px sans-serif');soccerPanel(ctx,c.x,c.y+30,half,c.h*.55);['League · Premier League','Top scorer · Alex · 18','Record · W20 D8 L4','Goals 68 · Form W W D W'].forEach((v,i)=>centered(ctx,v,c.x,c.y+c.h*.65+i*28,half,'12px sans-serif'));standings(ctx,c.x+half,c.y,c.w-half,c.h,moduleProfiles.soccer.xl.standingsRows)}
function stockStats(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,values:string[]){['Open 123.10','High 126.20','Low 121.80','Prev 121.60','Change +2.90','Range +8.4%'].forEach((v,i)=>centered(ctx,v,x,y+i*25,w,'13px sans-serif'))}
function stockSummary(ctx:CanvasRenderingContext2D,c:PixelCell,d:string[],bottomY:number){underlinedHeading(ctx,d[0],c,c.y+34);const rowX=c.x+24,rowW=c.w-48,colW=rowW/3;[d[1],d[2],'+8.4%'].forEach((v,i)=>{if(i)line(ctx,rowX+i*colW,bottomY-19,rowX+i*colW,bottomY+3);centered(ctx,v,rowX+i*colW,bottomY,colW,'bold 14px sans-serif')})}
function drawResponsiveStocks(ctx:CanvasRenderingContext2D,c:PixelCell,p:ResponsiveCellProfile,state:StocksState){
  const composition=stocksComposition(p,state),layout=stocksLayout(p,composition),absolute=(r:StockRect|null)=>r&&({...r,x:c.x+r.x,y:c.y+r.y})
  const fact=(value:string|null,local:StockRect|null,max=20,bold=true)=>{if(!value||!local)return false;const r=absolute(local)!,fitted=fitStockFact(value,r.width-6,r.height-2,(text,size)=>{ctx.font=`${bold?'bold ':''}${size}px sans-serif`;return ctx.measureText(text).width},{maxFont:max,minFont:8});if(!fitted)return false;centered(ctx,fitted.text,r.x,r.y+(r.height+fitted.fontSize*.7)/2,r.width,`${bold?'bold ':''}${fitted.fontSize}px sans-serif`);return true}
  if(!composition.available){fact('No stock',layout.emptyRect,15,false);return}
  const title=state.name||state.symbol
  if(title&&layout.titleRect){const r=absolute(layout.titleRect)!,max=composition.family==='detail-chart'?17:15;let size=max,text=title;for(;size>=9;size--){ctx.font=`bold ${size}px sans-serif`;if(ctx.measureText(text).width<=r.width-4)break}if(size<9){size=9;ctx.font='bold 9px sans-serif';let end=text.length;while(end&&ctx.measureText(`${text.slice(0,end).trimEnd()}…`).width>r.width-4)end--;text=end?`${text.slice(0,end).trimEnd()}…`:''}if(text){centered(ctx,text,r.x,r.y+size+1,r.width,`bold ${size}px sans-serif`);const underline=Math.min(r.width-4,ctx.measureText(text).width);ctx.fillRect(r.x+(r.width-underline)/2,r.y+size+6,underline,2)}}
  fact(formatStockPrice(state.price),layout.priceRect,composition.family==='micro'?34:30)
  fact(formatStockSigned(state.changePercent,{percent:true}),layout.dayChangeRect,15)
  const rangeChange=formatStockSigned(state.selectedRangePercent,{percent:true});fact(rangeChange?`${STOCK_RANGE_LABELS[state.selectedRange]} ${rangeChange}`:null,layout.rangeChangeRect,13,false)
  const labels:Record<string,string>={open:'Open',high:'High',low:'Low',previousClose:'Prev close',change:'Change'}
  composition.detailKeys.forEach((key,index)=>{const value=key==='change'?formatStockSigned(state.change):formatStockPrice(state[key as keyof StocksState] as number),r=layout.detailRowRects[index];if(value&&r)fact(`${labels[key]}  ${value}`,r,12,false)})
  if(layout.rangeSelectorRect){const r=absolute(layout.rangeSelectorRect)!,itemW=r.width/4;STOCK_RANGES.forEach((range,index)=>{ctx.save();const x=r.x+index*itemW,label=STOCK_RANGE_LABELS[range];if(range===state.selectedRange){ctx.fillStyle='#fff';ctx.fillRect(x+3,r.y+3,itemW-6,r.height-6);ctx.fillStyle='#000'}centered(ctx,label,x,r.y+r.height/2+4,itemW,`${range===state.selectedRange?'bold ':''}11px sans-serif`);ctx.restore()})}
  if(layout.chartRect){const r=absolute(layout.chartRect)!,values=state.series,min=Math.min(...values),max=Math.max(...values),span=max-min||1,baseline=stockReferenceLine(state);ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.width,r.height);ctx.clip();if(baseline!=null){const y=r.y+r.height-((baseline-min)/span)*r.height;ctx.setLineDash([3,5]);line(ctx,r.x,y,r.x+r.width,y);ctx.setLineDash([])}ctx.lineWidth=2;ctx.beginPath();values.forEach((value,index)=>{const x=r.x+index*r.width/(values.length-1),y=r.y+r.height-((value-min)/span)*(r.height-2)-1;index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.lineWidth=1;ctx.restore()}
}
function drawResponsiveGroceries(ctx:CanvasRenderingContext2D,c:PixelCell,p:ResponsiveCellProfile,state:GroceriesState){
  const composition=groceriesComposition(p,state),layout=groceriesLayout(p,composition,state),absolute=(value:GroceryRect)=>({...value,x:c.x+value.x,y:c.y+value.y})
  const measure=(font:string)=>(text:string)=>{ctx.font=font;return ctx.measureText(text).width}
  const drawText=(text:string,rect:GroceryRect,font='14px sans-serif',align:CanvasTextAlign='left')=>{const r=absolute(rect);ctx.font=font;ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.width,r.height);ctx.clip();ctx.textAlign=align;ctx.fillText(text,align==='center'?r.x+r.width/2:r.x,r.y+Math.min(r.height-3,15));ctx.restore()}
  const fitted=(text:string,rect:GroceryRect,font='14px sans-serif',align:CanvasTextAlign='left')=>drawText(fitGroceriesText(text,rect.width,(value)=>measure(font)(value)).text,rect,font,align)
  const heading=(text:string,rect:GroceryRect|null)=>{if(!rect)return;const r=absolute(rect),font='bold 15px sans-serif',rendered=fitGroceriesText(text,rect.width,measure(font));drawText(rendered.text,rect,font,'center');ctx.font=font;const width=ctx.measureText(rendered.text).width;ctx.fillRect(r.x+(r.width-width)/2,r.y+r.height-3,width,2)}
  if(layout.emptyRect){heading(state.header,layout.headerRect);const r=absolute(layout.emptyRect);centered(ctx,composition.failed?'Fetch failed':state.emptyPhrase,r.x,r.y+r.height/2+8,r.width,'14px sans-serif');return}
  if(layout.todayLabelRect)fitted("TODAY'S DINNER",layout.todayLabelRect,'bold 10px sans-serif','center')
  heading(layout.groceryHeading,layout.titleRect)
  layout.groceryRows.forEach(row=>{const itemRect=absolute(row.itemRect);if(composition.horizontal){const fit=fitGroceryText(row.item,row.itemRect.width-10,(text,size)=>{ctx.font=`bold ${size}px sans-serif`;return ctx.measureText(text).width},{fontSize:14});if(fit)fitted(fit.text,row.itemRect,'bold 14px sans-serif','center');return}ctx.beginPath();ctx.arc(itemRect.x+5,itemRect.y+itemRect.height/2,3,0,Math.PI*2);ctx.fill();if(row.quantityRect)fitted(`${row.item.quantity}x`,row.quantityRect,'bold 13px sans-serif');if(row.nameRect){const fit=fitGroceryText({...row.item,quantity:1},row.nameRect.width,(text,size)=>{ctx.font=`${size}px sans-serif`;return ctx.measureText(text).width},{fontSize:13});if(fit)fitted(fit.name,row.nameRect,'13px sans-serif')}})
  if(!layout.groceryRows.length&&layout.groceryRect)fitted(state.emptyPhrase,{...layout.groceryRect,y:layout.headerRect!.y+layout.headerRect!.height+8,height:24},'13px sans-serif','center')
  if(layout.overflowRect){const r=absolute(layout.overflowRect),remaining=state.items.length-layout.groceryRows.length;fitted(r.width<70?`+${remaining}`:`+${remaining} more`,layout.overflowRect,'bold 12px sans-serif','center')}
  if(layout.menuHeaderRect&&layout.menuHeading)heading(layout.menuHeading,layout.menuHeaderRect)
  layout.menuRows.forEach(row=>{const r=absolute(row.rect);ctx.font='bold 12px sans-serif';ctx.textAlign='left';ctx.fillText(`${row.dinner.dayLabel}:`,r.x,r.y+15);const dayWidth=ctx.measureText(`${row.dinner.dayLabel}: `).width;fitted(row.dinner.title,{...row.rect,x:row.rect.x+dayWidth,width:row.rect.width-dayWidth},'13px sans-serif')})
  if(layout.runningLowRect)heading('RUNNING LOW',{...layout.runningLowRect,height:25})
  layout.runningLowRows.forEach(row=>drawText(fitRunningLowText(row.item,row.rect.width,(value)=>measure('13px sans-serif')(value)).text,row.rect,'13px sans-serif'))
  if(layout.mealIdeasRect)heading('MEAL IDEAS',{...layout.mealIdeasRect,height:25})
  layout.mealIdeaGroups.forEach(group=>drawText(fitMealIdeaText(group.idea,group.rect.width,(value)=>measure('13px sans-serif')(value)).text,group.rect,'13px sans-serif'))
  layout.dividers.forEach(value=>line(ctx,c.x+value.x1,c.y+value.y1,c.x+value.x2,c.y+value.y2))
}
function drawResponsiveAiFollow(ctx:CanvasRenderingContext2D,c:PixelCell,p:ResponsiveCellProfile,state:AiFollowState){
  const composition=aiFollowComposition(p,state),layout=aiFollowLayout(p,composition),absolute=(r:AiFollowRect)=>({...r,x:c.x+r.x,y:c.y+r.y}),measure=(text:string,size:number)=>{ctx.font=`${size}px sans-serif`;return ctx.measureText(text).width}
  const draw=(text:string,local:AiFollowRect,font:string,align:CanvasTextAlign='left')=>{const r=absolute(local);ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.width,r.height);ctx.clip();ctx.font=font;ctx.textAlign=align;const size=Number(font.match(/(\d+)px/)?.[1]??13);ctx.fillText(text,align==='center'?r.x+r.width/2:r.x,r.y+Math.min(r.height-2,size*.9));ctx.restore()}
  const header=absolute(layout.headerRect),headerFont='bold 15px sans-serif';ctx.font=headerFont;const heading='AI FOLLOW',headingWidth=Math.min(header.width,ctx.measureText(heading).width);draw(heading,layout.headerRect,headerFont,'center');if(c.h>=135)ctx.fillRect(header.x+(header.width-headingWidth)/2,header.y+21,headingWidth,2)
  if(composition.mode!=='updates'){if(layout.quietPrimaryRect)draw(composition.mode==='zero-follow'?'Nothing followed yet':'No new updates',layout.quietPrimaryRect,'bold 14px sans-serif','center');if(layout.quietSecondaryRect)draw(composition.mode==='zero-follow'?'Follow topics in the app':`Following ${state.followingCount} ${state.followingCount===1?'topic':'topics'}`,layout.quietSecondaryRect,'12px sans-serif','center');return}
  for(const group of layout.updateGroups){const topic=fitAiFollowTitle(group.update.topicTitle,group.topicRect.width,measure,{fontSize:14});draw(topic.text,group.topicRect,'bold 14px sans-serif');const wrapped=wrapAiFollowSummary(group.update.summary,group.summaryRect.width,composition.summaryLines,measure,{fontSize:13});wrapped.lines.forEach((value,index)=>draw(value,{...group.summaryRect,y:group.summaryRect.y+index*16,height:16},'13px sans-serif'))}
  if(layout.overflowRect){const label=layout.overflowRect.width<75?`+${layout.overflow}`:`+${layout.overflow} more`;draw(label,layout.overflowRect,'bold 12px sans-serif','right')}
}
function drawStocks(ctx:CanvasRenderingContext2D,c:PixelCell,d:string[]){if(c.size==='SMALL'){stockSummary(ctx,c,d,c.y+c.h-22);return}if(c.size==='MEDIUM'){stockSummary(ctx,c,d,c.y+c.h-22);centered(ctx,d[3],c.x,c.y+75,c.w,'12px sans-serif');drawSparkline(ctx,c.x+32,c.y+90,c.w-64,c.h-145);return}if(c.size==='LARGE'){const half=c.w/2;underlinedHeading(ctx,d[0],{...c,w:half},c.y+34);stockStats(ctx,c.x,c.y+74,half,d);centered(ctx,d[3],c.x+half,c.y+35,half,'bold 13px sans-serif');drawSparkline(ctx,c.x+half+20,c.y+55,half-40,c.h-82);return}underlinedHeading(ctx,d[0],c,c.y+27);const rowX=c.x+20,rowW=c.w-40,colW=rowW/moduleProfiles.stocks.xl.headlineValues;[d[1],'+2.90',d[2]].forEach((v,i)=>{if(i)line(ctx,rowX+i*colW,c.y+48,rowX+i*colW,c.y+110);centered(ctx,v,rowX+i*colW,c.y+87,colW,'bold 20px sans-serif')});[['High 126.20','Low 121.80'],['Open 123.10','Prev 121.60'],['Change +2.90','Day +2.4%']].forEach((pair,i)=>pair.forEach((v,j)=>centered(ctx,v,rowX+i*colW,c.y+137+j*25,colW,'12px sans-serif')));const mid=c.y+c.h*.52;centered(ctx,'Day   Week   Month   Year',c.x,mid+18,c.w,'bold 12px sans-serif');drawSparkline(ctx,c.x+24,mid+31,c.w-48,c.y+c.h-mid-50)}
function groceryHeader(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,w:number){centered(ctx,text,x,y,w,'bold 17px sans-serif');ctx.fillRect(x+w*.3,y+5,w*.4,2)}
function groceryList(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,items:string[],count:number,columns=1){const per=Math.ceil(count/columns),colW=w/columns;for(let i=0;i<count;i++){const col=Math.trunc(i/per),row=i%per,py=y+row*25;ctx.beginPath();ctx.arc(x+col*colW+18,py-4,3,0,Math.PI*2);ctx.fill();clippedCentered(ctx,items[i%items.length]||'Grocery item',x+col*colW+30,py,w/columns-42)}}
function drawGroceries(ctx:CanvasRenderingContext2D,c:PixelCell,d:string[]){const dinner=d[4]==='todayDinner',items=d.slice(1,4);if(c.size==='SMALL'){groceryHeader(ctx,d[0],c.x,c.y+34,c.w);const count=moduleProfiles.groceries.small.itemRegions,colW=c.w/count;for(let i=1;i<count;i++)line(ctx,c.x+i*colW,c.y+moduleProfiles.groceries.small.headerRegion,c.x+i*colW,c.y+c.h-12);for(let i=0;i<count;i++)clippedCentered(ctx,items[i],c.x+i*colW+8,c.y+c.h-24,colW-16);return}if(c.size==='MEDIUM'){if(dinner)centered(ctx,"TODAY'S DINNER",c.x,c.y+18,c.w,'11px sans-serif');groceryHeader(ctx,d[0],c.x,c.y+(dinner?43:35),c.w);groceryList(ctx,c.x+12,c.y+(dinner?82:76),c.w-24,items,12,moduleProfiles.groceries.medium.listColumns);return}const half=c.w*moduleProfiles.groceries.large.panelRatio;if(c.size==='LARGE'){groceryHeader(ctx,'Grocery List',c.x,c.y+35,half);groceryList(ctx,c.x+12,c.y+76,half-24,items,12,2);groceryHeader(ctx,'Weekly Menu',c.x+half,c.y+35,c.w-half);groceryList(ctx,c.x+half+12,c.y+76,half-24,['Mon · Tacos','Tue · Pasta','Wed · Soup'],7);return}const mid=c.y+c.h*moduleProfiles.groceries.xl.splitRatio;groceryHeader(ctx,'Grocery List',c.x,c.y+35,half);groceryList(ctx,c.x+12,c.y+76,half-24,items,12,2);groceryHeader(ctx,'Weekly Menu',c.x+half,c.y+35,half);groceryList(ctx,c.x+half+12,c.y+76,half-24,['Today · Tacos','Tue · Pasta','Wed · Soup'],7);line(ctx,c.x+10,mid,c.x+c.w-10,mid);groceryHeader(ctx,'Running Low',c.x,mid+36,half);groceryList(ctx,c.x+12,mid+74,half-24,['Coffee','Rice','Soap'],3);groceryHeader(ctx,'Meal Ideas',c.x+half,mid+36,c.w-half);groceryList(ctx,c.x+half+12,mid+74,half-24,['Tacos · missing salsa','Curry · missing rice'],2)}
function drawModule(ctx:CanvasRenderingContext2D,c:PixelCell,m:StudioModuleName,p:Preset,ink:string){ctx.save();ctx.beginPath();ctx.rect(c.x,c.y,c.w,c.h);ctx.clip();ctx.fillStyle=ink;ctx.strokeStyle=ink;ctx.lineWidth=1;const strategy=studioRenderStrategy(m,c.colSpan,c.rowSpan,c.w,c.h);if(m==='assistant'){drawResponsiveAiFollow(ctx,c,strategy.profile,aiFollowStudioPresets[p]);ctx.restore();return}const legacyModule:LegacyModuleName=m;const d=fake[legacyModule][p];if(strategy.path==='reminders-responsive'){drawResponsiveReminders(ctx,c,strategy.profile,reminderStudioPresets[p]);ctx.restore();return}if(strategy.path==='weather-responsive'){drawResponsiveWeather(ctx,c,strategy.profile,weatherStudioPresets[p]);ctx.restore();return}if(strategy.path==='countdown-responsive'){drawResponsiveCountdown(ctx,c,strategy.profile,countdownStudioPresets[p]);ctx.restore();return}if(strategy.path==='date-responsive'){drawResponsiveDate(ctx,c,strategy.profile,dateStudioPresets[p]);ctx.restore();return}if(strategy.path==='surf-responsive'){drawResponsiveSurf(ctx,c,strategy.profile,surfStudioPresets[p]);ctx.restore();return}if(strategy.path==='soccer-responsive'){drawResponsiveSoccer(ctx,c,strategy.profile,soccerStudioPresets[p]);ctx.restore();return}if(strategy.path==='stocks-responsive'){drawResponsiveStocks(ctx,c,strategy.profile,stocksStudioPresets[p]);ctx.restore();return}if(strategy.path==='groceries-responsive'){drawResponsiveGroceries(ctx,c,strategy.profile,groceriesStudioPresets[p]);ctx.restore();return}if(strategy.path==='responsive'){drawResponsive(ctx,c,legacyModule,d,strategy.profile);ctx.restore();return}if(legacyModule==='date')drawDate(ctx,c,d,p);if(legacyModule==='reminders')drawReminders(ctx,c,d,p);if(legacyModule==='weather')drawWeather(ctx,c,d);if(legacyModule==='countdown')drawCountdown(ctx,c,d,p);if(legacyModule==='surf')drawSurf(ctx,c,d);if(legacyModule==='soccer')drawSoccer(ctx,c,d);if(legacyModule==='stocks')drawStocks(ctx,c,d);if(legacyModule==='groceries')drawGroceries(ctx,c,d);ctx.restore()}

const geometrySize=(cell:Pick<EditorCell,'colSpan'|'rowSpan'>):PixelCell['size']|null=>legacyStudioVariant(cell.colSpan,cell.rowSpan)
const editorPixelCell=(cell:EditorCell,slot:number):PixelCell=>resolveGridCell({...cell,slot,size:geometrySize(cell)??'XL'} as GridCell)
const productionAssignments:Record<LayoutName,ModuleName[]>={full:['date'],default:['date','reminders','weather'],pyramid:['date','reminders','weather','countdown'],square:['date','reminders','weather','countdown']}

function drawSnapGrid(ctx:CanvasRenderingContext2D,emphasized:SplitGuide|null){
  ctx.save();ctx.strokeStyle='rgba(22,135,255,.18)';ctx.lineWidth=1;ctx.setLineDash([2,6])
  for(let boundary=1;boundary<4;boundary++){line(ctx,gridX(boundary),gridY(0),gridX(boundary),gridY(4));line(ctx,gridX(0),gridY(boundary),gridX(4),gridY(boundary))}
  if(emphasized){ctx.strokeStyle='rgba(22,135,255,.48)';ctx.lineWidth=2;emphasized.axis==='vertical'?line(ctx,gridX(emphasized.boundary),gridY(0),gridX(emphasized.boundary),gridY(4)):line(ctx,gridX(0),gridY(emphasized.boundary),gridX(4),gridY(emphasized.boundary))}
  ctx.restore()
}
function drawDividerHighlight(ctx:CanvasRenderingContext2D,divider:DividerHit){
  const draw=()=>divider.axis==='vertical'?line(ctx,gridX(divider.boundary),gridY(divider.from),gridX(divider.boundary),gridY(divider.to)):line(ctx,gridX(divider.from),gridY(divider.boundary),gridX(divider.to),gridY(divider.boundary))
  ctx.strokeStyle='rgba(220,48,48,.24)';ctx.lineWidth=9;draw();ctx.strokeStyle='#dc3030';ctx.lineWidth=3;draw();ctx.lineWidth=1
}
function drawSelection(ctx:CanvasRenderingContext2D,selection:GridSelection){
  if(selection.colSpan<1||selection.rowSpan<1)return
  const x=gridX(selection.col),y=gridY(selection.row),w=gridX(selection.col+selection.colSpan)-x,h=gridY(selection.row+selection.rowSpan)-y
  ctx.fillStyle='rgba(0,150,110,.2)';ctx.fillRect(x,y,w,h);ctx.strokeStyle='rgba(0,120,90,.8)';ctx.lineWidth=3;ctx.setLineDash([7,5]);ctx.strokeRect(x+1.5,y+1.5,w-3,h-3);ctx.setLineDash([]);ctx.lineWidth=1
}

export default function FrameSimulator(){
  const output=useRef<HTMLCanvasElement>(null),overlay=useRef<HTMLCanvasElement>(null),drag=useRef<{id:number;start:Point;lock?:DividerStrokeLock}|null>(null)
  const [layout,setLayout]=useState<LayoutName|'custom'>('default'),[dark,setDark]=useState(false),[preset,setPreset]=useState<Preset>('normal'),[debug,setDebug]=useState(false),[showcase,setShowcase]=useState(false),[showcaseModule,setShowcaseModule]=useState<StudioModuleName>('date')
  const [history,setHistory]=useState<EditorHistory>(()=>createHistory()),[dragPoint,setDragPoint]=useState<Point|null>(null),[selected,setSelected]=useState<string|null>(null),[feedback,setFeedback]=useState('')
  const custom=history.present
  const dragPreview=useMemo(()=>drag.current&&dragPoint?previewDividerStroke(custom,{start:drag.current.start,end:dragPoint,lock:drag.current.lock},VIEWPORT):null,[custom,dragPoint])
  const pointer=(e:React.PointerEvent<HTMLDivElement>):Point=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*VIEWPORT.width/r.width,y:(e.clientY-r.top)*VIEWPORT.height/r.height}}
  const onDown=(e:React.PointerEvent<HTMLDivElement>)=>{if(layout!=='custom')return;e.currentTarget.setPointerCapture(e.pointerId);const start=pointer(e);drag.current={id:e.pointerId,start};setDragPoint(start);setFeedback('')}
  const onMove=(e:React.PointerEvent<HTMLDivElement>)=>{if(drag.current?.id===e.pointerId){const end=pointer(e);drag.current.lock??=resolveDividerStrokeLock({start:drag.current.start,end},VIEWPORT);setDragPoint(end)}}
  const onUp=(e:React.PointerEvent<HTMLDivElement>)=>{if(drag.current?.id!==e.pointerId)return;const end=pointer(e),{start}=drag.current,lock=drag.current.lock??resolveDividerStrokeLock({start,end},VIEWPORT),result=finalizeDividerStroke(custom,start,end,VIEWPORT,lock);if(result.valid){setHistory(h=>pushHistory(h,result.cells));setSelected(null)}else if(Math.hypot(end.x-start.x,end.y-start.y)>=8)setFeedback(result.reason??'That divider stroke is not rectangular');drag.current=null;setDragPoint(null)}
  const choose=(moduleId:StudioModuleName|'empty')=>{if(!selected)return;setHistory(h=>pushHistory(h,h.present.map(c=>c.id===selected?{...c,moduleId}:c)));setSelected(null)}
  const reset=()=>{setHistory(createHistory());setSelected(null);setFeedback('')}
  const beginCustom=()=>{setLayout('custom');setHistory(createHistory());setDragPoint(null);setSelected(null);setFeedback('')}
  const editCopy=()=>{if(layout==='custom')return;const cells=cellsForLayout(layout).map((c,i)=>({id:`copy-${layout}-${i}`,col:c.col,row:c.row,colSpan:c.colSpan,rowSpan:c.rowSpan,moduleId:productionAssignments[layout][i]??'empty'} as EditorCell));setHistory(createHistory(cells));setLayout('custom')}
  useEffect(()=>{const ctx=output.current!.getContext('2d')!,ox=overlay.current!.getContext('2d')!,paper=dark?'#000':'#fff',ink=dark?'#fff':'#000';ctx.imageSmoothingEnabled=false;ctx.fillStyle=paper;ctx.fillRect(0,0,PANEL.width,PANEL.height);ctx.strokeStyle=ink
    if(layout==='custom'){custom.forEach((cell,i)=>{const px=editorPixelCell(cell,i);if(cell.moduleId!=='empty')drawModule(ctx,px,cell.moduleId,preset,ink)});internalDividerSegments(custom).forEach(segment=>segment.axis==='vertical'?line(ctx,gridX(segment.boundary),gridY(segment.from),gridX(segment.boundary),gridY(segment.to)):line(ctx,gridX(segment.from),gridY(segment.boundary),gridX(segment.to),gridY(segment.boundary)))}
    else{const cells=cellsForLayout(layout);dividersForLayout(layout).forEach(d=>line(ctx,d.x1,d.y1,d.x2,d.y2));cells.forEach((cell,i)=>drawModule(ctx,cell,productionAssignments[layout][i]??'date',preset,ink))}
    quantizeOneBit(ctx,dark);ox.clearRect(0,0,PANEL.width,PANEL.height)
    if(layout==='custom'){drawSnapGrid(ox,null);internalDividerSegments(dragPreview?.valid?dragPreview.cells:custom).forEach(segment=>{ox.strokeStyle='rgba(25,30,35,.72)';ox.lineWidth=2;segment.axis==='vertical'?line(ox,gridX(segment.boundary),gridY(segment.from),gridX(segment.boundary),gridY(segment.to)):line(ox,gridX(segment.from),gridY(segment.boundary),gridX(segment.to),gridY(segment.boundary));ox.lineWidth=1});dragPreview?.inferredKeys?.forEach(unit=>{const [axis,fixed,along]=unit.split(':');ox.strokeStyle='rgba(22,135,255,.7)';ox.lineWidth=2;axis==='vertical'?line(ox,gridX(Number(fixed)),gridY(Number(along)),gridX(Number(fixed)),gridY(Number(along)+1)):line(ox,gridX(Number(along)),gridY(Number(fixed)),gridX(Number(along)+1),gridY(Number(fixed)))});if(dragPreview?.intent!=='erase'&&dragPreview?.normalized&&dragPreview.normalized.rangeStart<dragPreview.normalized.rangeEnd){const stroke=dragPreview.normalized;ox.strokeStyle='#1687ff';ox.lineWidth=3;ox.lineCap='round';stroke.orientation==='vertical'?line(ox,gridX(stroke.boundary),gridY(stroke.rangeStart),gridX(stroke.boundary),gridY(stroke.rangeEnd)):line(ox,gridX(stroke.rangeStart),gridY(stroke.boundary),gridX(stroke.rangeEnd),gridY(stroke.boundary));ox.lineCap='butt';ox.lineWidth=1}}
    if(debug){ox.strokeStyle='#b14cff';for(let i=0;i<=4;i++){line(ox,gridX(i),VIEWPORT.y,gridX(i),VIEWPORT.y+VIEWPORT.height);line(ox,VIEWPORT.x,gridY(i),VIEWPORT.x+VIEWPORT.width,gridY(i))}}
  },[layout,dark,preset,debug,custom,selected,dragPreview])
  return <main className={styles.shell}><header className={styles.header}><div><h1 className={styles.title}>Frame layout studio</h1><p className={styles.note}>Draw to split · trace to erase</p></div><div className={styles.controls}><label>Layout <select value={layout} onChange={e=>setLayout(e.target.value as LayoutName|'custom')}><option value="full">Full</option><option value="default">Default</option><option value="pyramid">Pyramid</option><option value="square">Square</option>{layout==='custom'&&<option value="custom">Custom</option>}</select></label><button onClick={beginCustom}>New layout</button>{layout!=='custom'&&<button onClick={editCopy}>Edit copy</button>}<button onClick={reset} disabled={layout!=='custom'}>Reset</button><button onClick={()=>setHistory(undoHistory)} disabled={layout!=='custom'||!history.past.length}>Undo</button><button onClick={()=>setHistory(redoHistory)} disabled={layout!=='custom'||!history.future.length}>Redo</button><span className={styles.group}>Theme <button className={dark?'':styles.active} onClick={()=>setDark(false)}>Light</button><button className={dark?styles.active:''} onClick={()=>setDark(true)}>Dark</button></span><label>Sample data <select value={preset} onChange={e=>setPreset(e.target.value as Preset)}>{REMINDER_STUDIO_PRESET_VALUES.map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></label><label className={styles.toggle}><input type="checkbox" checked={debug} onChange={e=>setDebug(e.target.checked)}/> Debug</label><button className={showcase?styles.active:''} onClick={()=>setShowcase(v=>!v)}>Responsive Geometry Showcase</button></div></header>{showcase&&<GeometryShowcase module={showcaseModule} setModule={setShowcaseModule} preset={preset} debug={debug}/>}<div className={styles.workspace}><div className={styles.stage} onPointerDown={onDown} onPointerMove={onMove} onPointerUp={onUp} onPointerCancel={()=>{drag.current=null;setDragPoint(null)}} onLostPointerCapture={()=>{drag.current=null;setDragPoint(null)}}><canvas ref={output} className={styles.canvas} width="800" height="480" aria-label="One-bit e-paper viewport preview"/><canvas ref={overlay} className={styles.overlay} width="800" height="480" aria-label="Layout editor overlays"/>{layout==='custom'&&<div className={styles.hint}>Draw to split · trace to erase</div>}</div>{feedback&&<p className={styles.feedback}>{feedback}</p>}{selected&&layout==='custom'&&<aside className={styles.picker}><strong>Choose content</strong><div>{studioModuleRegistry.map(module=><button key={module.id} onClick={()=>choose(module.id)}>{module.label}</button>)}<button onClick={()=>choose('empty')}>Empty / clear</button></div></aside>}</div>{debug&&<p className={styles.debug}>Viewport 800×480 · production origin (0, 0) · generated slots are ordered top-to-bottom, then left-to-right.</p>}</main>
}

function ShowcaseCell({module,colSpan,rowSpan,preset,debug}:{module:StudioModuleName;colSpan:number;rowSpan:number;preset:Preset;debug:boolean}){
  const ref=useRef<HTMLCanvasElement>(null),w=gridX(colSpan)-gridX(0),h=gridY(rowSpan)-gridY(0)
  useEffect(()=>{const canvas=ref.current!,ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);drawModule(ctx,{col:0,row:0,colSpan,rowSpan,slot:0,size:legacyStudioVariant(colSpan,rowSpan)??'XL',x:0,y:0,w,h},module,preset,'#000');quantizeOneBit(ctx,false)},[module,colSpan,rowSpan,preset,w,h])
  const strategy=studioRenderStrategy(module,colSpan,rowSpan,w,h)
  return <figure className={styles.showcaseCell}><figcaption>{colSpan}×{rowSpan} · {responsiveCellProfile(colSpan,rowSpan,w,h).orientation}{debug&&<> · {strategy.profile.density} · {strategy.path}</>}</figcaption><canvas ref={ref} width={w} height={h}/></figure>
}
function GeometryShowcase({module,setModule,preset,debug}:{module:StudioModuleName;setModule:(m:StudioModuleName)=>void;preset:Preset;debug:boolean}){
  return <section className={styles.showcase}><div className={styles.showcaseTitle}><strong>Responsive Geometry Showcase</strong><label>Module <select value={module} onChange={e=>setModule(e.target.value as StudioModuleName)}>{responsiveShowcaseRegistry.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label><span>Deterministic sample data · all 16 geometry types</span></div><div className={styles.showcaseGrid}>{[1,2,3,4].flatMap(rowSpan=>[1,2,3,4].map(colSpan=><ShowcaseCell key={`${colSpan}x${rowSpan}`} module={module} colSpan={colSpan} rowSpan={rowSpan} preset={preset} debug={debug}/>))}</div></section>
}
