'use client'
import {useEffect,useRef,useState} from 'react'
import styles from './FrameSimulator.module.css'
import {PANEL,VIEWPORT,frameLayouts,cellsForLayout,gridX,gridY,isSupported,moduleProfiles,resolveGridCell,type LayoutName,type ModuleName,type PixelCell} from '../lib/frameSimulator'

type Preset='normal'|'long'|'extreme'|'empty'
const fake={
 date:{normal:['WEDNESDAY','AUGUST','19','2026'],long:['TORSDAG','DESEMBER','31','2026'],extreme:['WEDNESDAY','SEPTEMBER','30','2099'],empty:['DATE UNAVAILABLE','','','']},
 reminders:{normal:['REMINDERS','Dentist · 14:30','Buy coffee'],long:['REMINDERS','Renew the family travel insurance','Call the electrical contractor'],extreme:['REMINDERS','An exceptionally long reminder that exceeds its clipping region','Another overflowing reminder row'],empty:['NO REMINDERS','Enjoy the clear schedule']},
 weather:{normal:['OSLO','18°','Partly cloudy','12° / 21°'],long:['LONGYEARBYEN','-18°','Snow showers and strong wind','-24° / -12°'],extreme:['A VERY LONG LOCATION NAME','-123°','Exceptionally prolonged weather condition','-140° / 123°'],empty:['WEATHER UNAVAILABLE','','','']},
 countdown:{normal:['SUMMER HOLIDAY','42','days','30 June'],long:['ANNIVERSARY CELEBRATION','365','days','19 August 2027'],extreme:['AN EXTREMELY LONG COUNTDOWN EVENT LABEL','99999','days','31 December 2099'],empty:['NO COUNTDOWNS','','','']}
} satisfies Record<ModuleName,Record<Preset,string[]>>
const modules:ModuleName[]=['date','reminders','weather','countdown']
function line(ctx:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number){ctx.beginPath();ctx.moveTo(x1+.5,y1+.5);ctx.lineTo(x2+.5,y2+.5);ctx.stroke()}
function clipText(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,max:number){ctx.save();ctx.beginPath();ctx.rect(x,y-24,max,30);ctx.clip();ctx.fillText(text,x,y);ctx.restore()}
function drawModule(ctx:CanvasRenderingContext2D,c:PixelCell,m:ModuleName,p:Preset,ink:string){
 const d=fake[m][p], cx=c.x+c.w/2; ctx.save();ctx.beginPath();ctx.rect(c.x,c.y,c.w,c.h);ctx.clip();ctx.fillStyle=ink;ctx.strokeStyle=ink;ctx.textBaseline='alphabetic'
 if(m==='date'){if(c.size==='SMALL'){ctx.font='bold 24px sans-serif';ctx.textAlign='center';ctx.fillText(`${d[0]}, ${d[1]} ${d[2]}`,cx,c.y+c.h/2+8)}else{ctx.textAlign='center';ctx.font='14px sans-serif';ctx.fillText(d[3],cx,c.y+45);ctx.font='bold 20px sans-serif';ctx.fillText(d[1],cx,c.y+78);ctx.font='bold 48px sans-serif';ctx.fillText(d[2],cx,c.y+132);ctx.strokeRect(cx-75,c.y+150,150,42);ctx.font='bold 18px sans-serif';ctx.fillText(d[0],cx,c.y+178)}}
 if(m==='reminders'){const pad=moduleProfiles.reminders.smallPadding[0];ctx.textAlign='left';ctx.font='bold 18px sans-serif';ctx.fillText(d[0],c.x+pad,c.y+30);line(ctx,c.x+pad,c.y+38,c.x+Math.min(c.w-pad,150),c.y+38);ctx.font='bold 17px sans-serif';d.slice(1).forEach((v,i)=>clipText(ctx,v,c.x+pad,c.y+70+i*30,c.w-pad*2))}
 if(m==='weather'){ctx.textAlign='center';ctx.font='bold 18px sans-serif';ctx.fillText(d[0],cx,c.y+30);ctx.font='bold 42px sans-serif';ctx.fillText(d[1],cx,c.y+Math.min(88,c.h/2+20));ctx.font='16px sans-serif';ctx.fillText(d[2],cx,c.y+Math.min(118,c.h-30));ctx.fillText(d[3],cx,c.y+Math.min(145,c.h-10))}
 if(m==='countdown'){ctx.textAlign='center';ctx.font='bold 17px sans-serif';ctx.fillText(d[0],cx,c.y+30);ctx.font='bold 48px sans-serif';ctx.fillText(d[1],cx,c.y+Math.min(90,c.h-35));ctx.font='16px sans-serif';ctx.fillText(`${d[2]}  ·  ${d[3]}`,cx,c.y+Math.min(118,c.h-10))}
 ctx.restore()
}
export default function FrameSimulator(){
 const output=useRef<HTMLCanvasElement>(null),overlay=useRef<HTMLCanvasElement>(null);const [layout,setLayout]=useState<LayoutName>('default'),[dark,setDark]=useState(false),[preset,setPreset]=useState<Preset>('normal'),[test,setTest]=useState(false),[mod,setMod]=useState<ModuleName>('date'),[colSpan,setCS]=useState(4),[rowSpan,setRS]=useState(1),[col,setCol]=useState(0),[row,setRow]=useState(0);const [flags,setFlags]=useState({panel:true,viewport:true,grid:false,cells:true,slots:true,coords:true,content:false})
 const toggle=(k:keyof typeof flags)=>setFlags(v=>({...v,[k]:!v[k]}));let cells:PixelCell[]=[];let supported=true;try{cells=test?[resolveGridCell({col:Math.min(col,4-colSpan),row:Math.min(row,4-rowSpan),colSpan,rowSpan,slot:0,size:colSpan===4&&rowSpan===1?'SMALL':colSpan===2&&rowSpan===2?'MEDIUM':colSpan===4&&rowSpan===2?'LARGE':'XL'})]:cellsForLayout(layout);supported=!test||isSupported(mod,colSpan,rowSpan)}catch{cells=[];supported=false}
 useEffect(()=>{const c=output.current!,ctx=c.getContext('2d')!,o=overlay.current!,ox=o.getContext('2d')!;ctx.imageSmoothingEnabled=false;const paper=dark?'#000':'#fff',ink=dark?'#fff':'#000';ctx.fillStyle=paper;ctx.fillRect(0,0,PANEL.width,PANEL.height);const assigned:ModuleName[]=test?[mod]:['date','reminders','weather','countdown'];if(!test){const margin=Math.trunc(VIEWPORT.width*.025),vMargin=Math.trunc(VIEWPORT.height*.025);ctx.strokeStyle=ink;for(const div of frameLayouts.dividers[layout]){if(div.axis==='y')line(ctx,VIEWPORT.x+margin,gridY(div.boundary),VIEWPORT.x+VIEWPORT.width-margin,gridY(div.boundary));else{const from='from'in div?gridY(div.from):VIEWPORT.y+vMargin,to='to'in div?gridY(div.to):VIEWPORT.y+VIEWPORT.height-vMargin;line(ctx,gridX(div.boundary),from,to)}}}if(supported)cells.forEach((cell,i)=>drawModule(ctx,cell,assigned[i%assigned.length],preset,ink));else{ctx.fillStyle=ink;ctx.font='bold 28px monospace';ctx.textAlign='center';ctx.fillText('UNSUPPORTED — NEEDS NEW VARIANT',400,240)}ox.clearRect(0,0,800,480);ox.font='12px monospace';ox.textAlign='left';if(flags.panel){ox.strokeStyle='#ff3b3b';ox.strokeRect(.5,.5,799,479)}if(flags.viewport){ox.strokeStyle='#00a8ff';ox.strokeRect(VIEWPORT.x+.5,VIEWPORT.y+.5,VIEWPORT.width-1,VIEWPORT.height-1)}if(flags.grid){ox.strokeStyle='#ff00cc';for(let i=0;i<=4;i++){line(ox,gridX(i),VIEWPORT.y,gridX(i),VIEWPORT.y+VIEWPORT.height);line(ox,VIEWPORT.x,gridY(i),VIEWPORT.x+VIEWPORT.width,gridY(i))}}cells.forEach(cell=>{if(flags.cells){ox.strokeStyle='#00d26a';ox.strokeRect(cell.x+.5,cell.y+.5,cell.w-1,cell.h-1)}ox.fillStyle='#e6007a';if(flags.slots)ox.fillText(`S${cell.slot}`,cell.x+5,cell.y+14);if(flags.coords)ox.fillText(`${cell.x},${cell.y} ${cell.w}×${cell.h} [${cell.colSpan}×${cell.rowSpan}]`,cell.x+5,cell.y+29);if(flags.content){ox.strokeStyle='#ff8c00';ox.setLineDash([4,3]);ox.strokeRect(cell.x+12.5,cell.y+8.5,cell.w-25,cell.h-17);ox.setLineDash([])}})},[layout,dark,preset,test,mod,colSpan,rowSpan,col,row,flags,supported,cells.map(c=>`${c.x},${c.y},${c.w},${c.h}`).join('|')])
 return <main className={styles.shell}><h1 className={styles.title}>800×480 e-paper frame simulator</h1><p className={styles.note}>Exact integer geometry mirrors firmware. Browser glyph rasterization and baselines are approximate; boxes, clipping, origins and shared layout profiles are deterministic.</p><div className={styles.controls}><label>Mode <select value={test?'test':'layout'} onChange={e=>setTest(e.target.value==='test')}><option value="layout">Production layouts</option><option value="test">Module geometry test</option></select></label>{!test?<label>Layout <select value={layout} onChange={e=>setLayout(e.target.value as LayoutName)}>{Object.keys(frameLayouts.layouts).map(x=><option key={x}>{x}</option>)}</select></label>:<span className={styles.section}><label>Module <select value={mod} onChange={e=>setMod(e.target.value as ModuleName)}>{modules.map(x=><option key={x}>{x}</option>)}</select></label>{(['colSpan','rowSpan'] as const).map((key)=><label key={key}>{key}<input type="number" min="1" max="4" value={key==='colSpan'?colSpan:rowSpan} onChange={e=>(key==='colSpan'?setCS:setRS)(+e.target.value)}/></label>)}<label>col <input type="number" min="0" max="3" value={col} onChange={e=>setCol(+e.target.value)}/></label><label>row <input type="number" min="0" max="3" value={row} onChange={e=>setRow(+e.target.value)}/></label></span>}<label>Preset <select value={preset} onChange={e=>setPreset(e.target.value as Preset)}>{['normal','long','extreme','empty'].map(x=><option key={x}>{x}</option>)}</select></label><label><input type="checkbox" checked={dark} onChange={e=>setDark(e.target.checked)}/>dark frame</label>{Object.entries(flags).map(([k,v])=><label key={k}><input type="checkbox" checked={v} onChange={()=>toggle(k as keyof typeof flags)}/>{k}</label>)}</div>{test&&!supported&&<p className={styles.warning}>UNSUPPORTED — NEEDS NEW VARIANT. The renderer is not scaled or redesigned.</p>}<div className={styles.stage}><canvas ref={output} className={styles.canvas} width="800" height="480" aria-label="Static one-bit e-paper output"/><canvas ref={overlay} className={styles.overlay} width="800" height="480" aria-label="Developer geometry overlays"/></div><p className={styles.legend}>Overlay colors: red panel · blue viewport · magenta grid · green cells · orange module content bounds. Disable all overlay toggles for final static output.</p></main>
}
