from pathlib import Path

path = Path('app/HomePageClient.tsx')
text = path.read_text()

old_type = """  current: {\n    temp_c: number | null\n    wind_mps: number | null\n    wind_dir_deg: number | null\n    gust_mps: number | null\n    precipitation_1h_mm: number | null\n  }\n  forecast: Array<{\n"""
new_type = """  current: {\n    temp_c: number | null\n    wind_mps: number | null\n    wind_dir_deg: number | null\n    gust_mps: number | null\n    precipitation_1h_mm: number | null\n  }\n  snow: {\n    snow_depth_cm: number | null\n    fresh_24h_cm: number | null\n    fresh_72h_cm: number | null\n    altitude_m: number | null\n    source_date: string | null\n    grid: { x: number; y: number }\n  }\n  forecast: Array<{\n"""
assert text.count(old_type) == 1, f'type block count={text.count(old_type)}'
text = text.replace(old_type, new_type, 1)

old_derived = """  const current = summary?.current ?? null\n  const mainLine = current\n    ? `${formatSkiTemperature(current.temp_c)} · ${skiWindDirectionLabel(current.wind_dir_deg)} ${formatSkiMetric(current.wind_mps)} m/s`\n    : null\n"""
new_derived = """  const current = summary?.current ?? null\n  const snow = summary?.snow ?? null\n  const snowLine = snow && (snow.fresh_24h_cm != null || snow.snow_depth_cm != null)\n    ? `${formatSkiMetric(snow.fresh_24h_cm)} cm ${isNo ? 'nysnø' : 'fresh'} · ${formatSkiMetric(snow.snow_depth_cm)} cm ${isNo ? 'totalt' : 'total'}`\n    : null\n  const mainLine = snowLine || (current\n    ? `${formatSkiTemperature(current.temp_c)} · ${skiWindDirectionLabel(current.wind_dir_deg)} ${formatSkiMetric(current.wind_mps)} m/s`\n    : null)\n"""
assert text.count(old_derived) == 1, f'derived block count={text.count(old_derived)}'
text = text.replace(old_derived, new_derived, 1)

old_stats = """                <div className=\"text-4xl font-medium tracking-[-0.04em] text-[color:var(--fg-95)]\">{mainLine}</div>\n                <div className=\"mt-7 grid grid-cols-2 gap-x-6 gap-y-5 border-t border-[color:var(--bd-10)] pt-5\">\n                  <div>\n                    <div className=\"text-[10px] uppercase tracking-[0.18em] text-[color:var(--fg-45)]\">{isNo ? 'VINDKAST' : 'GUSTS'}</div>\n                    <div className=\"mt-1 text-lg text-[color:var(--fg-80)]\">{current.gust_mps != null ? formatSkiMetric(current.gust_mps) + ' m/s' : '–'}</div>\n                  </div>\n                  <div>\n                    <div className=\"text-[10px] uppercase tracking-[0.18em] text-[color:var(--fg-45)]\">{isNo ? 'NEDBØR NESTE TIME' : 'PRECIP NEXT HOUR'}</div>\n                    <div className=\"mt-1 text-lg text-[color:var(--fg-80)]\">{current.precipitation_1h_mm != null ? formatSkiMetric(current.precipitation_1h_mm, 1) + ' mm' : '–'}</div>\n                  </div>\n                </div>\n"""
new_stats = """                <div className=\"text-4xl font-medium tracking-[-0.04em] text-[color:var(--fg-95)]\">{mainLine}</div>\n                <div className=\"mt-7 grid grid-cols-2 gap-x-6 gap-y-5 border-t border-[color:var(--bd-10)] pt-5\">\n                  <div>\n                    <div className=\"text-[10px] uppercase tracking-[0.18em] text-[color:var(--fg-45)]\">{isNo ? 'NYSNØ 3 DØGN' : 'FRESH 3 DAYS'}</div>\n                    <div className=\"mt-1 text-lg text-[color:var(--fg-80)]\">{snow?.fresh_72h_cm != null ? formatSkiMetric(snow.fresh_72h_cm) + ' cm' : '–'}</div>\n                  </div>\n                  <div>\n                    <div className=\"text-[10px] uppercase tracking-[0.18em] text-[color:var(--fg-45)]\">{isNo ? 'TEMPERATUR' : 'TEMPERATURE'}</div>\n                    <div className=\"mt-1 text-lg text-[color:var(--fg-80)]\">{formatSkiTemperature(current.temp_c)}</div>\n                  </div>\n                  <div>\n                    <div className=\"text-[10px] uppercase tracking-[0.18em] text-[color:var(--fg-45)]\">{isNo ? 'VIND' : 'WIND'}</div>\n                    <div className=\"mt-1 text-lg text-[color:var(--fg-80)]\">{skiWindDirectionLabel(current.wind_dir_deg)} · {formatSkiMetric(current.wind_mps)} m/s</div>\n                  </div>\n                  <div>\n                    <div className=\"text-[10px] uppercase tracking-[0.18em] text-[color:var(--fg-45)]\">{isNo ? 'VINDKAST' : 'GUSTS'}</div>\n                    <div className=\"mt-1 text-lg text-[color:var(--fg-80)]\">{current.gust_mps != null ? formatSkiMetric(current.gust_mps) + ' m/s' : '–'}</div>\n                  </div>\n                </div>\n                <div className=\"mt-5 text-[11px] text-[color:var(--fg-40)]\">NVE SeNorge · MET Norway</div>\n"""
assert text.count(old_stats) == 1, f'stats block count={text.count(old_stats)}'
text = text.replace(old_stats, new_stats, 1)

path.write_text(text)
